workshops/templates/workshops/person.html, workshops/views.py
1.  Collect information in view.
2.  Display on person details page.
This closes #25.
=> Displaying awards and tasks on the person details page.

workshops/templates/workshops/all_badges.html, workshops/templates/workshops/badge.html, workshops/templates/workshops/index.html, workshops/urls.py, workshops/views.py
Adds views to display details of badges (name, criteria, etc.) and who they've been awarded to.
This closes #35 and #36.
=> Display badges

workshops/forms.py, workshops/templates/workshops/instructors.html, workshops/views.py
1.  Add pulldown field for airport IATA code to instructor matching form.
2.  Add logic to process airport *or* latitude+longitude.
3.  Add some error reporting.
=> Allowing search by known airport.

requirements.txt
=> Adding 'requests' library to 'requirements.txt'

workshops/models.py, workshops/templates/workshops/all_tasks.html, workshops/templates/workshops/person.html, workshops/templates/workshops/task.html, workshops/test/test_tasks.py, workshops/urls.py, workshops/views.py
Fixes #153.  See earlier discussion there.
=> Link to tasks by ID

workshops/static/amy.css, workshops/templates/workshops/person_bulk_add_results.html, workshops/urls.py, workshops/views.py
This PR is a solution to #138.
Work-in-progress.
=> Bulk people CSV upload confirmation page

workshops/migrations/0040_auto_20150120_1610.py, workshops/models.py, workshops/views.py
=> Add default ordering to Event

amy/settings.py, workshops/models.py, workshops/templates/workshops/_page.html, workshops/templates/workshops/person_bulk_add_form.html, workshops/templates/workshops/person_bulk_add_results.html, workshops/test/test_util.py, workshops/urls.py, workshops/util.py, workshops/views.py
* Redirect when no session data after bulk upload
* case-insensitive email look up
* Move csv parsing to util.py, add test
* Move verification to util.py, add tests
* Ensure data structure from csv parsing is json-serializable
=> Add various tweaks and improvements to CSV parsing

workshops/migrations/0002_auto_20150219_1305.py, workshops/models.py
=> Make Site.notes blank

workshops/forms.py, workshops/templates/workshops/debrief.html, workshops/urls.py, workshops/views.py
Address #213.
**This doesn't have a link from the home page.**
=> Add selection to debrief session

workshops/templates/workshops/all_airports.html, workshops/templates/workshops/all_events.html, workshops/templates/workshops/all_persons.html, workshops/templates/workshops/all_sites.html, workshops/templates/workshops/all_tasks.html
These buttons are now placed above and below data tables in index pages:
* airports
* events
* persons
* sites
* tasks
=> Templates: add "Add new *" buttons

workshops/check.py, workshops/views.py
This fixes errors relating to the missing basestring in Python 3
=> Pull latest version of check.py from https://github.com/swcarpentry/workshop-template/blob/gh-pages/tools/check.py

workshops/test/test_util.py, workshops/test/upload-malformed-file-with-header.csv, workshops/util.py
Do nothing if we try to upload user and assigned task that already exist.
This solves #211.
=> Bulk-upload: no-op when user and task exist

workshops/util.py
This commit resolves #226 
create_uploaded_persons_tasks function was required to match email case-insensitive before creating a new person
=> Case-insensitive matching of email

amy/settings.py, requirements.txt, workshops/forms.py, workshops/models.py, workshops/static/css/amy.css, workshops/templates/workshops/airport_form.html, workshops/templates/workshops/all_events.html, workshops/templates/workshops/all_persons.html, workshops/templates/workshops/badge.html, workshops/templates/workshops/cohort_form.html, workshops/templates/workshops/debrief.html, workshops/templates/workshops/event.html, workshops/templates/workshops/event_create_form.html, workshops/templates/workshops/event_edit_form.html, workshops/templates/workshops/instructors.html, workshops/templates/workshops/person.html, workshops/templates/workshops/person_form.html, workshops/templates/workshops/search.html, workshops/templates/workshops/site.html, workshops/templates/workshops/site_form.html, workshops/templates/workshops/task_form.html, workshops/test/base.py, workshops/test/test_person.py, workshops/views.py
Resolves #240.
See discussion in #240 and #237.
=> `None` values in forms + introduction of crispy-forms

workshops/templates/account/logged_out.html, workshops/templates/account/login.html, workshops/templates/amy-logo.html, workshops/templates/workshops/index.html
This should probably be done using an 'include' directive of some kind, since it's exactly the same HTML as is used in index.html.
=> Adding the Amy logo to the login page

workshops/templates/workshops/search.html
It's a lot easier to find things this way.
=> Putting search results in columns for easier reading

amy/settings.py, requirements.txt, workshops/migrations/0005_auto_20150404_0953.py, workshops/test/base.py
Resolves #237. (See also discussion in #240.)
This should be merged after #242, but will probably cause conflicts in `settings.py`.
=> Upgrade to Django 1.8

workshops/templates/base_without_navbar.html, workshops/templates/workshops/debrief.html, workshops/templates/workshops/event_edit_form.html
Due to some changes in recent PRs, the datepicker widget broke. Here are my fixes to get it working.
=> Fix datepicker widget

workshops/models.py, workshops/test/test_event.py, workshops/test/test_landing_page.py
1.  Upcoming workshops are only displayed if they have been published.
2.  Workshops are only listed as unpaid if they've taken place (and owe us money).
=> Slimming down the workshops displayed on the dashboard.

workshops/templates/base_without_navbar.html
=> Displaying title correctly on home page

workshops/templates/base.html
Implemented similarily to the "+" on the GitHub (top-right corner).
This supersedes #280.
=> Top nav: new shortcut to add new event/site/person

Makefile, README.md
We no longer need to import data from the old database, and we're generating reports programmatically now.
=> Stripping old stuff out of Makefile

workshops/templates/workshops/all_persons.html, workshops/views.py
1.  Show whether a person is an instructor in the "all persons" display.
2.  Have their full name link to their details page.
3.  Have their email address be a mailto: link.
=> Creating a more useful display of persons.

workshops/migrations/0008_person_notes.py, workshops/models.py, workshops/templates/workshops/person.html, workshops/test/base.py, workshops/test/test_person.py, workshops/views.py
Solves #323.
One bug was discovered and fixed, see commits in this PR.
=> Add `Person.notes`

workshops/templates/base.html, workshops/templates/workshops/all_events.html, workshops/templates/workshops/all_persons.html, workshops/templates/workshops/all_tasks.html, workshops/templates/workshops/badge.html, workshops/templates/workshops/debrief.html, workshops/templates/workshops/event.html, workshops/templates/workshops/event_edit_form.html, workshops/templates/workshops/instructors.html, workshops/templates/workshops/person.html, workshops/test/test_instructors.py, workshops/test/test_person.py
This resolves #307, #310, #311, #312 (and #315, and fixes the same issue on other pages), plus this enhances person details page.
=> Graphical updates

workshops/models.py
=> Sorting uninvoiced events oldest-first to improve dashboard display.

workshops/forms.py, workshops/static/css/amy.css, workshops/templates/base.html, workshops/templates/workshops/person.html, workshops/test/base.py, workshops/test/test_person.py, workshops/urls.py, workshops/views.py
This resolves #326.
Not sure if I need to test password changing feature, because it relies upon Django forms.
=> Changing passwords and permissions

workshops/forms.py, workshops/static/css/amy.css, workshops/templates/workshops/instructors.html, workshops/views.py
Preview (UPDATE):  
UPDATE: As discussed, I wrapped the three fields in a single row. I utilised panels to show lat/long.
=> Make AMY show list of skills horizontally

workshops/forms.py, workshops/templates/base_without_navbar.html, workshops/templates/workshops/event_edit_form.html, workshops/templates/workshops/person_edit_form.html, workshops/test/test_event.py, workshops/views.py
This PR:
1. adds messages to edit/create views
2. makes messages visually nicer (with http://getbootstrap.com/components/#alerts)
3. cleans up event-edit view (so it works very similar to person-edit)
4. shifts second form up on event/person-edit pages
Resolves #339.
=> Verbose messages

workshops/management/commands/check_badges.py
Usernames alone are causing extra work - this gives full names and email addresses so that I can generate certificates and badges more easily.
=> Making output of check_badges more useful

workshops/templates/workshops/all_airports.html, workshops/views.py
=> Paginating airport display

workshops/views.py
=> Search: include event.site.domain and event.site.fullname

workshops/templates/workshops/debrief.html, workshops/test/test_debrief.py, workshops/views.py
Now we only select events that happened within user-selected date range.
=> Debrief only finished workshops

scripts/mail-all-activity.py
Merging this because (a) we used it and it works and (b) it doesn't affect anything else.
=> Improving mailout scripts

workshops/forms.py, workshops/migrations/0011_auto_20150618_0231.py, workshops/models.py, workshops/static/css/amy.css, workshops/templates/workshops/all_airports.html, workshops/templates/workshops/all_events.html, workshops/templates/workshops/all_persons.html, workshops/templates/workshops/all_sites.html, workshops/templates/workshops/all_tasks.html, workshops/templates/workshops/event.html, workshops/views.py
For:
* #313 
* #353 
* #369 
* #371
* #368
=> Bunch of quickfixes

amy/settings.py, requirements.txt, workshops/filters.py, workshops/forms.py, workshops/migrations/0011_person_badges.py, workshops/migrations/0015_merge.py, workshops/models.py, workshops/static/css/amy.css, workshops/templates/base.html, workshops/templates/base_without_navbar.html, workshops/templates/workshops/_page_fluid.html, workshops/templates/workshops/all_airports.html, workshops/templates/workshops/all_events.html, workshops/templates/workshops/all_persons.html, workshops/templates/workshops/all_sites.html, workshops/templates/workshops/all_tasks.html, workshops/templates/workshops/person.html, workshops/views.py
Resolves #256.
Resolves #129.
Work in progress: fix for #189, filters for other models (Airport, Task).
Changes:
* formerly invisible relationship between persons and their badges is now explicit (similar should be done for future person↔lesson relationship)
* new fluid (ie. width=100%) view
* filtering added for Event, Site, Person list views
Preview:
Please pull it down and try yourself and tell me what you think.
Thanks,
Piotr
=> Poor man's DataTables (ie. filters)

workshops/templates/pagination.html, workshops/templatetags/pagination.py, workshops/util.py, workshops/views.py
@carlosp420 and my work.
See #381.
=> Nicer pagination bar (new)

workshops/forms.py, workshops/templates/base.html, workshops/templates/workshops/person_merge_confirm.html, workshops/templates/workshops/person_merge_form.html, workshops/templatetags/merging_utils.py, workshops/test/test_person.py, workshops/urls.py, workshops/util.py, workshops/views.py
This is @gvwilson's work from #366 (rebased and enhanced).
WIP: missing tests.
This fixes #193.
This suppresses #366.
=> Merging people (new)

scripts/anonymizer.py
* Overwrite user passwords
* Don't accidentally make unpublished events published
* Drop historical data from django-reversion
* Add a reminder for the user to populate initial revisions
for all tracked objects
WIP: development DB update
=> Enhance anonymizer + update development DB

workshops/management/commands/upgrade_instructor_profiles.py, workshops/migrations/0025_auto_20150707_0809.py, workshops/migrations/0026_add_missing_airports.py, workshops/models.py
1.  Reformatting some bits of code.
2.  Adding migrations to add airports and discpline names.
=> Changes made while importing latest instructor data.

workshops/templates/workshops/person.html, workshops/views.py
Use 2-column layout for the awards/tasks and domains/lessons.
This fixes #417.
=> Show person's knowledge domains + lessons they can teach

workshops/forms.py, workshops/static/css/amy.css, workshops/templates/workshops/instructors.html, workshops/test/test_instructors.py, workshops/views.py
The Find Instructors page had a facelifting.
This fixes #394.
All changes are listed in the commit messages, the important and visible ones:
1. No more "wanted" field; instead pagination with sorting by distance is in place.
2. Filter instructors by their country.
=> Find instructors by country + other improvements

workshops/forms.py, workshops/static/css/amy.css, workshops/templates/workshops/person_edit_form.html, workshops/test/test_person.py, workshops/views.py
This fixes #391.
More in the commit messages.
=> Add tasks from person edit

workshops/templates/workshops/_page_fluid_nosidebar.html, workshops/templates/workshops/person_bulk_add_results.html, workshops/util.py
This fixes #389.
The resulting improvement in the verboseness of the bulk uploader is shown below:
=> More verbose bulk upload

workshops/models.py, workshops/test/test_person.py
Sorts all Lessons alphabetically.
Fixes #422.
=> Added ordering field to Meta class for Lessons.

workshops/forms.py, workshops/management/commands/upgrade_instructor_profiles.py, workshops/migrations/0028_person_affiliation.py, workshops/models.py, workshops/templates/workshops/instructors.html, workshops/templates/workshops/person.html, workshops/templates/workshops/person_diff.html, workshops/templates/workshops/person_merge_confirm.html, workshops/test/test_commands.py
This solves #412.
New field, `Person.affiliation`, was added. It's being displayed on "Find Instructors" page, too.
=> Person affiliation field

workshops/templates/workshops/event_create_form.html, workshops/test/test_util.py, workshops/urls.py, workshops/util.py, workshops/views.py
More details in commit messages.
=> Import event data from URL

workshops/forms.py, workshops/test/test_event.py
=> Event start date must be earlier than it's end date

.travis.yml
See http://docs.travis-ci.com/user/migrating-from-legacy/
=> Switching Travis-CI to use containers

workshops/templates/workshops/event.html, workshops/templates/workshops/event_diff.html
This fixes #5 by adding "Find closest instructors" to events that have lat/long set.
=> Find closest instructors

workshops/filters.py, workshops/forms.py, workshops/migrations/0037_auto_20150728_0227.py, workshops/models.py, workshops/test/base.py, workshops/test/test_instructors.py, workshops/views.py
1. Hosts are sorted by domain (this makes items for Host, Administrator selects on the All Events page sorted, too)
2. A lot better list of countries within filter on All Hosts, Find Instructors pages
3. Only hosts used as hosts are now selectable within filter on All Events page
4. Multiple country select for Find Instructors
5. Filter by gender on Find Instructors
This fixes #445.
This fixes #385.
=> Better filtering by countries + filtering by gender

workshops/templates/workshops/event_create_form.html, workshops/templates/workshops/event_edit_form.html
This fixes #442.
It's pure JS so it doesn't require tests.
=> Add "Update from URL" functionality

workshops/migrations/0038_auto_20150809_0534.py, workshops/models.py
Some venue details are very, very long (like precise description of
route to take to get into the workshop room).  These fields needed
to be extended.
=> Make event location fields longer

api/serializers.py, api/test/test_events.py, api/urls.py, api/views.py
This 3 new API endpoints add possibility to find:
- all past workshops
- currently running workshops
- upcoming workshops
I hope I didn't mess up ordering in `api/views.py` :-)
=> Workshops API

Makefile, workshops/management/commands/check_certificates.py
Adds a new management command to check awards listed in database against certificates stored on disk.
=> Checking PDF certificates against database

workshops/templates/workshops/dashboard.html, workshops/test/base.py, workshops/test/test_event.py, workshops/test/test_landing_page.py, workshops/views.py
This fixes #495.
The fix was pretty easy thanks to the QuerySet logic.
=> Upcoming & ongoing on the dashboard

workshops/check.py
...which is upstream.
Ref https://github.com/swcarpentry/workshop-template/issues/251
=> Pull `check.py` from @swcarpentry/workshop-template

workshops/templates/workshops/all_events.html, workshops/templates/workshops/all_hosts.html, workshops/templates/workshops/event.html, workshops/templates/workshops/host.html, workshops/templates/workshops/person.html, workshops/templates/workshops/person_merge_confirm.html, workshops/templates/workshops/profileupdaterequest.html, workshops/templatetags/links.py
=> Open external links in new tab

workshops/migrations/0051_auto_20150929_0847.py, workshops/test/test_event.py, workshops/test/test_util.py, workshops/util.py, workshops/views.py
=> Automatically count event attendees

scripts/anonymizer.py
This adds development database and some required changes to the anonymizer script.
Fixes #491.
=> Updated anonymizer script + dev DB

workshops/models.py, workshops/templates/workshops/airport.html, workshops/templates/workshops/event.html, workshops/templates/workshops/host.html, workshops/templates/workshops/last_modified.html, workshops/templates/workshops/person.html, workshops/templates/workshops/task.html, workshops/templatetags/revisions.py
Thanks to using djang-reversion, it wasn't that hard to do.
This fixes #518.
=> Add "created by", "last modified by"

workshops/templates/workshops/instructor_issues.html, workshops/views.py
Show people who have been through instructor training but are not yet qualified instructors.
=> Report incomplete instructors

workshops/templates/base_without_navbar.html
@ethanwhite @pbanaszkiewicz please review
=> Giving credit to Ethan White's support

workshops/models.py, workshops/templates/workshops/event.html
This fixes #520.
I considered making a method/property on `Event` model that calculates the link, for the sake of testability, but then I started wondering how would tests look like. Probably I would hard-code resulting URLs and check if the said method returns exactly same string…
=> Event details page: add link to Invoice form for NUMFocus

bower.json, workshops/forms.py, workshops/migrations/0055_todoitem.py, workshops/models.py, workshops/static/calendar_popup.js, workshops/static/css/amy.css, workshops/templates/workshops/event.html, workshops/templates/workshops/todos_add.html, workshops/test/test_todos.py, workshops/urls.py, workshops/views.py
Hi,
this is a big new feature for v1.1. This PR enables admins to set up TODOs for events. We'll see if they like it.
This fixes #483.
=> TODO lists for events

workshops/templates/workshops/instructor_num_taught.html, workshops/templates/workshops/workshop_issues.html, workshops/urls.py, workshops/views.py
Sending out messages to prod people for attendance figures, came up with a stronger wording - please check that it's OK.
=> Fixing email wording

amy/urls.py, workshops/forms.py, workshops/migrations/0058_auto_20151105_1452.py, workshops/migrations/0059_auto_20151109_1006.py, workshops/models.py, workshops/templates/account/login.html, workshops/templates/account/password_reset.html, workshops/templates/account/password_reset_complete.html, workshops/templates/account/password_reset_confirm.html, workshops/templates/account/password_reset_done.html
=> Reset password form

workshops/static/css/amy.css, workshops/templates/workshops/event.html, workshops/views.py
This fixes #540.
Unfortunately the change in 0fec918 adds a lot of workshops to the "Workshop issues" page.
=> Highlight issues on event page

workshops/filters.py, workshops/forms.py, workshops/lookups.py, workshops/migrations/0060_auto_20151111_1245.py, workshops/models.py, workshops/templates/workshops/all_eventrequests.html, workshops/templates/workshops/all_events.html, workshops/templates/workshops/dashboard.html, workshops/templates/workshops/event.html, workshops/templates/workshops/eventrequest.html, workshops/test/test_assignments.py, workshops/test/test_event_requests.py, workshops/test/test_landing_page.py, workshops/urls.py, workshops/views.py
This PR adds new feature: assigning admins to events and event requests.
This fixes #537.
=> Assignments for admins

workshops/templates/workshops/instructor_issues.html
Having been away from this for a few weeks, I didn't know what the first table was showing me, so I've titled both.
=> Making titles on instructor issue page more descriptive

workshops/views.py
=> Search in Event's URL, contact, venue and address fields

workshops/forms.py, workshops/templates/workshops/profileupdaterequest.html, workshops/urls.py, workshops/views.py
This fixes multiple small issues we had about profile update requests machinery: #532, #573.
=> Profile update request fix + redirection to user's profile after approving

scripts/mail-all-activity.py, workshops/management/commands/report_all_instructor_activity.py
Need to update activity and profile information in advance of January's election.
=> Updating command used to poke instructors about their activity and profiles

workshops/static/import_from_url.js, workshops/static/update_from_url.js, workshops/templates/workshops/event_create_form.html, workshops/templates/workshops/event_edit_form.html, workshops/templates/workshops/event_import_update_from_url.html, workshops/test/test_util.py, workshops/util.py, workshops/views.py
This fixes #618. See commit messages for details.
=> Indication of wrong URL

api/test/test_export.py, workshops/forms.py, workshops/management/commands/report_all_instructor_activity.py, workshops/management/commands/report_incomplete_instructors.py, workshops/management/commands/upgrade_instructor_profiles.py, workshops/migrations/0064_dc_instructor_badge.py, workshops/models.py, workshops/templates/base.html, workshops/templates/workshops/all_persons.html, workshops/templates/workshops/instructors.html, workshops/test/base.py, workshops/test/test_badge.py, workshops/test/test_commands.py, workshops/test/test_person.py, workshops/util.py, workshops/views.py
This fixes #596 by:
* changing original 'instructor' badge into 'swc-instructor'
* adding a new 'dc-instructor' badge
* changing all logic behind original 'instructor' badge to work with multiple badges ending in 'instructor'.
=> New instructor badge: DC Instructor

workshops/admin.py
This way we can adjust tags or lessons without adding migrations.
=> Add basic models into admin management interface

workshops/filters.py
=> Filter people by type of workshops they taught at

api/serializers.py, api/urls.py, api/views.py, bower.json, workshops/models.py, workshops/static/css/amy.css, workshops/templates/base_without_navbar.html, workshops/templates/workshops/dashboard.html, workshops/test/test_todos.py, workshops/views.py
The timeline is displayed on top of the dashboard.  It allows for zooming and dragging (needs to be highlighted with a click first).
This fixes #570.
=> Timeline feature

workshops/migrations/0067_person_username_regexvalidator.py, workshops/models.py, workshops/templates/workshops/person_bulk_add_results.html, workshops/test/test_person.py, workshops/test/test_util.py, workshops/util.py, workshops/views.py
This (hopefully) fixes #623 (see https://github.com/swcarpentry/amy/issues/623#issuecomment-166152983). And this fixes #526.
For details, see commit messages.
=> Bulk upload: suggest names, generate usernames

api/serializers.py, api/test/test_events.py, api/views.py
This fixes #636 by adding:
* query param for filtering events by tags
* serializer for event tags
=> API: events' tags

api/views.py
=> API: don't return TODOs without due date

workshops/forms.py, workshops/migrations/0068_auto_20160119_0629.py, workshops/migrations/0069_merge.py, workshops/models.py, workshops/templates/workshops/person.html, workshops/templates/workshops/person_diff.html, workshops/templates/workshops/person_merge_confirm.html, workshops/templates/workshops/profileupdaterequest.html, workshops/test/test_profile_update_request.py, workshops/views.py
=> Person model: add ORCID and occupation fields

workshops/migrations/0068_fix_underscores_in_usernames.py, workshops/migrations/0070_merge.py, workshops/models.py, workshops/templates/account/login.html, workshops/test/base.py, workshops/test/test_person.py, workshops/test/test_util.py, workshops/util.py
This fixes #642 the way @gvwilson wanted.
=> Underscored usernames

workshops/migrations/0070_maintainer_trainer_badge.py
Once this is merged and deployed, @gvwilson will give maintainers and trainers their awards.
=> Adding maintainer and trainer badges

workshops/forms.py, workshops/templates/workshops/event.html
=> Fix: "Survey links" -> "Survey results"

workshops/management/commands/instructors_last_call.py
Helps with managing instructor training.
=> Fetch people to be warned of instructor event closing

amy/settings.py, requirements.txt, workshops/static/jquery-ui-custom/jquery-ui.css, workshops/static/jquery-ui-custom/jquery-ui.js, workshops/templates/base_without_navbar.html, workshops/templates/workshops/dashboard.html
This fixes #676 by installing [`django-compress`](http://django-compressor.readthedocs.org/en/latest/), setting it up and enabling it to serve compressed assets all the time.
=> Assets compressor

workshops/management/commands/trainings_completion_rates.py, workshops/templates/reports/training_completion_rates.txt
Generate CSV to view in a spreadsheet (or parse with other tools for plotting).
=> Instructor completion statistics display as CSV

api/serializers.py, api/test/test_export.py, api/views.py
=> API: return award date per person per badge

workshops/filters.py, workshops/forms.py, workshops/static/calendar_popup.js, workshops/templates/base_nonav_fixed.html, workshops/templates/workshops/all_activity_over_time.html, workshops/templates/workshops/badge.html, workshops/test/test_badge.py, workshops/urls.py, workshops/views.py
This fixes #685 by turning `badge_details` view into filtered view.
Filtered views have not only the obvious ability to filter, but they can also change ordering.
=> Filtered badge view

workshops/models.py, workshops/test/base.py, workshops/test/test_event.py
This fixes #700 (nice number!).
Corrected tests were included.
=> Fix: current and ongoing events based off of published events

workshops/management/commands/check_certificates.py
The certificate generator needs a CSV file as input, and the award dates, so...
=> Exporting missing instructors as CSV

workshops/management/commands/check_certificates.py
So that we can figure out who trained them.
=> Including the event in the CSV listing

workshops/migrations/0082_add_hackathon_tags.py, workshops/test/test_commands.py
Fixes https://github.com/swcarpentry/amy/issues/617
=>  added hackathon tags

workshops/models.py
We don't want anyone to think one instructor is an option (even for <20 learners)
=> change options to require at least two instructors per wkshp

workshops/forms.py, workshops/templates/workshops/person.html, workshops/test/test_person.py, workshops/views.py
=> Autogenerate username

api/serializers.py, workshops/templates/workshops/instructor_num_taught.html
=> Fix: include people's names in instructor-num-taught report

workshops/templatetags/diff.py
=> Fix: Turn off HTML autoescape at all revision pages.

workshops/templates/workshops/event.html, workshops/views.py
Instructors frequently need to email everyone involved in a workshop; this provided a one-stop link for doing that.
=> Providing easy link to mail everyone involved in a workshop

workshops/templates/workshops/all_trainings.html
This file should be added in #775, but it got untracked accidentally.
=> Bugfix: Add missing all_trainings.html template

workshops/templates/workshops/all_activity_over_time.html, workshops/views.py
Fixes #781 
@pbanaszkiewicz @gvwilson Please review.
EDIT (@pbanaszkiewicz): fixes #796.
=> Improvements to the "All activites over time" page

amy/settings.py
On my machine, this patch speedup tests execution from 90 seconds to 50 secs.
=> Speedup 2x tests

workshops/templates/workshops/person.html, workshops/views.py
This fixes #799 
Please review. Should I make changes to the way the counts are presented or this works?
=> Show aggregate counts of roles for each Person

workshops/templates/workshops/instructor_num_taught.html
This fixes #780. (no names in the chart, though, @gvwilson)
=> Add histogram chart to frequency of instruction page

workshops/templates/workshops/workshop_staff.html, workshops/views.py
Fixes #797 
Sorry about the goof-up. I should probably use better branch names.
=> Add the ability to send bulk emails to filtered workshop staff.

workshops/templates/account/logged_out.html
=> Added link to go back and log in from the logout page

workshops/test/base.py, workshops/test/test_autoupdate_profile.py
Just to prevent situation like the one described in first point in this comment: https://github.com/swcarpentry/amy/pull/825#issuecomment-229015225
=> Add test for AutoUpdateProfile.domains

workshops/models.py, workshops/templates/navigation_fixed.html
=> Top menu: Add link to view current user's profile

workshops/forms.py
=> Make links in help texts in training request form clickable

workshops/static/css/amy.css
Fixes https://github.com/swcarpentry/amy/issues/855
=> Stop indenting lists in trainee dashboard

workshops/templates/workshops/trainingrequest.html
=> Display all fields in training request detailed view

workshops/models.py, workshops/test/test_security.py
=> Grant steering committee members access to admin interface

workshops/templates/forms/trainingrequest.html
Ref #873.
Please note that I left the three conditions that the applicant has to meet (Code of Conduct, completion of homework, discussion and demo session and teaching one SWC/DC workshops within 12 months).
=> Fix intro in training request form

workshops/forms.py, workshops/test/test_event.py
=> Allow filling the `assigned_to` field on event_add view

workshops/templates/forms/trainingrequest.html
Fall 2016 open-access training is closed, but we're taking requests for
the next one.
Preview:
=> Fix #946 by adding a message

workshops/templates/workshops/eventrequest_accept.html
=> Fix error with "Import from URL" button.

api/serializers.py
=> Use `event.slug` instead of `event.get_ident`

workshops/models.py, workshops/templates/workshops/organization.html
Add defaults to fields in `organization_detail` view.
Fixes #858
=> Add null checks for fields in Membership model.

workshops/templates/workshops/eventrequest.html
=> Link a closed workshop request to the event it created.

pydata/api.py, pydata/checks.py, pydata/forms.py, pydata/templates/pydata/bulk-import/base.html, pydata/urls.py
Fixes #963.
And a bunch of other small bug fixes.
=> Add a CSRF token even when no form exists in a formset.

workshops/forms.py, workshops/templates/workshops/event_details_table.html
=> Hide survey fields on EventCreate form and EventDetail view

.landscape.yaml, README.md
Reverts swcarpentry/amy#903
Reverting since coveralls needs access to private repos, but we don't want to grant it.
=> Revert "Add badges to README.md"

pydata/templates/pydata/bulk-import/base.html, pydata/templates/pydata/bulk-import/person.html
Add defaults to the panel header in person bulk import
Fixes #985
=> Hide instances that have been marked NOT to be imported

workshops/forms.py
=> Fix #1004 -- 500 error when matching training request to a training

workshops/templates/forms/event_submit.html, workshops/test/test_event_submissions.py, workshops/urls.py, workshops/views.py
Here's the preview:
I think we may need to change the title header as well. Your thoughts, @maneesha?
EDIT: fixes #1036.
=> Disable workshop submissions

workshops/filters.py, workshops/test/test_person.py
@pbanaszkiewicz can this be merged without a test (I did manual test)?
=> Fix #975 -- fix bug in filtering events by tag

workshops/templates/workshops/person_bulk_add_form.html, workshops/views.py
=> Add instructions in bulk add person.

workshops/forms.py, workshops/models.py, workshops/templates/navigation_fixed.html, workshops/templates/workshops/search.html, workshops/test/test_search.py, workshops/views.py
This fixes #968 by extending current search capabilities to training applications.
=> Search in training applications

workshops/test/test_util.py, workshops/util.py
=> Allow AMY to import an event using the GH repo URL.

workshops/filters.py, workshops/models.py, workshops/templates/workshops/all_trainees.html, workshops/templates/workshops/trainee_dashboard.html, workshops/test/test_person.py, workshops/test/test_trainee_dashboard.py, workshops/util.py, workshops/views.py
=> Fix #980 -- filter trainees by "ready to be badged" status

workshops/filters.py, workshops/templates/workshops/all_trainingrequests.html
Display "group" column in the table when user filters by group name.
Fixes #1050.
=> Fix #1050 -- add filter by group name in training applications list view

workshops/templates/workshops/all_organizations.html, workshops/views.py
=> Fix #1035 -- display current partnership level in organization display

workshops/filters.py
=> Fix #1032 -- enable filtering by multiple partnership levels on organizations

workshops/templates/workshops/event.html, workshops/templates/workshops/event_details_table.html, workshops/templates/workshops/event_invoice.html, workshops/views.py
This PR fixes #1040 by disabling invoice requests. The invoice view, as well as "Invoice" button on event details page, shows new instructions on how to request an invoice.
=> Disable invoices

pydata/api.py
Prevents IntegrityError while trying to save an organization
with conflicting fullname but different domains.
Fixes #964
=> Rewrite the query to fetch an organization.

api/filters.py, api/views.py, workshops/filters.py, workshops/templates/workshops/time_series.html, workshops/views.py
=> Querying historical data with parameters

api/test/test_export.py, extforms/views.py, pydata/views.py, workshops/base_views.py, workshops/forms.py, workshops/github_auth.py, workshops/models.py, workshops/templates/workshops/all_profileupdaterequests.html, workshops/templates/workshops/all_trainings.html, workshops/templates/workshops/organization.html, workshops/templates/workshops/person.html, workshops/urls.py, workshops/util.py, workshops/views.py
- Bug fix in `all_trainings`: The number of trainees who became SWC or DC instructor was overestimated due to a bug in a query.
- Switching to class-based views in case of simple `ListView`s and some simple `DetailView`s.
- Adopting new name convention (`AMYWhateverView`) for our generic views.
- Moving generic views from `views.py` to `base_views.py`.
@pbanaszkiewicz what do you think about these changes?
=> Views refactoring + one bug fix

api/views.py, workshops/forms.py, workshops/templates/workshops/all_activity_over_time.html, workshops/views.py
=> Fix #782 -- use hyperlinks in report on all activity

docs/releases/v1.9.0.md
I propose to keep release notes in the source code, so they won't get lost.
=> Add release notes for v1.9.0

workshops/views.py
=> Fix #1096 -- correct title of badge detail page

workshops/models.py
Fixes #1103
@maneesha The new forms looks like:
=> Reorder fields on workshop request form

workshops/base_views.py, workshops/templates/workshops/badge.html, workshops/templates/workshops/event_edit_form.html, workshops/templates/workshops/person_edit_form.html, workshops/test/test_badge.py, workshops/test/test_todos.py, workshops/views.py
=> Trim AMYDeleteView of any redirection support

workshops/forms.py, workshops/templates/workshops/persons_merge.html, workshops/test/test_person.py, workshops/views.py
This fixes #1117 by extending merging persons mechanism with `trainingprogress_set` items.
Tests were adjusted.
=> Merging trainees

workshops/models.py, workshops/test/test_event.py
Changes include: removing cancelled events from uninvoiced, unpublished
and published events; adding a separate `.not_cancelled()` filter;
finally removing the cancelled condition from `unpublished_conditional`.
Tests were fixed accordingly.
This fixes #1064
This fixes #1110
This fixes #1128
=> EventQuerySet: change the way cancelled events are filtered

workshops/forms.py, workshops/models.py
=> Make select widget filtering events by tags bigger

api/views.py, workshops/test/test_profile_update_request.py, workshops/views.py
=> Fix #1109 -- make airport code insensitive in profile update requests

bower.json, workshops/templates/base_nonav_fixed.html, workshops/templates/workshops/admin_dashboard.html
Fixes #1135.
Is the `vis` library used anywhere in AMY?
=> Remove timeline from admin dashboard

workshops/filters.py
=> Fix #1151 -- allow filtering workshops by country

workshops/templates/workshops/validate_event.html, workshops/test/test_util.py, workshops/util.py, workshops/views.py
=> Fix #1053 -- add warnings in addition to errors in event validation

workshops/static/css/amy.css, workshops/templates/base_nav_fixed.html, workshops/templates/base_nonav_fixed.html, workshops/templates/forms/event_submit.html, workshops/templates/forms/profileupdate.html, workshops/templates/forms/profileupdate_confirm.html, workshops/templates/forms/trainingrequest.html, workshops/templates/forms/trainingrequest_confirm.html, workshops/templates/forms/workshop_swc_request.html
but only if the logged user is an admin.
Fixes #856.
=> Fix #856 -- add navigation bar to external forms

extforms/test/test_training_request_form.py, extforms/views.py, workshops/forms.py, workshops/test/test_training_request.py
=> Fix #1005 -- allow prepopulation of group name in training request form

docs/deployment.md
=> Fix #955 -- add description of deployment procedure

workshops/static/update_from_url.js
=> Fix #1176: Working  functionality.

pydata/views.py, workshops/migrations/0054_self_organized_host.py, workshops/test/test_search.py, workshops/views.py
=> Fix #1044 -- replace contains with icontains

workshops/templates/navigation_fixed.html
=> Fix #1166 -- prevent navbar from wrapping and covering content

workshops/templates/workshops/event_import_update_from_url.html, workshops/templates/workshops/eventrequest_accept.html
=> Fix #1169 -- correct misleading help text in "import from URL" modal

workshops/templates/workshops/last_modified.html, workshops/test/test_diff.py, workshops/urls.py, workshops/views.py
=> Fix #1083 -- fix revision pages

amy/settings.py
per Aleksandra Nenadic request
=> Raise API throttle rate for logged in users

docs/design/database_models.md, docs/design/index.md, docs/design/server_infrastructure.md
Hello all,
this PR covers basics of server-side of AMY deployment; documentation on AMY internal design has also been started.
I'd like to hear any feedback on the server-side. Thanks.
=> Documentation - design notes

amy/urls.py, workshops/test/test_security.py
This fixes #1197 and supersedes #1221.
=> Redirect `/` to `/workshops`

workshops/management/commands/fake_database.py
=> fix for TrainingRequest in Fake Database

workshops/migrations/0134_mentor_mentee_badges.py
Based on #1229 @pbanaszkiewicz suggested creating a migration for making new mentorship badges. 
Please review closely. First time making a migration, don't want to break anything 😬.
=> Adding badges to track mentorship participation

workshops/filters.py, workshops/forms.py, workshops/static/css/amy.css
This fixes #1264, and adds some other slight visual changes to the sidebar on that page. See commit messages for more.
=> Select2 widget widths on Find Workshop Staff page

workshops/templates/workshops/trainee_dashboard.html, workshops/views.py
This commit changes "workshops you taught at" to "your workshop
activity", that displays all workshops specific instructor was engaged
in.
=> Fix #1263: display all workshop activity for instructors

workshops/forms.py, workshops/static/css/amy.css, workshops/templates/workshops/training_progresses_inline.html, workshops/test/test_trainees.py, workshops/test/test_training_progress.py
This fixes #1285 by:
1) adding a validation level to TrainingProgressForm
2) conditioning "+" button used to add progress to trainees
3) adding a validation level to another form, BulkAddTrainingProgressForm
Tests were changed accordingly.
=> Require training task for person to assign a training progress to them

workshops/test/test_training_request.py, workshops/views.py
This fixes #1270 by altering the way
`views._match_training_request_to_person` saves details from training
request into matched person profile.
The data merged now is:
* personal, middle, family
* email, github, country
* affiliation, occupation
* knowledge domains
* data privacy agreement
* is_active and may_contact = True (these values come from the fact that
someone submitted the form)
* training request (admin) notes are merged with person notes
=> Save training request data into person profile upon matching

Makefile
This fixes #1317.
A new command was introduced, some commands were fixed. See commit messages for more details.
=> Remove Bower residues

workshops/filters.py, workshops/templates/workshops/all_eventrequests.html, workshops/templates/workshops/all_eventsubmissions.html, workshops/views.py
This PR fixes #1315:
* pagination was added to workshop requests list page,
* filter fields, that contained additional empty label ('----------'), were fixed,
* styling and ordering of some filter fields was improved.
=> Workshop requests: pagination and filters

api/serializers.py, api/views.py, workshops/forms.py, workshops/templates/workshops/instructors_by_date.html, workshops/test/test_instructors_by_date.py, workshops/views.py
This fixes #1320.
See commit messages for the list of changes.
=> Fix instructors by date report

workshops/templates/navigation.html
=> Sticky navigation bar

api/serializers.py
=> Extend PersonSerializer with ORCID data

amy/settings.py
I got the below error in the latest Google Chrome when trying to run AMY. The fix in this PR made it all work ok!
=> Add localhost host to debug mode

workshops/forms.py, workshops/views.py
This field is crucial for working with new instructor training
memberships.
This fixes #1356.
=> BulkMatchTrainingRequestForm: "open seat" field

api/serializers.py, api/views.py, workshops/templates/workshops/event.html, workshops/views.py
More details about the bug in comments.
This fixes #1377.
=> Instructor badges display bug

workshops/templates/workshops/organization.html
=> Add instructor training seat details to Organization details page

workshops/models.py
Added description of Library Carpentry workshops to the new Request a Carpentries Workshop page.
=> adding LC description to Request a Workshop page

amy/extrequests/views.py, amy/workshops/views.py
=> Warning for trainings falling out of agreement dates

amy/templates/forms/trainingrequest_confirm.html, amy/templates/forms/workshoprequest_confirm.html
=> Add library carpentry links to confirmation pages

amy/static/css/amy.css, amy/workshops/forms.py, amy/workshops/views.py
=> Permissions box resizable

amy/api/serializers.py, amy/api/tests/test_reports.py, amy/api/views.py, amy/templates/reports/instructor_num_taught.html
This fixes #1416. More in commit messages.
=> Instructor num taught split by tag

amy/api/filters.py, amy/api/views.py, amy/templates/workshops/workshop_staff.html, amy/workshops/filters.py, amy/workshops/forms.py, amy/workshops/tests/base.py, amy/workshops/tests/test_workshop_staff_searching.py, amy/workshops/urls.py, amy/workshops/views.py
This fixes #997 by:
* adding CSV output for Workshop Staff searching
* adding required filters to Workshops over time, Learners over time and Instructors over time reports.
The reports have CSV output already (one has to follow "API link" on the report's page), so @anenadic if this does not fulfil your requirement, please add a separate issue.
=> Workshop staff CSV, report filters

amy/extrequests/tests/test_workshop_requests.py, amy/templates/requests/all_workshoprequests.html
This fixes #1435. A regression test was added.
=> Workshop request list: comment column with missing comments

amy/templates/forms/trainingrequest.html
=> updated email addresses

Makefile
I think this was submitted before - but it is  currently not right when creating the test setup.
=> fix location of git_version.py

amy/fiscal/views.py, amy/templates/fiscal/membership.html
=> Membership details: Display badges for each instructor training seat

amy/static/amy_utils.js, amy/static/css/amy.css, amy/templates/base.html, amy/trainings/filters.py, config/settings.py, requirements.txt
This fixes #1482 #1485. Most of the issues were affected by wrong Django Compressor configuration, or some other micro bugs in code. See more in commit messages.
=> Fix Django Compressor issues

amy/api/views.py, amy/templates/reports/all_activity_over_time.html
=> LC stats in All Activity Over Time

amy/workshops/management/commands/fake_database.py
Some minor changes, but the biggest:
1. add fake workshop requests
2. create properly current events
=> Upgrade fake database script

amy/extrequests/views.py
=> Prefill Workshop Request Accept & Create Event form is URL provided

amy/extforms/tests/test_training_request_form.py, amy/extforms/tests/test_workshop_request_form.py, amy/extforms/views.py, amy/templates/mailing/training_request.html, amy/templates/mailing/training_request.txt, amy/templates/mailing/workshoprequest.html, amy/templates/mailing/workshoprequest.txt, amy/templates/mailing/workshoprequest_admin.html, amy/templates/mailing/workshoprequest_admin.txt, amy/workshops/base_views.py
This fixes #1490.
The workshop request form gained a new feature: autoresponder. It emails the person submitting the form, and it's the same mechanics as in training request form.
=> Workshop request autoresponder

amy/extrequests/tests/test_training_request.py, amy/workshops/models.py
This fixes #1505. Tests were adjust.
=> Add Chemistry to auto scored domains for Instructor Training Requests

amy/templates/dashboard/trainee_dashboard.html
=> Add lesson publication consent to Trainee Dashboard

amy/workshops/forms.py
This fixes #1537 by providing parameters for the widget.
=> Widen admin-selection widget

amy/extrequests/migrations/0006_migrate_workshop_requests_to_selforg_submissions.py
Some fields weren't used in that data migration. This fixes #1541 by
adding them to the migration.
=> Add missing fields to WorkshopRequest->SelfOrganisedSubmission migration

README.md
=> Readme instructions to createcachetable 

amy/templates/dashboard/autoupdate_profile.html, amy/templates/dashboard/trainee_dashboard.html
=> Adds text to note email & GH id can't be edited by user

amy/templates/dashboard/trainee_dashboard.html
=> Update self-org verbiage on trainee dashboard

amy/autoemails/actions.py, amy/autoemails/tests/test_postworkshopaction.py, amy/workshops/tests/test_util.py, amy/workshops/util.py, config/settings.py
This PR adds a survey result link (`reports_link`) to `PostWorkshopAction` context.
=> PostWorkshopAction: link to survey results

amy/extrequests/tests/test_selforganised_submissions.py, amy/fiscal/forms.py, amy/static/edit_from_url.js, amy/templates/includes/event_details_table.html, amy/templates/includes/workshoprequest_details.html, amy/workshops/forms.py, amy/workshops/templatetags/utils.py, amy/workshops/tests/test_commands.py, amy/workshops/tests/test_util.py, amy/workshops/util.py, amy/workshops/views.py
This PR fixes #1568 by supporting multiple values in Event contact field.
For more details please see commit messages.
=> Contact meta tag - split by |

amy/autoemails/admin.py, amy/autoemails/forms.py, amy/autoemails/templates/rqjob_preview.html, amy/autoemails/tests/test_admin_cancel.py, amy/autoemails/tests/test_admin_edit_template.py, amy/autoemails/tests/test_admin_reschedule.py, amy/autoemails/tests/test_admin_retry.py, amy/autoemails/tests/test_admin_sendnow.py, amy/static/css/rqjob_admin.css
This PR provides new form for editing a scheduled template, and also some styling cleanups for the preview page (where the form is located).
=> RQJob template editing

amy/templates/mailing/selforganisedsubmission.html, amy/templates/mailing/selforganisedsubmission.txt, amy/templates/mailing/workshopinquiry.html, amy/templates/mailing/workshopinquiry.txt, amy/templates/mailing/workshoprequest.html, amy/templates/mailing/workshoprequest.txt
once @sheraaronhurt and @Talishask have reviewed the language, @pbanaszkiewicz please review and merge.
=> add links to online workshop resources to WRF automated emails

.flake8, .gitignore, amy/autoemails/actions.py, amy/autoemails/forms.py, amy/autoemails/mixins.py, amy/autoemails/models.py, amy/autoemails/tests/test_action.py, amy/autoemails/utils.py, amy/extrequests/models.py, amy/workshops/forms.py, amy/workshops/mixins.py, amy/workshops/models.py, amy/workshops/tests/test_badge.py, amy/workshops/tests/test_event.py, amy/workshops/tests/test_person.py, amy/workshops/util.py, amy/workshops/views.py
1. Linting enabled: assuming your code editor supports it,
we have flake8 configuration. Also mypy should work.
2. Black should be used to format files (these scripts were
formatted with it).
=> Improve syntax of some files, add linting options

amy/autoemails/tests/test_instructorshostintroductionaction.py
This test was accidentally removed during #1684 work.
=> Restore context test for Introduction email

amy/fiscal/tests/test_membership.py, amy/templates/fiscal/membership.html, amy/templates/fiscal/organization.html, amy/workshops/models.py
This fixes #1664 by incorporating changes requested by @maneesha.
=> Membership workshops summary fixes

docs/amy_database_structure.md
=> fix bulleted formatting

requirements.txt
=> Update Pillow to 7.1.0

amy/templates/mailing/training_request.txt
Please delete this line and the text below before submitting your contribution.
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The …
=> fix typo from ubmission to Submission

amy/templates/includes/event_details_table.html, amy/workshops/forms.py
Fixes #1736 by moving the workshop public field on the event view and event edit pages
=> moves workshop public question to more prominent place on page

package.json, yarn.lock
supersedes https://github.com/carpentries/amy/pull/1733
fixes #1723 
@pbanaszkiewicz  : you are correct, updating to Bootstrap 4.5.3 (and fixing the unmet peer dependency) makes the accordion work again.
=> Update to Boostrap 4.5

amy/static/amy_utils.js
=> Automatically check "TTT Open applications" when TTT tag is selected

amy/autoemails/actions.py, amy/autoemails/tests/test_askforwebsiteaction.py
Applied both for condition check and for recipients of the email.
=> Extend AskForWebsite with supporting instructor role

amy/api/views.py, amy/dashboard/forms.py, amy/dashboard/views.py, amy/reports/views.py, amy/static/amy_utils.js, amy/templates/dashboard/admin_dashboard.html, amy/templates/includes/assignment.html, amy/workshops/fields.py, amy/workshops/forms.py, amy/workshops/models.py, amy/workshops/tests/test_util.py, amy/workshops/util.py, amy/workshops/views.py
This fixes #1752.
Introduced new assignment form - which allows viewing events filtered down to a particular person (with administrative rights).
=> Assignment enhancement

amy/dashboard/forms.py, amy/dashboard/tests/test_assignment_form.py
=> [#1792] assigned to: Distinct list of users

amy/fiscal/forms.py, amy/fiscal/views.py, amy/workshops/lookups.py
1. Members formset contained wrong title
2. Person Task formset contained wrong lookup.
Edit: this fixes #1796.
=> [#1796] Fix small mixups on Memberhips formsets

amy/fiscal/views.py, amy/templates/fiscal/all_organizations.html, amy/templates/fiscal/organization.html
Relationship to memberships changed.
This fixes #1797.
=> [#1797] Fix small issues with organisations

amy/workshops/models.py
Revised text on to match what is mentioned in https://github.com/carpentries/amy/issues/1787
=> feature: Add language to instructor training application about sharing data

amy/workshops/filters.py, amy/workshops/forms.py, amy/workshops/lookups.py, amy/workshops/tests/base.py, amy/workshops/tests/test_workshop_staff_searching.py
=> feature: Filter workshop staff by knowledge domain.

amy/extrequests/base_views.py, amy/extrequests/tests/test_wrfinitial.py
Fixes https://github.com/carpentries/amy/issues/1758.
=> bugfix: Removed initial slug value from WRFInitial.

amy/fiscal/tests/test_membership.py, amy/templates/fiscal/membership.html, amy/templates/fiscal/organization.html, amy/workshops/models.py
1. Improved calculations
2. Tests to cover the calculations
3. UI changes
=> [#1781] Discounted workshops

amy/consents/forms.py, amy/consents/models.py, amy/consents/tests/test_forms.py, amy/consents/tests/test_models.py, amy/consents/tests/test_views.py, amy/consents/urls.py, amy/consents/views.py, amy/templates/workshops/person_edit_form.html, amy/workshops/views.py
Fixes https://github.com/carpentries/amy/issues/1830.
Dependent upon: https://github.com/carpentries/amy/pull/1832
=> feature(Consents): Users should see what they have consented to.

.github/workflows/codeql-analysis.yml, .github/workflows/python-test.yml, config/settings.py
=> GH action to run tests

amy/templates/dashboard/training_progress.html
Makes some changes to the trainee progress view (https://amy.carpentries.org/dashboard/trainee/training_progress/).
=> assorted changes to trainee progress view

amy/consents/admin.py, amy/consents/forms.py, amy/consents/tests/test_views.py
Fixes https://github.com/carpentries/amy/issues/1827
=> feature(Consents): Display change history for consents.

amy/consents/admin.py, amy/consents/models.py, amy/consents/tests/test_models.py, amy/templates/consents/admin_change_form_term.html, amy/workshops/management/commands/fake_database.py
Fixes https://github.com/carpentries/amy/issues/1882
Dependent on https://github.com/carpentries/amy/pull/1880
=> feature(Consents): Archive terms and term options from Django Admin view

amy/consents/admin.py
Just realized I left a breakpoint in admin consents from https://github.com/carpentries/amy/pull/1885
=> fix(Consents): Removed breakpoint from consent admin

docs/amy_database_structure.md
Fixes https://github.com/carpentries/amy/issues/1844
=> feat(Consents): Added documentation notes about the database tables.

amy/templates/dashboard/trainee_dashboard.html, amy/templates/navigation.html, amy/templates/workshops/person.html, amy/workshops/base_views.py, amy/workshops/models.py, amy/workshops/tests/test_person.py, amy/workshops/urls.py, amy/workshops/views.py
Fixes https://github.com/carpentries/amy/issues/1887
Fixes https://github.com/carpentries/amy/issues/1884
Fixes https://github.com/carpentries/amy/issues/1886
=> feat(Profile Archival): Archive person profile.

amy/consents/admin.py, amy/consents/models.py, amy/consents/tests/test_models.py, amy/templates/consents/admin_change_form_term.html
Fixes https://github.com/carpentries/amy/issues/1909
=> fix(Consents): Fixed issue with admin term and term option add being broken.

amy/consents/forms.py
Fixes https://github.com/carpentries/amy/issues/1926
=> feat(Consents): Added border around options fields that are unset.

.github/workflows/linter.yml
Enable GitHub action for linting Python files with Black, Flake8 and isort.
=> [#1875] Add linter GitHub action

amy/api/filters.py, amy/api/tests/test_filter.py, amy/consents/models.py
Partial fix for https://github.com/carpentries/amy/issues/1963
=> fix(Consent): Remove old style consents from filter

.github/workflows/linter.yml
=> [#1976] Linters configuration paths (GitHub CI)

amy/api/serializers.py, amy/api/tests/test_api_structure.py, amy/api/tests/test_export.py
Fixes https://github.com/carpentries/amy/issues/1974
=> fix(Consents) Changed the person data view and serializers to only show the active consents

amy/consents/forms.py, amy/consents/tests/test_action_required_view.py, amy/dashboard/forms.py, amy/dashboard/tests/test_autoupdate_profile.py, amy/dashboard/views.py, amy/templates/dashboard/autoupdate_profile.html
The user edit page was updating the older version of consents.
Fixes https://github.com/carpentries/amy/issues/1991
=> fix(Consents): Trainee dashboard user edit page updates consents correctly.

amy/fiscal/forms.py, amy/static/member_form.js
Show confirmation modal upon click on "DELETE" checkbox in Member
formset.
Preview:
=> [#1928] Confirm member removal

amy/dashboard/tests/test_search.py, amy/dashboard/views.py
Fix the bug: improper redirect to a single result if from many group
results only one group is exactly 1 element long.
This fixes #2014.
=> [#2014] Fix: redirect if only 1 group of results is singular

amy/api/tests/test_api_structure.py, amy/api/tests/test_filter.py, amy/dashboard/views.py, amy/templates/workshops/persons_merge.html, amy/workshops/forms.py, amy/workshops/tests/base.py, amy/workshops/tests/test_person.py, amy/workshops/tests/test_util.py, amy/workshops/util.py, amy/workshops/views.py
Fixes https://github.com/carpentries/amy/issues/1881
=> feat(Consents): Updated Merge person to handle new consents.

amy/autoemails/actions.py, amy/autoemails/fixtures/templates_triggers.json, amy/autoemails/models.py, amy/autoemails/tests/test_newconsentrequiredaction.py
Fixes https://github.com/carpentries/amy/issues/2030
=> Fix(Consents): Fix email reply to.

amy/extrequests/tests/test_training_request.py
=> Some tests misusing assertTrue for comparisons fix

docs/users_guide/index.md
Adds info about automated emails to documentation
=> Auto emails docs

amy/templates/requests/all_selforganisedsubmissions.html, amy/templates/requests/all_workshopinquiries.html, amy/templates/requests/all_workshoprequests.html
Fixes #1989  by adding a "Submission Date" column to the views for workshop inquiries, requests, and self-org submissions.
=> add submission date column to all WRF views

amy/templates/includes/instructorrecruitment.html
=> [#2156] Fix column name (Notes from RC->Notes from admin)

amy/templates/includes/instructorrecruitment.html
=> [#2157] Fix: remove interest column from instructor recruitment list

Pipfile.lock, amy/recruitment/forms.py, amy/recruitment/tests/test_forms.py, amy/recruitment/tests/test_instructor_recruitment_views.py, amy/recruitment/urls.py, amy/recruitment/views.py, amy/templates/includes/instructorrecruitment.html, amy/templates/recruitment/instructorrecruitment_add_signup.html, amy/workshops/lookups.py
~~WIP.~~
This fixes #2082.
TODO:
=> [#2082] Admin signs up Instructor on their behalf

amy/fiscal/forms.py, amy/fiscal/views.py, amy/static/amy_utils.js, amy/static/calendar_popup.js
=> make new membership start day after previous ends

amy/autoemails/tests/test_askforwebsiteaction.py, amy/autoemails/tests/test_instructorshostintroductionaction.py, amy/autoemails/tests/test_newinstructoraction.py, amy/autoemails/tests/test_newsupportinginstructoraction.py, amy/autoemails/tests/test_postworkshopaction.py, amy/autoemails/tests/test_recruithelpersaction.py, amy/autoemails/tests/test_selforganisedrequestaction.py, amy/dashboard/tests/test_instructor_recruitment_views.py, amy/dashboard/views.py, amy/recruitment/tests/test_instructor_recruitment_views.py, amy/recruitment/views.py, amy/templates/includes/instructor_selection_summary.html, amy/templates/recruitment/instructorrecruitment_add.html, amy/workshops/models.py, amy/workshops/tests/test_event.py, amy/workshops/views.py
Fixes #2153.
Fixes #2154.
TODO:
=> [#2153][#2154] Recruitment event requirements (date in future + location data)

amy/workshops/fixtures/badges.json, amy/workshops/management/commands/migrate_to_single_instructor_badge.py, amy/workshops/tests/test_commands.py
This fixes #1162 by creating a new (single) Instructor badge.
This fixes #2166 by creating a script to add Instructor badge to all instructors.
=> [#1162][#2166] New single Instructor badge

amy/templates/trainings/all_trainees.html, amy/trainings/filters.py, amy/trainings/tests/test_trainees.py, amy/trainings/views.py, amy/workshops/models.py
=> [#2169] Use Single Instructor Badge in Trainees view

amy/recruitment/tests/test_instructor_recruitment_views.py, amy/recruitment/views.py
=> [#2202] Fix "Decline" Instructor Application error

amy/templates/dashboard/training_progress.html
=> [#2175] Update verbiage on "Training Progress" contribution form

Makefile, amy/api/tests/test_export.py, amy/dashboard/forms.py, amy/dashboard/tests/test_instructor_dashboard.py, amy/dashboard/views.py, amy/static/amy_utils.js, amy/templates/dashboard/training_progress.html, amy/trainings/fixtures/training_requirements.json, amy/trainings/forms.py, amy/trainings/tests/test_trainees.py, amy/trainings/tests/test_training_progress.py, amy/workshops/models.py, amy/workshops/tests/test_person.py
=> [#2171] instructor checkout steps single badge

amy/dashboard/filters.py, amy/dashboard/tests/test_filters.py, amy/recruitment/filters.py, amy/recruitment/tests/test_filters.py
This fixes #2195.
This fixes #2199.
=> [#2195][#2199] Additional filters in instructor selection

amy/recruitment/forms.py, amy/recruitment/tests/test_forms.py, amy/recruitment/tests/test_instructor_recruitment_views.py, amy/recruitment/views.py, amy/templates/includes/instructorrecruitment.html
=> [#2203] Reopen closed recruitment

amy/workshops/forms.py, amy/workshops/tests/test_forms.py
=> [#2025] Block creating Task if instructor/trainer community role is inactive

amy/trainings/forms.py
=> [#2215] Fix: hide unused requirement types from New training progress form

amy/communityroles/forms.py, amy/communityroles/tests/test_community_role_forms.py, amy/communityroles/tests/test_community_role_views.py, pyproject.toml
=> [#2225] Disallow concurent community roles of the same type for the same person

amy/communityroles/forms.py, amy/communityroles/tests/test_autocreating_community_roles.py, amy/communityroles/tests/test_community_role_forms.py, amy/workshops/views.py
=> [#2221] Autoassign Community Role when award is created

amy/recruitment/forms.py, amy/recruitment/models.py, amy/recruitment/tests/test_forms.py, amy/recruitment/tests/test_instructor_recruitment_views.py, amy/recruitment/urls.py, amy/recruitment/views.py, amy/static/css/amy.css, amy/templates/includes/instructorrecruitment.html
=> [#2237] Edit admin notes for instructor selection

amy/templates/communityroles/communityrole.html, amy/templates/workshops/person.html, amy/templates/workshops/person_edit_form.html, amy/workshops/base_views.py, amy/workshops/views.py
=> [#2243] Award details and award-delete issues

amy/dashboard/views.py
=> [#2244] Sort instructor's workshop activity by event start date

docs/design/database_models.md
=> [#2267] Documentation: update database models

docs/design/template_hierarchy.md, mkdocs.yml
=> Documentation: update templates documentation

docs/design/server_infrastructure.md
=> Documentation: update infrastructure

README.md, docs/procedures.md
=> Documentation: update procedures

docs/design/index.md, docs/design/views_hierarchy.md, mkdocs.yml
=> Documentation: add documentation on base views

amy/autoemails/templates/rqjob_preview.html
=> Fix re-try button (switch from GET to POST)

amy/autoemails/admin.py, amy/autoemails/templates/rqjob_preview.html
This fixes #2303.
Additionally, usability of admin panel listing RQJobs was improved by removing some empty or unused columns, and adding filtering and search bar.
=> Fix Re-try button in Admin panel for RQJobs

Makefile, amy/workshops/github_auth.py, amy/workshops/middleware/github_auth.py, amy/workshops/middleware/version_check.py, config/settings.py, docker/Dockerfile, start.sh
This fixes #2283 on AMY side.
The rest of changes remains in a different repository.
=> AWS CDK preparation

.github/workflows/cicd.yml
Contains "build" job for Docker build and push.
=> [partial #2284] Change python-test to cicd workflow

.github/workflows/cicd.yml
Changes to "on merge" condition.
=> [#2284] Correct `build` step condition event

.github/workflows/cicd.yml
=> [#2284] Remove condition from develop branch

.github/workflows/cicd_develop.yml
Additionally testing conditions of `build` step in the pipeline.
=> [#2284] Add environment for building Docker

.github/workflows/test.yml, config/settings.py
=> Deploy to test-amy2

amy/templates/dashboard/upcoming_teaching_opportunities.html
=> Update text for conflicting workshops at instructor sign-up

amy/fiscal/filters.py
=> dev: Fix server error on organizations membership

docs/design/cicd.md, docs/design/database_backups.md, docs/design/server_infrastructure.md, mkdocs.yml
This fixes #2364.
This fixes #2365.
=> Updated docs for server infrastructure and backups

CHANGELOG.md, docs/amy_database_structure.md, docs/design/database_models.md, docs/design/projects/2021_consents.md, docs/releases/README.md, docs/users_guide/admin_index.md
Updates the documentation based on our recent changes for the consents project.
Will mark as WIP while we get the final issues finished.
=> Update docs for consents

.github/workflows/linter.yml, .pre-commit-config.yaml, amy/consents/admin.py, amy/workshops/base_views.py, amy/workshops/fields.py, amy/workshops/models.py, amy/workshops/tests/test_event.py, amy/workshops/tests/test_security.py, amy/workshops/tests/test_tasks.py, amy/workshops/utils/dates.py, amy/workshops/utils/usernames.py
Fixes #2383.
Would not reformat anything in #2402.
=> Bump black to 23.3.0

amy/emails/actions.py, amy/emails/templatetags/emails.py, amy/emails/tests/actions/test_feature_flag.py, amy/emails/tests/actions/test_persons_merged.py, amy/emails/tests/test_template_tags.py, amy/emails/tests/test_views.py, amy/emails/views.py, amy/templates/navigation.html, config/settings.py
This fixes #2441.
This is based on #2433 and will be shorter once it's merged.
~~WIP. Todo: addditional tests.~~ Done
=> Email module feature flag

docs/manual_deployment_steps.md, docs/procedures.md, mkdocs.yml
I tried to capture all the extra undocumented steps we took.
I've also created a new file where we can add manual deployment steps that should be completed for a particular release.
=> Update release procedure documentation

amy/static/css/amy.css
=> Override link colours in banner to improve contrast

README.md, docs/accessibility_testing.md
Docs updates not tied to member codes; can be merged before v4.3 release is ready.
WIP while I wrap things up.
=> Miscellaneous docs updates

amy/dashboard/forms.py
Addresses but does not close #2436.
=> Make explicit where Instructors can include accommodations they need when signing up for workshop

amy/templates/forms/trainingrequest.html, amy/templates/mailing/training_request.html, amy/templates/mailing/training_request.txt
Begins to address #2617 (first two bullets)
=> Remove references to open training

amy/locale/en/formats.py, config/settings.py
This is working only in english locale, which is default for this project.
This fixes #2628.
=> Update datetime and time formats to include a timezone

amy/emails/forms.py, amy/emails/tests/test_forms.py, amy/emails/tests/test_views.py
=> [Emails] Validate rescheduled date/time to not be in past

amy/emails/actions/admin_signs_instructor_up_for_workshop.py, amy/emails/actions/instructor_confirmed_for_workshop.py, amy/emails/actions/instructor_declined_from_workshop.py, amy/emails/actions/instructor_signs_up_for_workshop.py, amy/emails/actions/instructor_training_completed_not_badged.py, amy/emails/tests/actions/test_admin_signs_instructor_up_for_workshop.py, amy/emails/tests/actions/test_instructor_confirmed_for_workshop.py, amy/emails/tests/actions/test_instructor_declined_from_workshop.py, amy/emails/tests/actions/test_instructor_signs_up_for_workshop.py
=> [Emails] Correct URLs in context for scheduled emails

amy/emails/actions/new_self_organised_workshop.py, amy/emails/tests/actions/test_new_self_organised_workshop.py, amy/emails/types.py, amy/scripts/seed_emails.py, amy/templates/emails/email_template_list.html
This extends the context variables for New Self-Organised Workshop.
=> [Emails] Add missing context variables

amy/emails/controller.py
This fixes template rendering issue when updating email.
=> [Emails] Fix template render issue with email update actions

docs/design/application_design.md, docs/design/database_models.md, docs/design/projects/2019_automated_emails.md, docs/design/projects/2023_automated_emails.md, docs/design/projects/README.md, docs/design/server_infrastructure.md
=> [Emails] Updated technical documentation

amy/api/v2/serializers.py, amy/api/v2/views.py, amy/emails/controller.py, amy/emails/views.py, amy/templates/emails/scheduled_email_detail.html, amy/workshops/models.py
=> [Emails] Extend REST API for events, scheduled emails, and fix too many logs

amy/emails/filters.py, amy/emails/views.py, amy/templates/emails/email_template_list.html, amy/templates/emails/scheduled_email_list.html, amy/templates/includes/related_scheduled_emails.html, amy/templates/includes/related_scheduled_emails_no_empty_msg.html
=> [Emails] UI improvements for emails

amy/templates/includes/related_scheduled_emails.html, amy/templates/includes/related_scheduled_emails_no_empty_msg.html
=> [Emails] Add missing email state

amy/emails/controller.py, amy/emails/tests/test_controller.py, config/settings.py
This fixes #2678 by providing a logic mechanism cancelling emails that were failed 10 times in a row.
=> [Emails] Failed emails circuit breaker

amy/templates/includes/tracker.html
This PR updates the existing cloud based matomo tracking code to our new self-hosted version.
=> Update matomo tracking code

amy/emails/tests/test_utils.py, amy/emails/tests/test_views.py, amy/emails/utils.py, amy/emails/views.py, amy/templates/emails/scheduled_email_detail.html, docker/docker-compose.yml, pyproject.toml
=> [Emails] Preview rendered jinja2+markdown email templates

amy/api/v2/serializers.py, amy/templates/includes/event_details_table.html, amy/workshops/forms.py, amy/workshops/models.py, amy/workshops/tests/test_event.py
=> Automatically generate and update survey link

docs/manual_deployment_steps.md
Add info about migration script and its prerequisites.
=> chore: Update manual deployment steps

amy/templates/includes/event_details_table.html, amy/templates/workshops/task.html
=> [Emails] Remove RQ Jobs listings from event and task detail pages

amy/emails/models.py, amy/emails/tests/test_template_tags.py, amy/emails/tests/test_views.py, amy/templates/emails/scheduled_email_detail.html
=> [Emails] Allow editing cancelled emails

amy/emails/actions/instructor_confirmed_for_workshop.py, amy/emails/tests/actions/test_instructor_confirmed_for_workshop_strategy.py
=> [Emails] Add condition for event in future in Instructor Confirmed for Workshop

amy/dashboard/views.py
=> Leverage full-text search in Postgres to improve searching for people and training requests

amy/dashboard/views.py, amy/templates/dashboard/instructor_dashboard.html
=> Display tasks per role summary in instructor dashboard

amy/dashboard/tests/test_instructor_recruitment_views.py, amy/dashboard/views.py, amy/templates/dashboard/instructor_dashboard.html, amy/templates/navigation.html, amy/templates/navigation_instructor_dashboard.html
=> Allow admins to see upcoming teaching opportunities

.github/workflows/cicd_develop.yml
Fix the issue with deploying ECS from `develop` branch.
=> Update CICD workflow

amy/api/v2/serializers.py
The new field will return `get_state_display` value for the model instances.
=> API: Add `state_verbose` API r/o field to models that have state` field

amy/templates/dashboard/instructor_dashboard.html, amy/templates/workshops/person.html, amy/templates/workshops/persons_merge.html, docs/amy_database_structure.md, docs/users_guide/community_index.md
=> Update display of `Bluesky` field in missed template

amy/emails/actions/post_workshop_7days.py, docs/users_guide/admin_index.md
=> [Emails] Update conditions for Post Workshop 7 days

amy/emails/actions/new_membership_onboarding.py, amy/emails/tests/actions/test_new_membership_onboarding_integration.py, docs/users_guide/admin_index.md
=> [Emails] Update conditions for New Membership Onboarding

amy/dashboard/views.py
=> feat(#2758): Improve search for persons by their names

amy/dashboard/utils.py, amy/dashboard/views.py
This removes vector search and adds tokenized search instead.
=> feat(#2758): Bring back tokenized search

amy/dashboard/utils.py, amy/dashboard/views.py
=> feat(#2758): Bring back the old-old search

amy/emails/actions/base_action.py, amy/emails/actions/base_strategy.py, amy/emails/actions/instructor_badge_awarded.py, amy/emails/controller.py, amy/emails/signals.py, amy/emails/tests/actions/test_instructor_badge_awarded_cancel_receiver.py, amy/emails/tests/actions/test_instructor_badge_awarded_receiver.py, amy/emails/tests/actions/test_instructor_badge_awarded_strategy.py, amy/emails/utils.py, amy/templates/certificates/carpentries-instructor.svg, config/settings.py, poetry.lock, pyproject.toml
This fixes #2772.
~~WIP: missing tests, perhaps some corner cases should be fixed.~~
=> [Emails] Generate instructor certificate

amy/emails/actions/new_membership_onboarding.py, amy/workshops/models.py, config/__init__.py
=> [Emails] Update membership onboarding condition

amy/emails/actions/admin_signs_instructor_up_for_workshop.py, amy/emails/actions/ask_for_website.py, amy/emails/actions/base_action.py, amy/emails/actions/instructor_badge_awarded.py, amy/emails/actions/instructor_confirmed_for_workshop.py, amy/emails/actions/instructor_declined_from_workshop.py, amy/emails/actions/instructor_signs_up_for_workshop.py, amy/emails/actions/instructor_task_created_for_workshop.py, amy/emails/actions/instructor_training_approaching.py, amy/emails/actions/instructor_training_completed_not_badged.py, amy/emails/actions/new_membership_onboarding.py, amy/emails/actions/persons_merged.py, amy/emails/controller.py, amy/emails/forms.py, amy/emails/management/commands/create_emails_for_existing_events.py, docs/design/application_design.md, docs/design/projects/2023_automated_emails/base_actions.md, docs/design/projects/2023_automated_emails/email_controller.md, docs/design/projects/2023_automated_emails/index.md, docs/design/projects/2023_automated_emails/new_action_checklist.md, docs/design/projects/README.md, mkdocs.yml, pyproject.toml
=> [Emails] update emails developer documentation

.github/workflows/cicd_develop.yml, .github/workflows/cicd_main.yml, .github/workflows/cicd_main_manual.yml, .github/workflows/incl_build_and_deploy_production.yml, .github/workflows/incl_build_and_deploy_staging.yml
This is another part of #2762 work.
=> CI/CD for main branch - with deployment

Dockerfile, amy/templates/certificates/carpentries-instructor.svg
=> [Emails] Render SVG with correct fonts

amy/emails/actions/instructor_training_completed_not_badged.py, amy/emails/tests/actions/test_instructor_training_completed_not_badged_common_functions.py, amy/emails/types.py
=> [Emails] Add variable "certification_deadline" to email Instructor Training completed but not yet badged

amy/emails/actions/post_workshop_7days.py, amy/emails/tests/actions/test_post_workshop_7days_cancel_receiver.py, amy/emails/tests/actions/test_post_workshop_7days_strategy.py, amy/emails/tests/actions/test_post_workshop_7days_update_receiver.py, amy/emails/tests/test_utils.py, amy/emails/utils.py
=> [Emails] Don't cancel emails for 7days post workshop during that time after the workshop

amy/emails/actions/instructor_training_completed_not_badged.py, amy/emails/tests/actions/test_instructor_training_completed_not_badged_integration.py, amy/emails/tests/actions/test_instructor_training_completed_not_badged_strategy.py, amy/workshops/base_views.py, amy/workshops/models.py, amy/workshops/views.py
=> [Emails] Cancel instructor training completed not badged if badge awarded

amy/communityroles/forms.py, amy/static/communityrole_form.js, amy/workshops/lookups.py, poetry.lock
=> [#2799] empty autocomplete dropdown

amy/emails/actions/membership_quarterly_emails.py, amy/emails/tests/actions/test_membership_quarterly_emails_common_functions.py, amy/emails/tests/actions/test_membership_quarterly_emails_receiver.py, amy/emails/tests/actions/test_membership_quarterly_emails_update_receiver.py, amy/emails/types.py, amy/emails/views.py, amy/fiscal/views.py, amy/workshops/base_forms.py, amy/workshops/base_views.py, amy/workshops/forms.py, amy/workshops/views.py, pyproject.toml
=> [Emails] Improve membership quarterly emails
