carpentries/amy

workshops/forms.py, workshops/templates/workshops/index.html, workshops/templates/workshops/instructors.html, workshops/templates/workshops/search.html, workshops/urls.py, workshops/views.py
This addresses #24 and is an alternative to #101:
1.  Add a simple search form allowing a single word to be searched for (case sensitive) with radio buttons controlling search in site and event fields.
2.  Look for that word in fields of site and event.
3.  Return unsorted list of links to matching sites/events.
Search is implemented using SQL `like` (via Django's `contains`).
=> Simple-minded search

workshops/models.py
The field name doesn't make the meaning obvious, so record it in the
[help_text][1].  Discussion behind my phrasing is in #127.
[1]: https://docs.djangoproject.com/en/1.7/ref/models/fields/#help-text
=> workshops/models.py: Add help_text to Person.active

workshops/forms.py, workshops/models.py
Arliss requested that full airport names be displayed along with IATA codes when looking up instructors. This PR changes the way airport names are displayed so that the instructor search pulldown will do the right thing, then modifies the logic in the form's cleanup to match.
=> Adding airport names to instructor search.

workshops/templates/workshops/airport.html, workshops/templates/workshops/airport_form.html, workshops/templates/workshops/all_airports.html, workshops/templates/workshops/all_badges.html, workshops/templates/workshops/all_cohorts.html, workshops/templates/workshops/all_events.html, workshops/templates/workshops/all_persons.html, workshops/templates/workshops/all_sites.html, workshops/templates/workshops/all_tasks.html, workshops/templates/workshops/badge.html, workshops/templates/workshops/cohort.html, workshops/templates/workshops/cohort_form.html, workshops/templates/workshops/event.html, workshops/templates/workshops/event_form.html, workshops/templates/workshops/export.html, workshops/templates/workshops/instructors.html, workshops/templates/workshops/person.html, workshops/templates/workshops/person_bulk_add_form.html, workshops/templates/workshops/person_bulk_add_results.html, workshops/templates/workshops/person_form.html, workshops/templates/workshops/search.html, workshops/templates/workshops/site.html, workshops/templates/workshops/site_form.html, workshops/templates/workshops/task.html, workshops/templates/workshops/task_form.html, workshops/templates/workshops/validate_event.html, workshops/templatetags/breadcrumbs.py, workshops/urls.py, workshops/views.py
It may seem not connected, but thanks to new `CreateViewContext` and `UpdateViewContext` I was able to repair breadcrumbs.
1. These new views were created because Django basic `CreateView` and `UpdateView` do not carry template variables we needed. And because every update/create view uses variables `title` and (from now) `model`, I made `CreateViewContext` and `UpdateViewContext` that set these variables.
2. Breadcrumbs were neglected and inconsistent across pages. I removed unnecessary template tags code, took a look at what breadcrumbs are used most of the time and come up with some. More in commit message 2b164aaa482fdaeed8e9f835345f8968435954c7
This fixes #142.
EDIT: Forgot to mention that I fixed some URL regexp bug preventing sites editing.
=> Context views breadcrumbs

workshops/views.py
In `views.py` there was missing function `check_file`, defined in
`check.py`.
This fixes #144.
=> Fixed missing import function `check_file`

LICENSE.md
The usual Software Carpentry license for code.
License text downloaded from [1], with the <year> and <copyright
holders> markers filled in for our project.
[1]: http://opensource.org/licenses/mit-license.html
=> LICENSE.md: Distribute this project under the MIT license

workshops/models.py, workshops/views.py
These don't actually save us any work, since the instructors() view is
simpler without them.
They also break superuser addition when using Person as the user
model.  In my use-person-for-auth branch (swcarpentry/amy#147) without
this change, I see:
$ python3.4 ./manage.py syncdb
...
You have installed Django's auth system, and don't have any superusers defined.
Would you like to create one now? (yes/no): yes
Username: ...
Traceback (most recent call last):
File "./manage.py", line 10, in <module>
execute_from_command_line(sys.argv)
File "/.../django/core/management/__init__.py", line 385, in execute_from_command_line
utility.execute()
File "/.../django/core/management/__init__.py", line 377, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File …
=> workshops/models.py: Drop PersonQuerySet and PersonManager

workshops/views.py
This fixes NameError exception "global name 'Model' is not defined".
Exception occured in `CreateViewContext` class-based view.
This must have been my fault when I introduced `CreateViewContext` class
view.
=> Fix missing import (django.db.Model) in views

workshops/urls.py
Missing '$' (matches end-of-line or something like that) made
task edit view render task detail view.
=> Fix: '$' was missing in URL regex for task edit

workshops/models.py
When fetching Event by identification text, which could be either event
ID or slug, format `'YYYY-MM-text'` was not correctly matched.  Both
`'YYYY-MM-DD-text'` and `'ID'` worked correctly, though.
This is now fixed.  Fetching Event by ident now checks these 3 formats
(in this order):
* `'ID'`
* `'YYYY-MM-****'`
* `'YYYY-MM-DD-****'`
This fixes #171 .
=> Fix Event identification regex to include YYYY-MM format

workshops/test/test_util.py, workshops/util.py
Fix Python 3 incompatibilities that have landed since #140.  After
this series,
$ python3.4 manage.py test
passes again.
=> More Python 3 fixes for the test suite

workshops/test/test_util.py, workshops/util.py, workshops/views.py
This commit removes conditional StringIO import in a few source files as
well as fixes uploading unicode CSV-files.
Conditional import
==================
To support both Py2 and Py3 we had conditional imports:
```python
try:
from io import StringIO
except ImportError:
from cStringIO import StringIO
```
By moving to Py3-only we can drop these imports in favor of nice and
simple `from io import StringIO`.
Unicode issues with uploaded CSV files
======================================
By moving to Py3, it appeared that Django serves uploaded files as byte
files, not text files.  This forces us to encode upcoming files into
UTF-8 text files (which `TextIOWrapper` does).
`UnicodeWriter` removal
=======================
Helper class `UnicodeWriter` was required to make unicode CSV files,
because …
=> Remove Unicode Py2 shenanigans

workshops/templates/workshops/person_bulk_add_form.html, workshops/util.py, workshops/views.py
Instead of passing in an encoding and doing some issubclass stuff,
just require a Unicode stream in upload_person_task_csv.  In general,
decoding to Unicode as soon as possible and encoding to bytes as late
as possible makes for cleaner code (who better to know the proper
encoding than the first/last code that touches the content?).  We see
that here, with a simpler upload_person_task_csv implementation and
only a two more lines in person_bulk_add to wrap the incoming file in
a StreamReader.
The accept-charset business is a hack to work around shortcomings in
modern browsers.  For example, the data posted from my Firefox 24.8
looks like:
Content-Type: multipart/form-data; boundary=---------------------------196554893016147250581211961313
Content-Length: 477 …
=> workshops/util.py: Expect a Unicode stream in upload_person_task_csv

.gitignore, .travis.yml
This PR adds files required for testing on [Travis-CI](https://travis-ci.org/) server as well as measuring coverage through [coveralls.io](https://coveralls.io/).
The `.travis.yml` file was assembled from these instructions:
* http://docs.travis-ci.com/user/languages/python/
* https://github.com/coagulant/coveralls-python
Similarly looking files are supporting development of other open source projects (for example: [Tornado](https://github.com/tornadoweb/tornado/blob/master/.travis.yml), [Slumber](https://github.com/samgiles/slumber/blob/master/.travis.yml)).
This PR addresses #166.
=> Continuous integration and coverage reporting

workshops/models.py, workshops/test/test_event.py
Only setting the non-blank fields (published, site, and tags).  This
ensures that the form respects our blanks (e.g. they don't need a URL,
=> workshops/test/test_event.py: Add TestEventViews.test_add_minimal_event

workshops/views.py
Until we actually have permission groups to choose from it just
clutters the form.
Fixes #191.
=> workshops/views.py: Drop 'groups' from form fields

workshops/migrations/0003_remove_person_slug.py, workshops/models.py, workshops/test/base.py, workshops/views.py
Person.slug was replaced with Person.username.
This PR is based on @gvwilson work done in #205, but instead of making `Person.username` blank, `Person.username` stays the way it was previously (unique, non-nullable, non-blankable).
=> models.py: remove Person.slug

amy/settings.py
This is dictated by https://github.com/swcarpentry/amy/pull/204#issuecomment-76557668
and it's generally a good idea to use such variables with
per-application prefix.
If Greg's using specific "standard" for `DEBUG` values we can update our `settings.py` here to have: `AMY_DEBUG=$DEBUG AMY_SECRET_KEY=hjll... ./manage.py runserver`.
=> Add "AMY_" prefix to env vars DEBUG, SECRET_KEY

Makefile, README.md
Changing ```$ sudo python``` to  ```$ sudo python3``` at all places should suffice.
Please review.
=> Updated README.md to Python3

amy/settings.py, workshops/templates/base.html, workshops/templates/workshops/airport_form.html, workshops/templates/workshops/cohort_form.html, workshops/templates/workshops/event_form.html, workshops/templates/workshops/index.html, workshops/templates/workshops/person_form.html, workshops/templates/workshops/site_form.html, workshops/templates/workshops/task_form.html, workshops/templatetags/navigation.py, workshops/test/base.py
This PR:
* adds `navbar_element` template tag
* adds 4 new positions in the navigation bar (on top of the page)
* adds a search form in the navbar - a shortcut to the official search
page
Ref #194
=> Extended navigation bar

workshops/models.py
Instead of `wilson.g:Greg Wilson <gvwilson@software-carpentry.org>`, we now display just `Greg Wilson <gvwilson@software-carpentry.org>`.
=> Removing user slug from display of user name

workshops/models.py, workshops/templates/workshops/index.html, workshops/test/test_event.py, workshops/views.py
The aim of this PR is to show a third column on the dashboard page listing all the workshops that owe us an admin fee. The test for these workshops is:
* admin_fee > 0
* fee_paid != True (i.e., is either False or unknown (NULL))
EventQuerySet.unpaid_events is supposed to return this set, but it isn't working.  The test I conducted is to modify the standard (fake) test data like this:
~~~
update workshops_event set admin_fee = 1500 where id=344;
update workshops_event set admin_fee = 1500 where id=343;
update workshops_event set fee_paid = 0 where id=343;
~~~
and then check with:
~~~
select * from workshops_event where admin_fee > 0.0;
343|1|2015-07-02|2015-07-03|2015-07-02-UQ|https://github.com/bio-swc-bne/2015-07-02-UQ|||1500|0|||241 …
=> Trying to get a list of workshops that owe us money

workshops/forms.py, workshops/models.py, workshops/templates/workshops/all_events.html, workshops/templates/workshops/search.html, workshops/templates/workshops/site.html, workshops/templates/workshops/validate_event.html
In rare occasion when events don't have any deatils about them,
especially the slug, we should display event details using
`event.get_ident` as it returns either slug or ID.
Ref #257
=> Fix: template rev. URL error for events w/o slug

workshops/migrations/0005_auto_20150506_0848.py, workshops/models.py, workshops/templates/workshops/event.html, workshops/urls.py, workshops/views.py
This PR changes the way events and tasks are deleted: they're marked as deleted (`object.deleted=True`) instead of being removed from the database for real.
It was achieved by adding a filter to default query sets for both models.
A downside of this solution is that we can still delete an event/task by:
```python
task.delete()
event.delete()
Task.objects.filter(…).delete()
Event.objects.filter(…).delete()
```
These commands will result in objects being removed from the database.
=> Mark events and tasks as deleted

Makefile, workshops/management/commands/export_airports.py, workshops/management/commands/export_badges.py, workshops/views.py
1.  Update code used to export YAML for instructors-by-airport to be what the main website's map now needs.
2.  Add management command to export YAML for airports from the command line.
3.  Add management command to export YAML for badges from the command line.
4.  Add Makefile targets to run those commands.
5.  Create a variable in the Makefile to specify what Python we're running.
=> Exporting YAML needed by main web site

workshops/templates/workshops/index.html, workshops/views.py
1.  Add number of instructors and a flag showing whether dates are known to dashboard display of unpublished workshops.
2.  Moving the widened display to the side.
=> Displaying more information about unpublished workshops

workshops/models.py, workshops/templates/workshops/all_events.html, workshops/templates/workshops/debrief.html, workshops/templates/workshops/index.html, workshops/test/test_tasks.py, workshops/views.py
Hi,
I've added some methods to `TaskManager`, so that we can easily filter by the role name.
This for example makes easier for us to calculate the number of instructors per event - we don't have to run a loop for that. One eyesore less.
Additionally I updated `/debrief/` so that it provides a more verbose output: links to event/person detail pages, number of workshops a person has taught. This should fix #214.
=> TaskManager methods for roles lookup

README.md
This commit should resolve #261 where @wking suggested to update
`README.md`.
A few grammatical errors were fixed.
Sections were introduced (`Getting started`, `Upgrading`, `Contact`).
A new step to *Getting started* section was introduced (cloning the
repository).  Some notes were added.
A new section, *Upgrading*, was added (this directly relates to the
suggestion in #261).
=> README.md: Fix grammar, new *Upgrading* section

Makefile
git log:
* added "=", so that "--date" is now "--date=short". This was causing
errors on Small Orange (git version 1.7.1)
* switched "--pretty=format:" to shorter "--format="
git describe:
* send stderr to /dev/null
Fixes #278.
=> Makefile: fix git log, git describe commands

workshops/templates/workshops/all_awards.html, workshops/templates/workshops/all_badges.html, workshops/urls.py, workshops/views.py
The "all badges" page displays all the badges we can hand out.  However, the "badge details" page was displaying particular awards, not the details of the kind of badge (such as the criteria).  This inconsistent naming became a stumbling block when I wanted to add a new form to let us award a badge (e.g., give someone an instructor badge).  This PR changes things so that the "all badges" page links to pages showing who has been awarded particular badges.  Once this is merged, we can add another form that will allow for creation of new awards (i.e., assignment of badges to persons).
=> Regularizing use of names 'badge' and 'award'.

workshops/views.py
Names like `all_tasks` were being used both as function names and as the names of variables inside those functions.  This fixes that.
=> Some view functions had variables with the same names as the functions.

workshops/templates/base.html, workshops/templates/workshops/airport.html, workshops/templates/workshops/all_airports.html, workshops/templates/workshops/all_events.html, workshops/templates/workshops/all_persons.html, workshops/templates/workshops/all_sites.html, workshops/templates/workshops/all_tasks.html, workshops/templates/workshops/event.html, workshops/templates/workshops/person.html, workshops/templates/workshops/site.html, workshops/templates/workshops/task.html, workshops/templates/workshops/validate_event.html, workshops/views.py
This PR addresses #296 and #297.
I've only done work for event-related pages. If they're okay, I'll complete other pages, too.
"New object" button was changed (green color, no "Add a" text):
------
Event details page now contains "Edit" and "Delete event" buttons:
------
Events without URL show "Error" button with explanation:
------
Events with URL show "Validate" button that opens a modal window with validation results inside:
Validation on fake URL triggers 500 Server Error.
=> Buttons, links, validation, etc.

README.md
This snuck in with 9f35e49f (Updating README to sync with Makefile
deletions, 2015-05-19, #284).
=> README.md: Fix 'wit' -> 'with' typo

workshops/migrations/0007_auto_20150530_0537.py, workshops/models.py, workshops/templates/workshops/all_events.html, workshops/templates/workshops/event.html, workshops/templates/workshops/index.html, workshops/test/test_event.py, workshops/views.py
It isn't Amy's job to track whether money has arrived - that's the job of NumFOCUS's accounting system.  Instead, we should track whether an invoice has been sent, i.e., have we handed responsibility off to NumFOCUS.  This change of name makes those semantics clearer.
=> Renaming Event.fee_paid to Event.invoiced.

amy/settings.py, requirements.txt, workshops/migrations/0007_migrate_countries_to_2char_iso31661.py, workshops/migrations/0008_auto_20150522_1304.py, workshops/migrations/0010_merge.py, workshops/models.py, workshops/static/css/amy.css, workshops/templates/workshops/airport.html, workshops/templates/workshops/site.html
This solves #62.
Features:
* Data migration for old country fields (Site.country, Airport.country: shorten country names to [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1)). Not all countries can be migrated this way, but I used production database to get list of the countries and provided a mapping for them myself.
* "Normal" migration.
* Display of country flags in site/airport detail pages.
* Minor style fixes.
=> Use django-countries

workshops/models.py
Once this is merged, the home page dashboard will show upcoming events with the soonest at the top.
=> Ordering upcoming workshops by date, soonest first

workshops/forms.py
The `Event` model allows the `organizer` field to be NULL, but the form wasn't allowing it to be empty.  This PR fixes that by allowing `organizer` to be left empty in the event creation form.
This fixes #330.
=> 'Organizer' field of Event is optional.

workshops/forms.py, workshops/models.py, workshops/templates/workshops/person_edit_form.html, workshops/test/base.py, workshops/test/test_person.py, workshops/urls.py, workshops/views.py
This is a little bit alternative to #110, and somewhat more limited in options, as it only allows us to add one badge per request from the person-edit view.
However, in here we use two crispy forms that integrate easily and visually appeal, + we have tests in place.
=> Award badges from person-edit view

workshops/templates/workshops/person_bulk_add_results.html, workshops/test/test_util.py, workshops/util.py
1.  Report exactly which name field failed to match.
2.  Show blanks when there are no errors (rather than dashes).
3.  Modify pattern matching to match empty string in uploaded data vs. null in database to avoid spurious errors.
=> Improving pattern-matching and error reporting in bulk upload.

amy/settings.py, amy/urls.py, workshops/admin.py
Plus remove basic admin forms for workshops application.
We don't need them.
Resolves #41.
=> Turn off Django Admin completely

workshops/filters.py, workshops/templates/pagination.html, workshops/templates/workshops/all_airports.html, workshops/templates/workshops/all_events.html, workshops/templates/workshops/all_persons.html, workshops/templates/workshops/all_sites.html, workshops/templates/workshops/all_tasks.html, workshops/templates/workshops/badge.html, workshops/templatetags/pagination.py, workshops/views.py
Switching pages with pagination erased our filters from address, for example:
* page 1: `/workshops/events/?order=slug`
* page 2 should be: `/workshops/events/?order=slug&page=2`, but was: `/workshops/events/?page=2`
Additionally:
* a generic pagination template was used, so we're more DRY
* I decided to change ordering of events to DESC BY SLUG by default; I believe that was the order from before django-filters.
=> Pagination error with filtering

workshops/templates/workshops/event.html, workshops/templatetags/links.py
Display two links for an event:
* a website link (ie. http://user.github.io/repo)
* a repo link (ie. https://github.com/user/repo)
Resolves #325.
=> Two links for event

workshops/forms.py, workshops/templates/workshops/person.html
Username was missing on person details page.  This commit adds it on top
of the table with details.
=> Display person's username

README.md
The instructions skipped this step to it was not possible to successfully run
the command `python3 manage.py createsuperuser` as the tables in the sqlite3
database were not complete.
=> Added `make migrations` command to README

workshops/templates/base_without_navbar.html, workshops/templates/workshops/_page_fluid.html
A left-side offset was added to the messages on fluid layouts.
=> Fix: success/error messages hovered by filter control

CONTRIBUTING.md, README.md, workshops/static/css/amy.css, workshops/templates/account/logged_out.html, workshops/templates/amy-logo.html, workshops/templates/base.html, workshops/templates/base_without_navbar.html, workshops/templates/workshops/index.html, workshops/templatetags/breadcrumbs.py, workshops/test/base.py
We're switching from 'Amy' to 'AMY' to distinguish between real people and this project.
I think we have a consensus to leave 'amy' as the name for the eventual packages (PyPI / NPM), and 'AMY' for the project.
This resolves #328.
=> Switch from 'Amy' to 'AMY'

workshops/templates/workshops/person.html
The person display page was showing badge names in the main table, separated by commas, but also listing them individually under "Awards" further down.  This removes the first of those two displays.
=> Removing redundant display of badges from person page.

workshops/templates/workshops/event_diff.html, workshops/templates/workshops/person_diff.html
Fields were reordered in event_diff, person_diff pages to appear in the
same order as in EventForm and PersonForm.
Missing field 'notes' for Event was added.
=> Fix fields in *_diff pages

workshops/migrations/0027_auto_20150714_1143.py, workshops/models.py, workshops/test/test_event.py
1. Event.slug has unique=True
2. Proper migration is introduced
3. Event.save() is altered to save empty slugs as NULLs
4. Test for saving events with non-unique slugs
5. Test for saving events with empty slugs
This fixes #427. This is a general bug, not related to #426 (but discovered by @gvwilson when testing that PR).
=> Fix: make Event.slug unique

workshops/test/test_search.py, workshops/views.py
This fixes #319.
The fix: if the term can be tokenized to 2 words (for example: `"Piotr Banaszkiewicz"` → `["Piotr", "Banaszkiewicz"]`), then the search looks for people who have `personal=FIRSTTERM, family=SECONDTERM` or `personal=SECONDTERM, family=FIRSTTERM`.
Additional improvement was made to the search yielding only one record. In this case, user is redirected immediately to that result's details page.
WIP: missing tests.
=> Fix: searching for "name lastname"

workshops/models.py, workshops/templates/workshops/failed_to_delete.html, workshops/test/test_event.py, workshops/views.py
This fixes #383.
There's one small issue: we prevent events from deletion when there are some awards related. The thing is that we can't delete awards, we have no award-details page nor award-delete view.
@gvwilson what would you like to have? I think we need to add both award-detail page and award-delete view.
=> Protect awards when deleting events

workshops/migrations/0030_auto_20150720_0311.py, workshops/migrations/0031_auto_20150720_0344.py, workshops/models.py, workshops/test/test_event.py
This fixes #435.
Attendance is database-constrained, but admin_fee is only form-constrained. This means that if someone executes code `e.admin_fee = -1200` it will work, but `e.attendance = -36` won't.
So the admin_fee constraint applies only when adding/editing events via form.
=> Nonnegative administrative fee and attendance for Event

amy/settings.py, amy/urls.py, api/serializers.py, api/test/test_export.py, api/urls.py, api/views.py, requirements.txt, workshops/templates/base.html, workshops/templates/workshops/export.html, workshops/urls.py, workshops/views.py
Hi,
this PR adds django-rest-framework and two REST views (for exporting badges and instructors).
When you start the development server, go to: http://127.0.0.1:8000/api/v1/ and follow links to other resources.
These websites are generated with django-rest-framework entirely for viewing purposes (it will help other developers with implementation of that API).
To-do:
* ~~throttling~~
* ~~YAML format output~~
* rebuilding 'site' with API calls (PR in different repository)
Once YAML output is implemented, this PR will solve (sometimes partially):
* #432 (API for badges, airports)
* #454 (API for badges, YAML for exporting badges from `/workshops/export/badges`)
* #455 (API for airports, YAML for exporting instructors from `/workshops/export/instructors`)
This PR leaves missing:
* API for …
=> Basic REST API

workshops/management/commands/import_archived_workshops.py
The data is gathered from swcarpentry/site archives
(`config/archive.yml`).
This new management command also updates 'contact' field.
The command was needed because I introduced location fields to the AMY in v0.7, but no-one should update them manually…
=> Import location data for historical workshops

api/test/test_events.py, api/test/test_export.py, api/views.py, workshops/management/commands/export_airports.py, workshops/management/commands/export_badges.py
export-* commands used workshops.views views instead of calling
API endpoints.
This fix "simulates" the incoming request and then gets back all the
data from API, and serializes it in YAML.
This fixes #474, but the output format changes slightly (since the switch to API).
=> Fix: export-* management commands use API

workshops/forms.py, workshops/test/test_host.py, workshops/views.py
This fixes #468.
Includes regression test.
=> Prevent users from entering 'http://' or '/' as part of Host.domain

amy/settings.py, amy/urls.py, workshops/migrations/0039_add_permission_groups.py, workshops/templates/base.html, workshops/templates/workshops/airport.html, workshops/templates/workshops/all_airports.html, workshops/templates/workshops/all_events.html, workshops/templates/workshops/all_hosts.html, workshops/templates/workshops/all_persons.html, workshops/templates/workshops/all_tasks.html, workshops/templates/workshops/event.html, workshops/templates/workshops/host.html, workshops/templates/workshops/person.html, workshops/templates/workshops/task.html, workshops/templatetags/navigation.py, workshops/views.py
This PR implements #464.
Work so far:
* setting `@permission_required` decorator (in various forms) for all non-read-only views (for example `delete_host` or `person_add`)
* hiding elements of UI for users without specific permissions
So in order to give someone a read-only access to AMY, all we have to do is to enable them to log in.
If we want to have someone as an administrator (like Maneesha or Giacomo), we can either set them as superuser (that's how it's done now) or explicitly select all specific permissions for them.
Things to consider:
* adding permission groups 'administrator', 'steering committee'
* adding a 'can_login' field to `Person`
The permission groups may be just a more verbose way so say that someone belongs to administrators or steering committee.
The …
=> Permissions

api/serializers.py, api/test/test_export.py
This allow the main website to gather countries from this API call, so that we no longer have to manage the country flags manually.
=> Adding 'country' field to 'airport' record in API.

workshops/views.py
The forms for requesting SWC and DC workshops didn't say which kind of workshop it was - this adds that. It also make the title of the instructor info update form clearer.
Question: why are the SWC and DC workshop request forms classes, while the instructor info update form is a function?
=> Making form purpose clearer in titles.

workshops/templates/workshops/badge.html, workshops/templates/workshops/person_edit_form.html, workshops/test/test_badge.py, workshops/urls.py, workshops/views.py
This fixes #434.
It's now possible to remove Award from person's details page or from
badge's details page. Both removals should end up with correct
redirects.
Tests are included.
=> Add: remove award functionality

amy/settings.py
This commits adds back the "fake" EU country. Apparently Europe's flag is already present in the django-countries, it's just the country that's not available.
=> Add back the EU country, since it's used in some hosts

workshops/filters.py, workshops/forms.py, workshops/management/commands/report_invoicing.py, workshops/migrations/0040_invoice_status.py, workshops/models.py, workshops/templates/workshops/all_events.html, workshops/templates/workshops/event.html, workshops/templates/workshops/event_diff.html, workshops/test/base.py
Actually the Event.invoiced field was migrated to text field and renamed
`invoice_status` since it doesn't answer the question
"Was the workshop's host invoiced?", but rather shows the status of
workshop's invoicing.
This commit provides:
* all necessary migrations
* display changes (`invoiced|yesno` -> `get_invoice_status_display`
mostly)
* test updates
This fixes #469.
=> Add more options to Event.invoiced

workshops/test/test_util.py, workshops/util.py
I put "empty" in quotes because these lines may just as well be composed
of commas (something like ",,,,,"), but after parsing they would make
dicts with proper keys but no values.
This fixes #512.
=> Fix: ignore "empty" lines in CSVs bulk-uploaded to AMY

workshops/templates/workshops/all_eventrequests.html, workshops/templates/workshops/all_profileupdaterequests.html, workshops/templates/workshops/eventrequest.html, workshops/templates/workshops/profileupdaterequest.html, workshops/test/test_event_requests.py, workshops/test/test_profile_update_request.py, workshops/urls.py, workshops/views.py
This fixes #523.
New "filter switch" was added on both event requests and profile update requests lists. They allow users to quickly switch between closed and open requests.
=> Switch for new/closed requests

workshops/filters.py, workshops/forms.py, workshops/migrations/0054_auto_20151021_1347.py, workshops/models.py, workshops/templates/workshops/all_events.html, workshops/templates/workshops/event.html
Fixes #471.
The implementation adds a new field, `Event.completed` — it will be easier to do filtering in all-events view than when using Tag to do this task.
For example, with current approach we can display all events, events complete, or events incomplete. With Tag-approach we could only filter events incomplete, or complete.
I decided to not change the dashboard at all. My thinking is admins will only mark events as completed once they're not ongoing, nor upcoming, nor uninvoiced, nor unpublished.
If you would rather have `Event.complete` than `Event.completed`, just let me know.
=> Complete events

workshops/templates/workshops/profileupdaterequest.html
1. Move fields not being saved to DB to the bottom of the form
2. Separate these fields with long horizontal row saying
"These aren't saved"
3. Change "N/A" to "<em>Not available</em>"
4. Add some '|default:"—"' to the fields that didn't have this filter
This fixes #538 but in a different way (see attachment).
This PR will cause conflict once #528 is merged.
=> Profile update request view: fix couple of issues

workshops/models.py, workshops/test/base.py, workshops/test/test_event.py
This fixes #550.
Event.objects.uninvoiced_events() returns only past events with
invoice_status of 'not-invoiced'.
Previously these events had to have non-zero (non-null) admin fee
specified to be considered "uninvoiced".
=> Fix: uninvoiced events don't have to have an admin fee upfront

workshops/migrations/0054_self_organized_host.py, workshops/migrations/0055_auto_20151031_0832.py, workshops/migrations/0056_merge.py, workshops/models.py, workshops/test/test_search.py
This fixes #484.
A new host ('self-organized') was added.
Events that had no administrator and one of the following conditions were updated with 'self-organized' as admin:
* have "self-organized" in notes, or
* have "self organized" in notes, or
* have "Not applicable since self-organized" as invoice status
WIP since I'm waiting for the list of self-organized events.
=> New host: self-organized

workshops/templates/workshops/instructor_num_taught.html, workshops/urls.py, workshops/views.py
Report who has taught how often in downloadable CSV format.  Only remaining issue is the use of 'award.person.airport.country' in the template has to be wrapped with 'if' because 'award.person.airport' may not exist, so we sometimes get 'xxx-unset-variable-xxx' - haven't been able to find a filter that'll catch this and display '-' instead.
=> Reporting how often people have taught

workshops/forms.py, workshops/test/test_event.py
Rule: disallow characters other than [\w-].
This also adds test for that change.
This fixes #563.
=> Change the way slugs are verified in the EventForm

api/test/test_events.py, workshops/models.py, workshops/test/base.py, workshops/test/test_event.py, workshops/util.py
Events without start date caused `"".format()` to error out because it received `None` object instead of `datetime`.
The fix was merged to the master and deployed so that admins can continue to work.
=> Hotfix: wrong date formatting on event's details page

api/serializers.py, api/test/test_events.py, api/views.py
Filtered values:
* administrator organization
* host
Both take IDs.
Additionally a new value is being returned by the API: event's
eventbrite ID.
This fixes #529.
=> Add filtering to published events API endpoint

workshops/test/test_util.py, workshops/util.py, workshops/views.py
This fixes #584.
Cases:
* tag is missing from the website - we get `None`
* tag has string content
* tag has empty string content
Tests for these cases were added.
Another change:
slug is now returned in `event_import` view when using the old, workshop
index.html method.
=> Fix: react to more tricky cases of latitude/longitude/eventbrite_id

workshops/migrations/0062_add_stalled_unresponsive_tags.py, workshops/models.py, workshops/templates/workshops/all_eventrequests.html, workshops/templates/workshops/all_events.html, workshops/templates/workshops/event.html, workshops/templates/workshops/instructor_issues.html, workshops/templatetags/tags.py, workshops/test/test_instructor_issues.py, workshops/test/test_landing_page.py, workshops/views.py
For use in cases when admins lost contact with event's host, or for TTT
events that are no longer running.
Fixes #549.
Fixes #545.
=> Add 'stalled' tag

workshops/migrations/0062_no_invoice_for_historic_events.py, workshops/models.py
Retire events older than 2014, ie. change their invoice status from
unknown to "not invoice for historical reasons" and mark them as
completed.
Fixes #587.
=> Add more enumeration choices for Event.invoice_status

workshops/models.py, workshops/templates/workshops/attendance_email_href.html, workshops/templates/workshops/event.html, workshops/templates/workshops/workshop_issues.html, workshops/util.py, workshops/views.py
Used on event's details page and on workshop issues page.
This commit also contains:
* new utility function `find_emails` for finding emails in text (it's
being used to find emails in Event.contact)
* "mailto:..." content of 'href' attributes was factored out into new
template (since we don't like repeating ourselves). It's being used by
event.html, workshop_issues.html templates.
This fixes #553.
=> Event.mailto: new property for grabbing event's contact emails

workshops/test/test_views_404.py, workshops/views.py
What I mean is that they were doing `Model.objects.get(**data)`, but
should instead do `get_object_or_404(Model, **data)`.
This commit fixes this + provides regression tests for these views.
This fixes #611.
=> Fix: some views didn't correctly respond to wrong input data

amy/settings.py
This one:
* stops sending notifications to me (and Greg, as of #595)
* starts sending notifications to our sysadmin mailing list
* stops informing about "invalid HTTP_HOST header" errors (someone requests our pages without proper HOST header, usually "104.130.229.225" [which is server's IP address] or "*.software-carpentry.org")
=> Suppressing invalid HTTP HOST notifications

workshops/models.py
Spaces are stripped upon saving the object.
This fixes #612, #619.
=> Fix: strip spaces from names and email in Person, ProfileUpdateRequest

workshops/static/online_country.js
Error was: location inputs were not disabled if someone entered an edit
page for event which country was 'Online'.
They were only being disabled/enabled when changing the country to/from
'Online'.
This commit fixes this error.
It fixes #591 too.
=> Fix: disable inputs for online country if it was preselected

workshops/forms.py
This fixes #559 by changing default widgets to TextInput for these
fields:
* admin_fee
* attendance
* latitude
* longitude.
Unfortunately the `admin_fee` field's declaration is more important
than Meta.widgets content so the widget for admin_fee had to be
overwritten in the declaration.
Let me just add that the reason for this change is that under MacOS the HTML5 widgets can change value upon scrolling over them. This is not the case for Linux, and certainly not for Windows, but our admins use MacOSX so…
=> workshop/forms.py: change some fields' widgets to TextInput

api/serializers.py, api/test/test_export.py, api/views.py
This fixes #604.
The 'export members' view will be accessible only to users who are logged into AMY.
=> API: return members' usernames

workshops/templates/workshops/debrief.html, workshops/views.py
Additionally fix indentation in the template (it was tabs, should be
spaces) and speed up the retrieval of related objects (event, person,
role).
This fixes #643.
=> Debrief: exclude stalled, TTT and unresponsive events from search

workshops/templates/workshops/workshop_issues.html, workshops/test/test_util.py, workshops/util.py, workshops/views.py
This is based off of dashboard's filtering widget (three buttons saying
'Mine | Unassigned | All').
An auxiliary function was introduced to help decide what '?assigned_to'
means depending on user's permissions (it's used in both dashboard
and workshop issues views).
This fixes #609.
=> Workshop-issues: add filtering by assignment

workshops/forms.py, workshops/migrations/0068_auto_20160119_1247.py, workshops/models.py, workshops/templates/workshops/event.html
This fixes #578.
The new fields are displayed in the table on event details page.
On the event-edit page, the fields are wrapped together into
a nice-looking container, which should help separate them visually.
=> Event: add fields for survey links

workshops/forms.py, workshops/test/test_event.py, workshops/test/test_person.py, workshops/test/test_todos.py, workshops/views.py
Fixes #632.
On my machine, not a single test lasts more than 0.5s, which I think is good enough for now. Once the test base grows to about 250-300 tests, we may need to rethink testing again.
Some tests were replaced with similar ones, but the slow part (usually calls to views) was removed, so these tests aren't identical.
=> Repair slow tests

Makefile
Initial revisions will be created for objects created in fake_database
command.
This fixes #638.
=> Dev database: create initial revisions automatically

workshops/migrations/0072_underscore_usernames_fixed_migration.py
The error in previous migration was: even though there was a function
for migrating usernames, the operation for running this function was
never added.
Worse even: we have one server which applied this migration already, so
it was decided to add a new migration (properly this time!).
=> Fix: run migration responsible for changing _ to . in usernames

api/filters.py, api/serializers.py, api/test/test_api_structure.py, api/urls.py, api/views.py, bower.json, workshops/templates/base.html, workshops/templates/workshops/all_activity_over_time.html, workshops/templates/workshops/instructor_num_taught.html, workshops/templates/workshops/time_series.html, workshops/urls.py, workshops/views.py
This fixes #631 by:
* adding an API report with requested data
* adding a web interface for that API request
This fixes #616 by:
* moving `{workshops,instructors,learners}_over_time` to API (as reports)
* adding graphs to their web interfaces
* moving `instructors_num_taught` to API as well (again, as report) - its web interface doesn't change much, though
* moving `instructors_activity` to API (this will be done after WIP)
WIP: I want to merge #649 and then rebase this one as with #649 we may get better serializers+views and use hyperlinked resources in some of the new reports.
EDIT: rebase is done, so now we need to fix all the TODOS in the code.
EDIT: TODOS fixed, but I want to change one report and be done.
=> API reports

workshops/management/commands/trainings_completion_rates.py, workshops/templates/reports/training_completion_rates.txt
The management command reports:
* training tags,
* badge used for lookups,
* number of learners,
* how many of them got a badge for that training,
* how many of them got a badge for other training,
* how many of them have no badge.
This fixes #667.
=> Add report of completion rates for instructor trainings

api/urls.py
For unknown reason they threw NoReverseMatch.
This fixes #682 by removing the URLs (actually removing the inclusion of
these URLs).
=> Remove erroring DRF URLs

api/views.py, requirements.txt
Other views can't be rendered with this renderer since they use
a non-flat structure.
This fixes #684.
=> Install CSV renderer in one export view

workshops/filters.py, workshops/models.py, workshops/test/test_landing_page.py, workshops/views.py
This fixes #651.
Active event means:
* it's not stalled (it doesn't have "stalled" Tag)
* it's not marked as completed.
Altered views:
* dashboard
* workshop issues
=> Show only active events in various places

workshops/templates/workshops/workshop_issues.html, workshops/test/test_issues.py, workshops/views.py
This fixes #661 by extending search for events with no tasks with
role=instructor.
Additionally, tests against that view were introduced.
=> Workshop issues: show events w/o instructors

workshops/test/test_util.py, workshops/util.py
This fixes #694 by throwing Http404 when ValueError happens.
New tests were introduced to ensure `assign` mechanics work correctly.
=> Fix: error when looking up non-int person id for assignment

amy/settings.py
Anonymous user: from 100/day up to 50/hour [6x] (production uses about
10/hour, leaving about 40/hour to other users trying to build the SWC
website).
Logged-in user: from 1000/day up to 200/hour [2.4x].
It's cumbersome to set up token access to the API
(http://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication)
so I may set up an account for production script later on (ref.
https://github.com/swcarpentry/website/issues/223).
=> API: up throttle rates

workshops/templates/navigation_fixed.html, workshops/templates/workshops/duplicates.html, workshops/templatetags/assignments.py, workshops/test/test_finding_duplicates.py, workshops/urls.py, workshops/views.py
This fixes #624.
This PR provides a new view for finding possible duplicates amongst persons.
It looks for people who may have gotten their names switched (person↔family mixed up), and for people who may appear in the database more than once.
=> Finding duplicates

workshops/lookups.py
The new lookup unfortunately has to reuse code from django-selectable.
It's splitting term for tokens, each applied against first/last name.
This fixes #712.
=> New lookup to PersonLookup: matches tokenized names

workshops/test/test_finding_duplicates.py, workshops/views.py
The `List duplicates` page currently displays all persons if no duplicates are found.
This fix resolves the issue.
=> Empty results if no duplicates found

workshops/test/test_profile_update_request.py, workshops/views.py
The report email came during the night: incomplete form submitted to find a matching person didn't work correctly (caused server 500 error).
The error was: `form` variable was unbound in the local scope (which was a result of wrong steps order in the person matching logic).
=> Fix: 500 when submitting incomplete person match form

workshops/test/test_event.py, workshops/test/test_util.py, workshops/util.py, workshops/views.py
This PR fixes two bugs related to event importing:
1. missing `url` GET param when accessing `event_import` view caused 500
2. AttributeError when imported event had no instructors/helpers listed
=> Fix: event_import AttributeError and uncaught request exception

api/views.py
This fixes #725.
The fix is to turn iterables (generators in our case) into lists if the specific format is requested by the browser/user.
=> API: fix CSV, YAML renderers to render iterables correctly

workshops/test/test_event.py, workshops/test/test_person.py, workshops/util.py
The issue was: some related objects were removed instead of being
unassigned (in M2M relation or when FK relation was set `null=True`) in merge operation.
=> Fix: removal of M2M-related objects during merge

workshops/templates/workshops/profileupdaterequest.html, workshops/test/test_profile_update_request.py, workshops/urls.py, workshops/views.py
This fixes #741 by allowing users to add a new person from ProfileUpdateRequest.
Button responsible for adding is located next to "Update" button on profile update request view.
=> Add new people from profile update request

workshops/lookups.py
Query was matching either superusers or people from administrators
group, but if someone was in both categories they ended up twice on
the list.
Switching query to distinct mode fixed this error.
This fixes #764.
=> Fix: remove duplicated names from AdminLookup query

workshops/templates/workshops/airport.html
For example, when airport iata is CVG, it generated an invalid link to `http://cvg`. This patch makes the airport iata a static text instead of a hyperlink.
=> Delete broken iata link in airport_details view

workshops/views.py
The variable for storing template name was named 'form_template'
but it should have been 'template_name'.
Now the correct template is served.
This fixes #760.
=> Fix: wrong variable name for DC workshop request form

workshops/templates/workshops/instructors_by_date.html, workshops/views.py
Two bugs were fixed:
- There might be dangling commas if we don't know email of some
instructors, that is "john@example.com,,,bob@example.com," could be
generated. See #766 issue.
- Instructors who don't want to be contacted (that is, may_contact
is False) were included in the list.
=> Improved instructors' emails list generation in instructor_by_date view

workshops/templates/workshops/event.html, workshops/views.py
This fixes #754.
@pbanaszkiewicz Please review.
=> Allow users without `add_todoitem` permission to view an event

workshops/templates/workshops/event_import_update_from_url.html
This was confusing to admins as if they could not use other URLs
than `username.github.io/workshop`.
This fixes #757.
=> Fix: example of website URL for update from URL form

workshops/models.py, workshops/templates/workshops/all_persons.html, workshops/templates/workshops/event.html, workshops/templates/workshops/instructors.html, workshops/views.py
This is a patch created by @gvwilson (#762) with my minor tweaks.
Closes #759.
- Modifying display of all persons to distinguish Software Carpentry and Data Carpentry instructors.
- Modifying display of tasks associated with Event to distinguish Software Carpentry and Data Carpentry instructors.
=> Display SWC/DC instructor status in names (patched)

workshops/management/commands/fake_database.py, workshops/templates/navigation_fixed.html, workshops/urls.py, workshops/views.py
The training dashboard is available in the nav bar: more -> Trainings. The dashboard displays list of recent instructor training along with number of all participants and number of participants who has become SWC/DC instructors.
=> Add trainings dashboard

workshops/management/commands/check_for_workshop_websites_updates.py, workshops/templates/workshops/dashboard.html, workshops/templates/workshops/events_tag_changed.html, workshops/test/test_commands.py, workshops/test/test_event.py, workshops/urls.py, workshops/views.py
This fixes #769.
This PR:
1. fixes `check_for_workshop_websites_updates.py` command a little (real-test run showed that `PyGithub` module throws some errors)
2. adds notification to the dashboard for admin whose events have changed metatags.
The machinery for viewing/accepting/dismissing changed metatags was already in place from previous PR (#752).
=> Notification about changed metatags

workshops/templates/workshops/time_series.html
If using linear interpolation is not an option, we can set `interpolate_tension` to a high value (i.e. 0.95).
EDIT (@pbanaszkiewicz): this fixes #779.
=> Use linear interpolation to eliminate backward bends on charts

workshops/test/test_util.py, workshops/util.py
Changed event validation. It now checks expected format only for tags
that are required or that have a non-empty value.
This fixes #813.
=> Fix event validion: check format for required or non-empty tags

api/test/test_reports.py, api/views.py
Fixes #787
This solution makes a change to the list of instructors displayed.
Earlier, the instructors with SWC/DC badges who didn't teach (as an instructor) in any workshop were also listed with their corresponding count being zero.
Now, only instructors with non-zero frequency are listed.
Is that fine?
=> Prevents duplication of frequency for instructors with both DC and SWC badges.

workshops/test/test_views_404.py, workshops/views.py
The issue was: we should have used `get_object_or_404` instead of
`Host.objects.get` because the latter throws error 500 when specific
host cannot be found.
Additionally changed one test's name so that it's discovered by the test
runner.
=> host_details: fix 500 instead of 404 when no matching host

workshops/test/test_person.py, workshops/util.py, workshops/views.py
For example: merging two people with similar task of being a learner at
the event '2016-05-29-copacabana' would yield IntegrityError when trying
to use "combine" strategy since after merging there would be two
identical tasks (both learner, event '2016-05-29-copacabana' and the
same person) - and that violates the uniqueness constraint.
This fixes #755.
=> Fix IntegrityError when merging people with similar M2M related objects

api/views.py
The use of `lower` instead of `lower()` was preventing data download from working (bug detected 2016-06-13).
=> Fixing unparenthesized method 'call'.

workshops/forms.py
Specifing explicitly list of all fields included in the form, that is
using `Meta.fields` instead of `Meta.exclude` in order to prevent such
bugs in the future.
=> Remove 'active' field from TrainingRequestForm

workshops/forms.py
Replace "I agree to help teach" with "I agree to teach", because we want
new instructors to actually teach as an instructor, not a helper.
=> Clarify declaration in TrainingRequestForm

workshops/templates/account/login.html
Login page was restyled so that the GitHub login button is placed
next to the form with a world "OR" in bold between them.
This highlights that users can use one or the other to actually sign in.
=> Restyle login page so that GitHub login button is next to the login form

.travis.yml
Explanation how it works: if you run `makemigrations` with `-e` flag, `1` is returned when there are no changes and `0` when there are missing migrations.
~~Unfortunately, I couldn't test if this PR works.~~ This PR works. This PR have no missing migrations and passed. #884 has missing migrations and failed.
=> Check for missing migrations in Travis CI

workshops/test/test_person.py, workshops/views.py
The redirect in `finally` clause was executed even when an non-`GithubException` (like `IntegrityError`) was raised. This hid the error. Now it results in loud error.
=> Reveal IntegrityError raised in sync_usersocialauth view

.travis.yml
Reduction of build time from 188 seconds to 96 seconds (**2x speedup**).
This works. Compare [the first build](https://travis-ci.org/swcarpentry/amy/builds/143161913) of this PR with [the second one](https://travis-ci.org/swcarpentry/amy/builds/143163940).
=> Speedup Travis builds by caching pip directory

amy/settings.py, pydata/__init__.py, pydata/apps.py, pydata/checks.py, pydata/fixtures/workshops_role.json, pydata/static/import_person.js, pydata/static/import_sponsor.js, pydata/static/import_task.js, pydata/templates/pydata/person_create_form.html, pydata/templates/pydata/person_import_modal.html, pydata/templates/pydata/sponsor_import_modal.html, pydata/templates/pydata/task_create_form.html, pydata/templates/pydata/task_import_modal.html, pydata/templates/workshops/event.html, pydata/templates/workshops/event_edit_form.html, pydata/urls.py, pydata/views.py, requirements.txt, workshops/templates/workshops/event.html, workshops/templates/workshops/event_edit_form.html
Since all imports build incrementally on each other, I decided to club them together in one PR. (I get lost easily otherwise too)
I will rewrite the git history after the final approval. Rewriting git history after every suggestion hides the previous conversation, something that I hate.
Since I haven't yet hosted a PyData conf. site with an API over it, I am bundling the API responses.
```
GET /api/
{
"title": "PyData",
"start_date": "2040-01-01",
"end_date": "2040-01-04"
}
```
```
GET /api/speaker/1/
{
"username": "admin",
"name": "admin",
"email": "admin@pydata.org"
}
```
```
GET /api/presentation/1/
{
"slot": {
"day": "2016-06-14",
"kind": "Test",
"name": "2016-06-14 Test (09:55:44 - 00:00:00) ",
"start": "09:55:44",
"end": null
},
"section": "PyData General Sessions",
"speaker": { …
```
=> Import event person task

api/test/test_reports.py, api/views.py
When using CSV/YAML renderers in API, one view was prone to error because it contained a non-representable values (ie. `ValuesQuerySet`). This PR fixes the bug by using `listify()` on the vulnerable entries.
=> Fix API error with embedded iterator

workshops/github_auth.py, workshops/models.py, workshops/test/test_person.py
When `Person.github` is changed, all `UserSocialAuth` records associated with that person are now deleted.
=> Fix #891 -- UserSocialAuth cache got out of sync

workshops/forms.py, workshops/static/date_yyyymmdd.js, workshops/static/update_from_url.js
The JavaScript `Date` object was extended with a prototype function
`yyymmdd` (adapted from http://stackoverflow.com/a/3067896) to display
zeros before month and day number when they consist of single digits.
=> Fix #834 with a function for YYYY-MM-DD dates formatting

workshops/templates/workshops/all_trainees.html
During working on #871, I've accidentally included a piece of HTML to test bootstrap alerts.
Patching my own code 20 minutes after the release. :-(
=> Delete experimental code from all_trainees.html

workshops/forms.py, workshops/test/test_training_request.py
It wasn't possible to "accept & match to selected trainee account", because validation on the model was triggered. `TrainingRequest` requires that there is no matched person when the state is "pending", while the form, as submitted, has a trainee chosen.
Fixed by disabling model validation.
=> Fix bug when accepting training request

.gitignore, amy/settings.py, api/test/base.py, api/test/test_api_structure.py, api/test/test_events.py, api/test/test_export.py, api/test/test_reports.py, workshops/test/base.py, workshops/test/test_util.py
This PR introduces two improvements:
1. Use in-file database instead of in-memory one while running tests with `--keepdb`. This change lets us preserve database between test launches and, therefore, avoid the overhead of applying migrations during each test launch. Note that a new fresh in-memory database is still used by default, that is when you don't set `--keepdb` flag (i.e. `python3 manage.py test`).
2. `TestCase.subTest` cannot be used when tests are launched in parallel, that is with `--parallel` flag. To bypass this limitation, we use a dummy `subTest` mock when when tests are run in parallel.
The first improvement saves 30 seconds on my machine once the database is created. All test suite takes now 50 seconds instead of 80 seconds.
The second improvement in combination with the …
=> Speeding up tests with --keepdb and --parallel

workshops/templates/workshops/event.html, workshops/templates/workshops/instructors_by_date.html, workshops/templates/workshops/workshop_staff.html
In a few places, there were links with href=`mailto:bunch,of,emails` instead of `mailto:?bcc=bunch,of,emails`. Those email addresses ended up in "To" field instead of "BCC" (blind copy), resulting in recipients seeing other recipients' email addresses.
=> Fix #907 -- leakage of email addresses in "bulk email" buttons

workshops/models.py, workshops/test/test_event.py
This fixes #977.
The reason for this issue is: when using Q(tags__name="asd") on events
with multiple tags, they may be counted as N separate objects, where N
is equal to the number of tags.
=> Fix double display of (un)published events

workshops/test/test_issues.py, workshops/views.py
This fixes #936.
Actually the fix removes unresponsive workshops only from the attendance
part of report from "Workshop issues" page.
=> Remove unresponsive workshops from workshop issues

workshops/forms.py, workshops/test/test_autoupdate_profile.py, workshops/test/test_dc_selforganized_event_requests.py, workshops/test/test_event_requests.py, workshops/test/test_event_submissions.py, workshops/test/test_profile_update_request.py, workshops/test/test_training_request.py
This fixes #792 by adding a separate field (via a mixin) to multiple
forms that should ask the user for a privacy policy agreement.
This approach doesn't store any additional data in the DB, but forces
user to agree on the privacy policy instead. Such behavior may not be
desired (ie. do we by default assume everyone already in the database
agreed on that policy?).
=> Add privacy consent field to multiple forms

workshops/templates/workshops/airport.html, workshops/test/test_airport.py
This fixes #1008.
The error was: template used
`{% url 'airport_details' iata=airport.iata %}`
instead of
`{% url 'airport_details' airport_iata=airport.iata %}`
which caused 500 on every airport details page.
=> Airport details page: fix wrong URL param causing 500

pydata/forms.py, workshops/forms.py
- Renames red 'Reset' button to white 'Cancel' button
- Redirects to the last page in history
Fixes #984
However, if there is no browser history, the button does nothing.
=> Change the 'Reset' button to 'Cancel' button

workshops/test/test_person.py
Modify two tests (one for SWC and one for DC) to cover the following
scenario:
- add a "SWC/DC Homework" training progress record for Person XYZ that
they failed.
- then add "SWC/DC Homework" training progress record for the same person
that they passed (because they did a second demo and it worked).
- now "SWC/DC Homework" should be not listed in the list of missing
SWC/DC requirements
Ref discussion on amy-dev mailing list:
http://lists.software-carpentry.org/pipermail/amy-dev/2016-September/000170.html
=> Add test for instructor badge eligibility

requirements.txt, workshops/forms.py, workshops/templates/navigation_fixed.html, workshops/templates/workshops/all_trainees.html, workshops/test/base.py, workshops/test/test_person.py, workshops/util.py, workshops/views.py
"SWC" and "DC" labels in "eligible" column in trainees list view are
now clickable when a person is eligible to become SWC/DC instructor, but
doesn't have a swc/dc-instructor badge yet. The user is moved to person
edit view where the badge can be awarded.
=> Fix #981 -- add more ways to issue a badge

amy/settings.py, amy/urls.py, requirements.txt
The toolbar is enabled only when `DEBUG == True`. By default, almost all its functionality is disabled in order not to slow down page reloads. They can be turned on using checkboxes in the toolbox. The only one functionality that is turned on is "timing panel" that shows how long it took to process the last request.
The most useful feature of the toolbar is SQL panel which shows how many queries have been executed and how long did they take. It's important to track how long they execute to ensure that AMY scales up with growing database. In addition, it's much easier to make performance experiments now.
=> Install django debug toolbar

amy/settings.py
=> Fix #1045 -- enable SQL panel in Django Debug Toolbar by default

api/serializers.py, api/test/test_reports.py, api/views.py
This:
```python
qs = Person.objects.filter(badges__in=badges)  \
.annotate(date=Min('award__awarded'),
count=Value(1,
output_field=IntegerField())) \
.order_by('date')
```
~~results in this SQL:~~
```SQL
SELECT ••• FROM "workshops_person" 
INNER JOIN "workshops_award" 
ON ("workshops_person"."id" = "workshops_award"."person_id") 
WHERE "workshops_award"."badge_id" IN (
SELECT ••• FROM "workshops_badge" U0 
WHERE U0."name" IN ('''dc-instructor''', '''swc-instructor''')) 
GROUP BY "workshops_person".•••
ORDER BY "date" ASC
```
@pbanaszkiewicz could you confirm that this counts in correct way?
@edit:
The SQL query is actually:
```SQL
SELECT workshop_person.•••, 
MIN("workshops_award"."awarded") AS "date", 
'1' AS count
FROM "workshops_person" 
INNER JOIN "workshops_award" 
ON …
```
=> Fix #978 -- remove double-counting in display of instructor counts

amy/settings.py
From Django official docs:
> Changed in Django 1.10.3:
> In older versions, ALLOWED_HOSTS wasn’t checked if DEBUG=True.
> This was also changed in Django 1.9.11 and 1.8.16 to prevent a DNS rebinding attack.
=> Allow requests from localhost while in DEBUG mode.

.travis.yml, amy/settings.py, amy/urls.py, docs/PyData_deploy.md, pydata/apps.py, pydata/checks.py, workshops/test/test_sponsorship.py
PR created to test whether Travis creates multiple jobs.
=> Test pydata application

requirements.txt, workshops/base_views.py, workshops/templates/workshops/organization.html, workshops/templates/workshops/training_progresses_inline.html, workshops/test/test_training_progress.py, workshops/urls.py, workshops/views.py
Changes:
1. Adds a `PrepopulationSupportMixin` view.
The mixin prepopulates and disables fields based on GET parameters.
2. Refactor `MembershipCreate` view to use `PrepopulationSupportMixin`
@pbanaszkiewicz @chrismedrela please review.
=> Refactor views to allow better form prepopulation.

extforms/views.py
`django.contrib.messages` was missing which caused the error when
someone submitted their form. The error thankfully didn't prevent data
from saving to the database.
The error was caused because I did not check the source code for missing
imports (new machine, no linter installed). This is now fixed.
=> Fix: missing import in extforms

amy/settings.py
I like to test AMY on local machine on production data. That means, that I need to change `DATABASES['default']['NAME']` setting very often (i.e. every time I switch branches).
This PR let you overwrite the default (`db.sqlite3`) with whatever you put in `DB_NAME` env var. But only if `DEBUG is True` to prevent surprises on production.
=> Make database filename customizable via environment variables

docs/releases/README.md, docs/releases/TEMPLATE.md, docs/releases/v0.9.1.md, docs/releases/v0.9.2.md, docs/releases/v0.9.5.md, docs/releases/v0.9.6.md, docs/releases/v0.9.7.md, docs/releases/v1.0.0.md, docs/releases/v1.1.0.md, docs/releases/v1.2.0.md, docs/releases/v1.2.1_v1.3.0.md, docs/releases/v1.3.1.md, docs/releases/v1.3.2.md, docs/releases/v1.4.0.md, docs/releases/v1.5.0.md, docs/releases/v1.5.1.md, docs/releases/v1.5.2.md, docs/releases/v1.5.3.md, docs/releases/v1.5.4.md, docs/releases/v1.6.0.md, docs/releases/v1.6.1.md, docs/releases/v1.6.2.md, docs/releases/v1.7.0.md, docs/releases/v1.7.1.md, docs/releases/v1.7.2.md, docs/releases/v1.8.0.md, docs/releases/v1.9.1.md, extforms/views.py
This fixes #1082 by backporting release notes from my blog.
I decided to switch from "I" to "[Piotr](https://github.com/pbanaszkiewicz)", and to remove most of the personal stuff. I also tried to arrange all release notes in specific template (which was not always possible).
We're losing timestamps with this approach. I'm not sure if we need them. Maybe you could vote for having them? And point for a way to add them to the template?
=> Backporting release notes

workshops/templates/workshops/person_bulk_add_results.html, workshops/test/test_bulk_add.py, workshops/urls.py, workshops/util.py, workshops/views.py
This PR fixes #1000 and #1015 (in one of the commits).
88c3e1e, c0ecdfa, e28c85e and fa96e0e are cleaning up and / or fixing small bugs. Other commits change the workflow for bulk-upload (slightly). Some parts, like magic-matching or showing if `personal` or `family` is different in DB/uploaded file, were removed; it looks like we ended up with slightly more maintainable code.
=> Bulk upload: fix #1000 ("use that person") and #1015 (list of roles)

workshops/templates/navigation_fixed.html, workshops/test/test_search.py, workshops/views.py
Since this is a purely GET (no side effects) page, we don't need
the CSRF protection, and it will look better in the address bar.
This commit fixes #1069, and also provides working tests against
that search page.
=> Search: switch to GET, disable CSRF protection

workshops/templates/workshops/trainingprogress_form.html, workshops/test/test_training_progress.py, workshops/views.py
`delete-form` now submits to the delete view of the object.
Fixes #1085
=> Fix the delete button on the TrainingProgressUpdate view.

workshops/forms.py, workshops/static/css/amy.css
This fixes #898 by:
* changing default size of "Tags" field on Event add/edit forms to 10
(the current number of tags in the database),
* adding "resize: vertical" option to CSS3 for <select> tags; therefore
making any <select> resizable in vertical if user wants to just see
more of the options.
=> Event form tags: bigger list; resizable <select>s

workshops/models.py
=> Fix #1110 -- hide cancelled workshops from uninvoiced events in dashboard

workshops/templates/workshops/admin_dashboard.html, workshops/views.py
On a test person (@gvwilson) profile pages get to ~20 queries from >220.
Similarly dashboard is now O(const) instead of O(n) due to annotation of `num_instructors`.
=> Speed up person details & update, and admin dashboard pages

amy/settings.py, requirements.txt
`django_extensions` provide `shell_plus --notebook` command that open jupyter notebook in a browser, which is IMO much more convenient than command line shell.
=> Install django_extensions

workshops/templates/workshops/all_trainees.html, workshops/templates/workshops/all_trainingrequests.html, workshops/views.py
So that it always results in constant number of queries (16) and all queries execute in 500 ms with debug toolbar enabled (which makes everything much, much slower).
@narayanaditya95 or @pbanaszkiewicz please review.
=> Fix #1047 -- optimize SQL queries on trainees list view

workshops/test/test_person.py, workshops/views.py
Non-superuser admins with 'change_person' permission could not edit other people, because the person edit view required 'edit_person' permission instead of 'change_person'.
Fixes #1185.
=> Fix #1185 -- correct permission codename

workshops/static/amy_utils.js
Fixes #1154.
When you entered an invalid vaue into an autocomplete field (so that the field is red) and submit the form, invalid value is ignored and NULL was saved. No warning was displayed. This was confusing.
This commit prevents form submission if there is an invalid value in any autocomplete field. On top of that, the invalid field is focused on form submission.
There is no regression test, because we don't have end-to-end tests with javascript support (like Selenium).
=> Fix #1154 -- autocomplete fields no longer ignore invalid values

workshops/forms.py, workshops/templates/workshops/trainee_dashboard.html, workshops/views.py
1. Added list of workshops user taught at (trainee-dashboard)
2. Added ORCID and occupation fields to the form (autoupdate_profile)
The workshop listed in the `trainee-dashboard` consists only of workshops names, they aren't links to workshop pages.
=> Trainee dashboard enhancements

workshops/test/test_training_request.py, workshops/views.py
This fixes #1225 by adding a timestamp column to CSV export of training
requests.
=> Export "created-on" field for training requests

workshops/test/test_profile_update_request.py, workshops/views.py
When updating persons via profile update form there was a chance
for database constraint violations (non-unique usernames, GitHub
usernames or Twitter usernames).
This PR fixes #1237 and its multiple issues:
* when new person is being added via profile update, they now have
username generated (previously it was blank which caused errors),
* both new person and update to existing person are checked for
integrity (DB) errors,
* it's all contained in a transaction.
=> Fix profile update request accept (#1237)

workshops/test/test_event.py, workshops/util.py
Bug: with new addition in v1.11.3, the merging function was extended
to help with uniqueness errors (by removing related objects).
Unfortunately this caused a bug that removed one tag from AMY when an
admin decided to merge two events.
Fix: new code tries to use `.clear` if possible (for clearing M2M
relations), if it can't - then uses `.remove`.
=> Repair M2M merging bug that removed `SWC` tag from AMY

api/test/test_export.py, api/views.py
This PR includes a number of commits that fix various things that were wrong with `export-instructors` API endpoint.
=> Fix double instructors in API

workshops/static/amy_utils.js
This fixes #1255. The error was: due to some JS error, the browser
was unable to continue using the script, which further disabled
Select2 code.
=> Fix Select2 widget not being loaded

workshops/test/test_workshop_staff_searching.py, workshops/views.py
This fixes #804  by changing the query there:
instead of filtering events with 'TTT' tag but without 'stalled' tag,
the query now looks for events tagged 'TTT' but not 'stalled'. The big
difference here is that previously people who participated in
`TTT-stalled` AND `TTT` events where omitted in search reasults, now
they're not.
The tests were adjusted: now only one test case looks for a complicated
case search results.
EDIT: wrong issue number.
=> Fix workshop staff searching bug

workshops/templates/workshops/event_import_update_from_url.html
This fixes #1169 by making sure the issue mentioned in
[here](https://github.com/swcarpentry/amy/issues/1169#issuecomment-290912257)
is not present anymore.
Additionally a confusing help text from import/update modal was removed,
and "Update" button was changed to "Import" on import modal (it's still
"Update" on update modal).
=> Fixing inconsistencies when importing/updating events from URL

workshops/templates/base_nav_fixed.html, workshops/templates/navigation_trainee_fixed.html, workshops/templates/workshops/autoupdate_profile.html, workshops/templates/workshops/trainee_dashboard.html, workshops/templates/workshops/training_progress.html, workshops/test/test_security.py, workshops/test/test_trainee_dashboard.py, workshops/urls.py, workshops/views.py
This PR fixes #1274 by adding an altered top navigation bar to some views accessible by trainees:
* `trainee-dashboard`
* `training-progress` (new view split from `trainee-dashboard`)
* `autoupdate_profile`.
Additionally if the user is logged in, and not an admin, they will be displayed a navigation bar in externally accessible forms. Admins are still displayed "their" navbar in these pages.
Password changing form is now accessible for logged-in users who aren't admins.
=> Navigation bar for trainee accessible views

workshops/templates/workshops/event_edit_form.html
This fixes #943 by moving task notes (that may include event instructor
or helper names) closer to the tasks form (used to add instructor and
helper roles to the event).
=> Add event notes on tasks tab pane in event edit view

workshops/models.py, workshops/templates/workshops/admin_dashboard.html, workshops/test/test_landing_page.py, workshops/views.py
This PR changes some things on admin dashboard:
1. the workshop tag (SWC/DC/LC) is not in its own column, but they're all in the same column in "Current events" (see screenshot)
2. "Uninvoiced" events is hidden
3. "Unpublished" events have a different conditions now:
a. any event that's not "unresponsive", "stalled", "cancelled" or marked as "complete"
b. and has no known start date, or country, or venue, or address, or lat/lng, or URL.
=> Small improvements to admin dashboard

workshops/templates/workshops/person.html, workshops/test/test_person.py
This fixes #1288.
Changes:
* moved all data previously displayed in columns into a single table
* moved person-supplied data (like knowledge domains, lessons or languages)
up in the table so that they're with other supplied data (ORCID etc.)
* added training requests list
By person-supplied data I understand data coming from auto-profile-update
form or from instructor profile update form.
=> Change person details view layout

workshops/templates/workshops/person_bulk_add_results.html, workshops/test/test_bulk_add.py, workshops/urls.py, workshops/util.py, workshops/views.py
This PR provides:
1. a couple of style, text or function documentation changes
2. a sort-of fix for #1216 (more on that below)
3. a fix for #1215 
Changes in bulk-upload:
1. when first uploaded, entries from CSV are matched against people in the database; as long as the entries are correct, there's no need to go manually through the table and click "match with selected person" for each entry - this is easier and faster to implement than what was proposed in #1216, but I hope it's good enough
2. when someone is matched, they can be later unmatched (#1215)
=> Bulk upload - a couple of fixes

pydata/templates/pydata/person_create_form.html, workshops/fields.py, workshops/forms.py, workshops/templates/base.html, workshops/templates/forms/event_submit.html, workshops/templates/forms/profileupdate.html, workshops/templates/forms/trainingrequest.html, workshops/templates/forms/workshop_swc_request.html, workshops/templates/workshops/autoupdate_profile.html, workshops/templates/workshops/event.html, workshops/templates/workshops/event_create_form.html, workshops/templates/workshops/event_edit_form.html, workshops/templates/workshops/generic_form.html, workshops/templates/workshops/person_edit_form.html, workshops/templates/workshops/todos_add.html, workshops/templates/workshops/trainingprogress_form.html, workshops/templates/workshops/workshop_staff.html
This fixes #1330. Again. :-)
So the issue, after I figured it out, quite simple: multiple things tried to include jQuery; some of those things were causing errors, that prevented further JS code from executing.
What tried to include jQuery?
1. we tried in our general JS import block (using django compressor)
2. forms using select2 widgets tried via widgets' `media` properties
3. Django Crispy Forms default behavior was to automatically render `media` in HTML
4. we tried to render `media` on our own in our own templates
A number of steps were taken to fix this situation:
1. jQuery import was moved from bottom of `<body>` to `<head>`
2. Select2 widgets from DAL were overwritten so that they don't try to include jQuery
3. Forms media renderings were removed from templates
4. Django Crispy …
=> JS code breaks in `extrajs`

api/filters.py, workshops/models.py
This fixes #1351. The error was cryptic and well-hidden, but I narrowed
it to ill-made filter for tags.
Probably the idea was to allow people put in exact tag names, but now
it's easy to do with Django Filter options.
=> Events API: Fix 500-error when filtering

api/renderers.py, api/serializers.py, api/test/test_trainingrequests.py, api/views.py, workshops/forms.py, workshops/models.py, workshops/static/amy_utils.js, workshops/templates/navigation.html, workshops/templates/workshops/all_trainingrequests.html, workshops/templates/workshops/trainingrequest_bulk_upload_manual_score_confirmation.html, workshops/templates/workshops/trainingrequest_bulk_upload_manual_score_form.html, workshops/test/test_bulk_manual_score.py, workshops/urls.py, workshops/util.py, workshops/views.py
@karenword @ErinBecker here's snapshot of the new "Download for manual scoring" button group:
The same selected requests that you can see in the screenshot generate this CSV (zipped because GitHub):
[two_results.zip](https://github.com/swcarpentry/amy/files/2475843/two_results.zip)
Uploading this CSV file without any changes on the Bulk Upload page gives this result:
I didn't implement inline editing, like in bulk add persons, therefore in case of errors the user would have to fix the file and re-upload.
Please tell me what you think - e.g. if there's something wrong with the CSV.
=> Bulk upload training request manual score

requirements.txt
I'm reverting the recent dependency upgrade #1245  on Django-Autocomplete-Light - it makes widgets buggy on AMY.
=> Revert Django-Autocomplete-Light due to buggy widget display

workshops/filters.py
Bug #1: filter method name was doubled (ie. there were two filter
methods named this way in code).
Bug #2: filter logic was to narrow searches to dates outside of
[start, end] range (so like... `]start, end[` ). This was fixed as well.
// edit: forgot to mention this fixes #1379 .
=> Memberships filter: fix bug in filter method name & logic

workshops/forms.py, workshops/templates/bootstrap4/whole_uni_form.html
This fixes #1369. This feature was present in AMY v1.x, but was removed when we switched to Bootstrap4.
Forms with buttons additionally placed on top:
* `EventForm` - for workshop create & update pages, //edit: also for "Accept & create event" pages
* `PersonForm` - for person create & update pages
* `OrganizationForm` - for organization create & update pages
* various EventRequest forms - for SWC/DC Event Request update, but not for externally available (to unauthorized users)
* `TrainingRequestUpdateForm` - for updating training requests
* `TrainingProgressForm` - for creating/updating training progresses
=> Submit buttons on form tops

workshops/templates/workshops/all_trainingrequests.html
This fixes #1383.
Changes:
1. Group column is no longer conditionally displayed.
2. Affiliation column is no longer conditionally displayed.
3. Location is kept conditionally (whenever someone searches for location) displayed (there's little screen estate to display this column unconditionally).
4. Request's email is alternatively used for contacting when no person is matched to the request.
=> Training Requests list refinements

amy/settings.py, extforms/views.py, workshops/base_views.py, workshops/test/test_util.py, workshops/test/test_workshop_requests.py, workshops/util.py
This PR fixes #1368 and #1367.
New workshop request notifications will go to various addresses, depending on the country provided by the user.
// edit: addresses (or rather matching criteria) are hardcoded, but in a way that should be simple to universalize in a future, if needed. The `Criterium` object can easily be translated to a database model.
=> Admin notifications propagation to various emails

api/views.py
The addition of `distinct()` prevents API from showing more than one
result for people who match a number of criteria simultaneously.
This fixes #1395.
=> Fix PersonViewSet queryset to include only distinct results

amy/workshops/tests/test_bulk_add.py, amy/workshops/util.py
This fixes #1394 by catching `Person.MultipleObjectsReturned` when,
after CSV parsing, empty emails end up as `None`s and cause unhandled
exception for this query:
```python
Person.objects.get(email=email)
```
=> Fix bulk upload server error

amy/workshops/migrations/0097_auto_20160519_0739.py, amy/workshops/migrations/0139_fix_language_names.py
`open(filename)` used default system encoding, but it turns out some systems don't use `utf-8` by default :disappointed:
=> Force encoding for languages registry (used in migrations)

.travis.yml, config/settings.py
This PR enhances Travis-CI testing and enables loading two setting parameters from environment: `SITE_URL` and `ALLOWED_HOSTS`. This is required for #1392 and #917.
=> Deployment automation: prepare

amy/workshops/tests/test_security.py, amy/workshops/urls.py, config/urls.py
This fixes #1423 by adding redirects from old architecture addresses to
new architecture addresses. Mostly the URLs were switched from
a `workshops` application namespace to a new application namespace. The
redirects are placed in top-most `urls.py`.
Additionally redirects for old external forms were moved from
`workshops.urls` to top-most `urls.py`.
The same redirects were removed from tests opt-out, since we handle
redirect views in the tests separately.
=> Redirect from old URLs to new ones

amy/workshops/tests/test_workshop_staff_searching.py, amy/workshops/views.py
This fixes #1421 by generating `badge1 OR badge2 OR ...` instead of
`badge1 AND badge2 AND ...`.
The tests were adjusted properly.
=> Don't conjoin badges in Find Workshop Staff

amy/fiscal/forms.py, amy/fiscal/tests/test_membership.py
The error occured because custom `MembershipForm.save` method was
triggering Django comment signal, but there was no `comment` field to
attach to this signal.
The method was moved to `MembershipCreateForm`, where `comment` is
present.
A regression test was added.
=> Fix #1437: MembershipForm triggering comment creation w/o comment field

.travis.yml
Solution:
https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
I may consider switching entirely to Python v3.7, because it supports ["on-the-fly" SQLite backups](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.backup). Or we switch to PostgreSQL.
=> Update Travis config to work with Python 3.7

.travis.yml
It was using this command:
./manage.py makemigrations --dry-run -e
which doesn't recognize `-e` parameter. That parameter was changed to
`--check` and the command now works.
This fixes #1451.
=> Travis: fix broken migration testing command

amy/templates/workshops/search.html, amy/workshops/forms.py, amy/workshops/tests/test_search.py, amy/workshops/views.py
This fixes #1442. Comments found are displayed in new far-right column. Links redirect to specific comments within corresponding objects.
=> Search in comments

amy/extrequests/forms.py, amy/extrequests/tests/test_training_request.py, amy/extrequests/views.py, amy/static/checkboxes_sessionstorage.js, amy/templates/base.html, amy/templates/requests/all_trainingrequests.html
This fixes #1375.
Big changes (exclusive to All Training Requests page only):
1. switch to Datatables
2. no more pagination - it's now all handled by Datatables
3. filtering on the left hand side narrows data for the table, but the table can be sorted, paged, and even filtered even further by the Datatables script
4. table sorting/pagination/filtering is preserved in the browser
5. selected checkboxes are preserved in the browser
6. action buttons under the table are split into 3 categories: action (they don't change data, but instead allow you to work on the data [e.g. email, download CSV, etc]), modification (they modify the data), acceptance & match (advanced modification with parameters).
@karenword this should work and help you with your workflow, however be aware there may still be …
=> Revamping All Training Requests page with Datatables and saved checkboxes

amy/workshops/action_required.py, amy/workshops/tests/test_action_required.py, amy/workshops/views.py
This fixes #1463.
Changes in `action_required_policy` view:
* setting `?next` query parameter in the middleware
* adhering to the `?next` query parameter by `action_required_view`
* throwing Http 404 error when view accessed by user who already agreed on the policy
=> Action required next page

amy/templates/navigation.html, config/settings.py, config/urls.py
For security purposes, Django Admin URL, until now accessible under `admin/` link, will be moved to a long and random URL.
This PR includes changes in `settings.py` and `urls.py` that enable this kind of operation. Additionally, a link visible only to superusers is added to the navigation bar.
=> Django Admin URL parametrized

amy/templates/base.html
There are some issues on the main production server that can only be
resolved, for the countless time, by changing how jQuery is imported.
This time the change is to move main jQuery import from `<head>` to top
of `<body>`, and to move all other imports from bottom of the `<body>`
to the top.
=> Change place where jQuery is included in base.html

config/settings.py, requirements.txt
This gets rid of "source map" errors in browsers.
Source maps are stored as comments inside source CSS files, but when
we enable compression, the comments aren't preserved, and so the issue
is gone.
=> Django compressor: compress CSS files

Makefile
This fixes #1474.
Some potential issues:
1. `make superuser` would create a superuser, and there was nothing to prevent that from happening even on production server; it was changed so that only `dev_database` creates this user.
2. `make dev_database` was removing `db.sqlite3` without warning. Now it requires user to remove it first.
3. `make upgrade` was changing `yarn.lock` file, but I'd rather stick to the values from the file.
=> Makefile: fix some potentially risky commands

amy/templates/dashboard/training_progress.html
This fixes #1464 by adding a requested note to the training progress
page of the trainee dashboard.
@maneesha this is how it looks:
=> Training progress note in trainee dashboard

amy/workshops/tests/test_util.py, amy/workshops/util.py
This fixes #1461 by extending AMY parsing capabilities to accept separate "lat" and "lng" tags.
This opens a way for workshop templates to accept split coordinates (https://github.com/carpentries/workshop-template/issues/582).
=> Split workshop tag "latlng" into two tags "lat" and "lng"

.gitignore, amy/workshops/signals.py, config/settings.py
This fixes #1499 by enhancing logging + reacting upon `user_failed_login` signal sent from `django.contrib.auth`.
A new envvar `AMY_SERVER_LOGFILE` is used for log file name.
=> Log failed login attempt

config/settings.py
looking at the logs of Mailgun I noticed that notifications to this address bounce because it doesn't exist. `sysadmin@carpentries.org` does exist though but I'm not 100% sure we want to go there because I'm not sure the kind of emails that end up being sent to this address.
=> fix email address for sysadmin

amy/templates/base.html
There may be other places that we also need to update the GH  name.
=> change GH link swcarpentry > carpentries

docs/procedures.md
This fixes #1535 by correcting the link in `procedures.md` (it was
pointing to the old repository).
=> Update repository links in procedures.md

amy/templates/requests/all_selforganisedsubmissions.html, amy/templates/requests/all_workshopinquiries.html
This fixes #1536 by adding missing pagination on these pages.
The pagination template tag used wrong variable name, therefore was
unable to render.
=> Add missing pagination on All Workshop Inquiries and Self-Organised Submissions

amy/extrequests/views.py
This fixes #1539 by updating wrong permission codenames in
`extrequests.views`.
The wrong codenames contained `workshops` as the application, whereas
`extrequests` was correct.
=> Fix wrong permissions in `extrequests.views`

config/settings.py
This potentially fixes #1538 (I'm still waiting for user test results).
The potential cause for this error was no cache table (no cache at all
was set up), so the Django-select2 AutoResponseView was unable to find
a correct widget by `field_id` GET parameter.
https://github.com/applegrew/django-select2/blob/master/django_select2/views.py#L82
=> Enable cache

amy/api/renderers.py, amy/api/serializers.py, amy/api/tests/test_export.py, amy/api/tests/test_trainingrequests.py
This fixes #1540. The CSV serializers were extended with one additional
column (`review_process` - Application Type). Tests were adjusted.
=> Add 'review_process' to CSV download of Training Requests data

amy/templates/requests/selforganisedsubmission.html, amy/templates/requests/workshopinquiry.html
This fixes #1551. The invalid permissions were replaced by valid onces.
The error affected only action widget in Self-Organised Submission
and Workshop Inquiry details pages.
=> Fix invalid permission passed to action widget

amy/templates/requests/selforganisedsubmission.html, amy/templates/requests/workshopinquiry.html
This fixes #1550 by changing the wrong links to proper ones:
* `selforganisedsubmission_assign` for Self-Organised Submission
* `workshopinquiry_assign` for Workshop Inquiry.
=> Fix assignment link in SelfOrgSubmission and WorkshopInquiry

amy/workshops/forms.py, amy/workshops/tests/test_event.py
Previously we were using name of the curriculum (split by "-"). Now we
can use curriculum.carpentry value, which corresponds to Tag name,
unless it's mix&match -> then tag name is "Circuits". And this is what
the method now does.
A new test case was added to ensure this mechanism is working correctly
with Mix&Match curriculum.
This fixes #1554.
=> EventForm: build expected tags in clean_curricula differently

amy/extrequests/views.py
This fixes #1581 by updating the name: `change_workshopinquiry` -> `change_workshopinquiryrequest`.
=> Fix change_workshopinquiry permission name

requirements.txt
This update fixes potential account hijack. See below for details:
https://docs.djangoproject.com/en/3.0/releases/2.2.9/
The production server was already updated with newer Django.
=> Update to Django v2.2.9

amy/static/css/amy.css, amy/templates/workshops/all_persons.html, amy/templates/workshops/event.html, amy/templates/workshops/workshop_staff.html, amy/workshops/models.py, amy/workshops/tests/test_workshop_staff_searching.py, amy/workshops/views.py
Three templates:
* all persons
* event details
* workshop staff searching
were changed. The column that showed instructor badges in all three templates was replaced with unified column showing instructor badges and a trainer badge.
This fixes #1549.
=> Trainer badge in badge column on all persons / event details / workshop staff pages

amy/templates/account/base.html, amy/templates/account/login.html
This fixes #1522.
The changes:
* more break points in accounts/base.html (for extra large `xl` we set
page width to 6 columns, for large `lg`: 9 columns, for small `sm`:
10 columns, for extra small [no prefix]: 12 columns)
* different columns in login page (left column: login form, center column:
word "OR", right column: login with GitHub) and they have different
widths depending on display size (on extra small [no prefix] all
columns have 12col width, which is the widest, and on medium or
higher `md`: 5 cols, the rest, 5 cols).
=> Enable responsiveness on login page

config/settings.py, requirements.txt
Fixes #1598.
Due to cache settings change, Django-Compressor started using DB-based cache. Since the default database, SQLite, is pretty terrible, that change resulted in very poor performance.
This PR switches cache backend used by Django-Compressor back to `LocMemCache`, which despite its shortcomings should result in good performance.
=> Django-Compressor performance upgrade

amy/extrequests/views.py
Permissions for that view were wrong- used the old name
(without "request" part).
=> Update WorkshopInquiryRequest's assignment view

amy/api/urls.py, amy/workshops/util.py, requirements.txt
Upgraded dependencies:
* django-filter 2.0.0 -> 2.2.0
* djangorestframework 3.8.2 -> 3.9.4
* social-auth-code 1.7.0 -> 3.2.0
* social-auth-app-django 2.1.0 -> 3.1.0
* django-extensions 2.1.3 -> 2.2.5
* Markdown 3.0.1 -> 3.1.1
This commit also contains important security change in PyYAML loader.
PyYAML was recently upgraded from 3.x to 5.1.
See more info at https://msg.pyyaml.org/load
=> Upgrade some dependencies due to deprecation warnings in old versions

amy/extforms/tests/test_training_request_form.py, amy/templates/includes/trainingrequest_details.html, amy/templates/mailing/training_request.html, amy/templates/mailing/training_request.txt, amy/templates/requests/trainingrequest.html, amy/workshops/management/commands/fake_database.py
This fixes #1422 by adding a table with data entered by a sender.
This is very similar to how other 3 workshop request forms work:
* a general-purpose table details template is available
* it's used for admin display (it changes slightly)
* it's also used for HTML email content
* finally a manually trimmered version is used for bare (text) email.
=> Send form copy to Training Request applicant

amy/templates/dashboard/trainee_dashboard.html
Based on suggestion from @Talishask  , this PR adds a link to the trainee dashboard view so they can submit a self organised workshop directly from that view if they see something missing.  Here's a snapshot of what it will look like:
=> add link to submit self org wkshp

amy/templates/dashboard/trainee_dashboard.html
This adds help text explaining how the two different email fields are used.
=> add help text to both email fields

amy/extforms/views.py
This is required to generate proper context to the autoresponder email template.
=> Training Request form: Add missing email context

amy/workshops/forms.py, amy/workshops/tests/test_event.py
This fixes #1608 bug: if empty `manual_attendance` is supplied,
it defaults to zero instead of None, which was causing DB error.
=> Fix empty manual_attendance bug

amy/extrequests/tests/test_training_request.py, amy/extrequests/views.py
During matching Training Request with existing person in database,
this person's details are updated from the Request.
It may happen that there's a conflict in our DB. For example,
a duplicate person with the same email as in the Training Request.
In this case the rewriting of person's data will trigger
IntegrityError, and before this commit it wasn't in a transaction
and could result in 500 Server Error.
=> Non-transactional DB error when matching Training Request with existing Person

docker-compose.yml
This solves the recent problem with no permissions for redis
to write to the `/data` on its container.
=> Redis: use persistent storage

amy/extrequests/tests/test_training_request.py, amy/extrequests/views.py
This extends searching for matching person with additional criterium
for TrainingRequest's secondary email matching either persons
primary or secondary email.
If the TrainingRequest doesn't specify secondary email, the criterium
is left blank.
This fixes #1618.
=> Match TrainingReq. with person on secondary email

amy/templates/forms/selforganised_submission.html, amy/templates/forms/workshop_landing.html
Text about self organised workshops made it sound like only a certified instructor or a member site could submit this form.  This clarifies the language to note you must be connected with a certified Instructor who will teach, but anyone can actually fill out the form.
=> Change text for self org msg

amy/api/filters.py, amy/api/tests/test_reports.py
Due to wrong lookup type in `InstructorsOverTimeFilter`, an error
was present in API that prevented admins from looking up instructor
numbers with specific badges.
=> Regression fix: Instructors Over Time, badge not iterable

amy/extrequests/tests/test_selforganised_submissions.py, amy/extrequests/views.py, amy/workshops/management/commands/check_for_workshop_websites_updates.py, amy/workshops/tests/test_util.py, amy/workshops/util.py, amy/workshops/views.py
This PR responds to numerous issues raised over functionality of "import from URL" / "update from URL":
- #1572 
- #1610
- #1625 
The solution is to basically ignore the fact that `slug` is missing from websites (mostly because they're hosted outside GitHub). Instead, only when not a single tag is to be found in HTML, then the algorithm switches to YAML version, and if again nothing is found - an error is generated.
This slight change allow to import from URL from websites such as:
* https://pages.nist.gov/2020-05-29-nist/ (used in tests below)
* https://www.hpc.tntech.edu/workshop-2020-03-16/
You can access source code (CTRL+U in Firefox for Windows) and see that these website have a bunch of `<meta>` tags, but the one named `slug` is missing content.
Using first page as an example, I …
=> Update from URL when `slug` is missing

amy/autoemails/actions.py, amy/autoemails/tests/test_postworkshopaction.py
List of event-associated instructors will be available in templates
under `instructors`.
=> Add instructors to PostWorkshopAction context

requirements.txt
This fixes #1635 in order to sustain Github log-in functionality.
=> Upgrade social-auth-core dependency

amy/extrequests/base_views.py, amy/extrequests/tests/test_selforganised_submissions.py, amy/extrequests/tests/test_workshop_inquiries.py, amy/extrequests/tests/test_workshop_requests.py, amy/extrequests/urls.py, amy/extrequests/views.py, amy/workshops/base_views.py
This PR refactors and extends "accept and create event" views:
* `workshoprequest_accept_event` -> `WorkshopRequestAcceptEvent` (CBV)
* `workshopinquiry_accept_event` -> `WorkshopInquiryAcceptEvent` (CBV)
* `selforganisedsubmission_accept_event` -> `SelfOrganisedSubmissionAcceptEvent` (CBV)
All three new views share the same base view (new) `AMYCreateAndFetchObjectView`.
Tests were added for:
* accepting event behaviour
* creating `PostWorkshopAction`
=> PostWorkshopAction in "accept and create event" views

amy/templates/account/login.html
This fixes #1640 by adding `?next=/asd` query for GitHub login button.
It will redirect to pointed resource after successful log in.
=> Add ?next= param for GitHub login

amy/autoemails/actions.py, amy/autoemails/tests/test_newinstructoraction.py, amy/autoemails/tests/test_postworkshopaction.py, amy/autoemails/tests/test_selforganisedrequestaction.py
This fixes #1647 by adding list of tags to each Action email context.
Tests were adjusted.
It's now possible to do:
```django
{% if "online" in tags %}
...
{% endif %}
```
=> Add list of event tags to email body

amy/workshops/fields.py, amy/workshops/tests/test_fields.py
This fixes #1651 by working around the issue of empty
list as an argument to `Select2TagWidget.optgroups()`.
=> Fix Select2TagWidget error when value is empty list

amy/workshops/forms.py, amy/workshops/tests/test_badge.py, amy/workshops/tests/test_event.py, amy/workshops/tests/test_person.py, amy/workshops/tests/test_tasks.py, amy/workshops/views.py
Prefixes added only in Person Update page.
Task Create and Award Create views updated with form prefix.
This fixes #1650 .
=> Add form prefixes to Award create and Task create forms

amy/extrequests/views.py
This fixes #1666 by replacing the previous, wrong permission app name
`workshops` with correct name `extrequests`.
=> Fix wrong permissions app name

amy/extrequests/tests/test_dc_selforganized_event_requests.py, amy/extrequests/tests/test_event_requests.py, amy/extrequests/tests/test_event_submissions.py, amy/extrequests/tests/test_selforganised_submissions.py, amy/extrequests/tests/test_workshop_inquiries.py, amy/extrequests/tests/test_workshop_requests.py, amy/workshops/forms.py, amy/workshops/tests/test_event.py
This makes the Administrator field required.
The model still has `null=True, blank=True,`.
If we have historic data where we don't have Administrator I'm ok leaving those but moving ahead I want all future data to be one of the options available in the drop down.  @pbanaszkiewicz  Is there anything else that needs to be done for this?
=> make Administrator field required

amy/workshops/views.py
This fixes #1653 by showing the comment box for event update.
The comment box will be used for automatic comment made by the "Update from URL"
function.
=> Revert removal of comment box for Event Update

amy/extrequests/tests/test_selforganised_submissions.py, amy/extrequests/views.py
=> Hide "Lessons covered" from SOS mix&match event accept form

amy/autoemails/actions.py, amy/autoemails/tests/test_instructorshostintroductionaction.py
This PR extends conditions for triggering action: for online
events, additionally two supporting instructors are required.
=> Instructors-host introduction: adjustments for online events

amy/autoemails/actions.py, amy/autoemails/tests/test_instructorshostintroductionaction.py
This fixes #1680 by reducing number of required supporting instructors
to 1 in case of online events.
Additionally, list of instructors and supporting instructors is now included
in the email context.
=> Reduce required numer of supporting instructors for Introduction Email

amy/autoemails/actions.py, amy/autoemails/tests/test_instructorshostintroductionaction.py
The fix simply removes empty email addresses, which was cause for MailGun
errors.
=> Fix: Introduction email drops empty contacts from event

amy/autoemails/actions.py, amy/autoemails/tests/test_postworkshopaction.py
This fixes #1686 by adding supporting instructors to the list of roles selected as recipients for PostWorkshopAction email. Tests adjusted.
=> Extend PostWorkshop recipients with supporting instructors

amy/autoemails/admin.py, amy/autoemails/base_views.py, amy/autoemails/tests/base.py, amy/autoemails/tests/test_actionmanagemixin.py, amy/autoemails/tests/test_admin_cancel.py, amy/autoemails/tests/test_admin_edit_template.py, amy/autoemails/tests/test_admin_reschedule.py, amy/autoemails/tests/test_admin_retry.py, amy/autoemails/tests/test_admin_sendnow.py, amy/workshops/views.py
This fixes #1693.
This also fixes a bug reported on Slack: two Introduction emails scheduled for single event.
Finally, this PR updates the RQJob status whenever it's cancelled.
More details in the comments.
=> Dualfix: fix cancel error, fix double email for Introduction action

README.md
=> replace travis-ci.org by travis-ci.com

amy/autoemails/actions.py, amy/autoemails/tests/test_instructorshostintroductionaction.py, amy/autoemails/tests/test_selforganisedrequestaction.py
This fixes #1697.
Additionally, changes were made to tests to ensure that both
SelfOrganisedRequest action and InstructorsHostIntroduction action handle
empty emails correctly.
Going forward, other actions will be changed to use similar code for dropping empty contacts (e.g. #1690).
=> Drop empty emails for SelfOrganisedRequest action

amy/autoemails/actions.py, amy/autoemails/tests/test_postworkshopaction.py
This fixes #1679 by using `event.contact` in PostWorkshopAction.
Additionally a condition for empty contact was added in one point in Introduction email action.
=> Use additional contacts in PostWorkshopAction

amy/extrequests/migrations/0022_auto_20200615_1436.py, amy/workshops/migrations/0217_auto_20200615_1436.py
This fixes conflicting migrations (instructor availability checkbox vs verbiage for number of attendees for both workshop requests and inquiry requests).
=> Change order of the conflicting migrations

amy/autoemails/actions.py, amy/autoemails/tests/test_postworkshopaction.py
This fixes #1681 by extending list of tags for triggering
Post Workshop action. Questions raised in the issue still remain.
=> Add Circuits to PostWorkshopAction tag check list

amy/autoemails/actions.py, amy/autoemails/tests/test_askforwebsiteaction.py, amy/autoemails/tests/test_recruithelpersaction.py, amy/workshops/tests/test_event.py, amy/workshops/tests/test_tasks.py
This PR fixes #1724 by adjusting the trigger logic for:
1. AskForWebsite: run for either self- or centrally-organised workshops
2. RecruitHelpers: don't run for self-organised workshops
=> Ask For Website + RecruitHelpers logic change

amy/templates/workshops/person.html, amy/workshops/views.py
This fixes #1720  by adding "Supporting Instructor" to the role count for Instructor, Helper, and Learner.
=> Supporting Instructor role count

amy/templates/forms/workshop_landing.html, amy/templates/forms/workshoprequest.html
Fixes #1734 
Adds words "centrally organised" to the landing page button and to the intro text on the form itself.
=> specify request form is for centrally org. wkshp

amy/workshops/models.py, amy/workshops/tests/test_tasks.py
This fixes #1563 by adding another enforcement to `Task`: when either membership seat, or open training seat is used, then the role can only be learner.
=> Enforce learner for seat open/member task

amy/extrequests/base_views.py, amy/extrequests/tests/test_selforganised_submissions.py, amy/extrequests/tests/test_wrfinitial.py, amy/extrequests/views.py, amy/workshops/forms.py, amy/workshops/models.py
This fixes #1561 by prefilling as many fields as possible, most notable:
1. `public_status`
2. `curricula`
3. tags based on curricula, `public_status`, Mix&Match or `workshop_listed`
4. contact data
5. host
6. start/end dates (if provided)
7. slug based on start/end dates and location (if provided)
=> Prefill WRF accept and create a new event form

amy/templates/dashboard/admin_dashboard.html
Changes one of the headings on the dashboard to make it more reflective of how it is used by workshop administrators.
=> change heading for dashboard workshop list

amy/autoemails/tests/test_genericaction.py, amy/templates/forms/selforganisedsubmission_confirm.html, amy/templates/forms/trainingrequest_confirm.html, amy/templates/forms/workshopinquiry_confirm.html, amy/templates/forms/workshoprequest_confirm.html, amy/workshops/management/commands/instructors_activity.py, amy/workshops/tests/test_util.py, config/settings.py, docs/sending_mails.md
addresses #1764
After talking with @sheraaronhurt, only workshop-related tasks should have a different point of contact. Occurrences that have to do with questions about how to update their profile information, etc. should continue to use `team@carpentries.org`. 
I think I replaced occurences that were appropriate. But feel free to reimplement/refactor.
=> update default email for workshop related tasks

amy/autoemails/actions.py, amy/autoemails/tests/test_askforwebsiteaction.py, amy/autoemails/tests/test_instructorshostintroductionaction.py, amy/autoemails/tests/test_postworkshopaction.py
Fixes #1755 
The following email actions received a new `hosts` context variable:
* `AskForWebsiteAction`
* `InstructorsHostIntroductionAction`
* `PostWorkshopAction`
It's intentionally a new variable for backwards-compatibility sake (`InstructorsHostIntroductionAction` already has a singlular `host` variable, and `PostWorkshopAction` has a `host` that links to workshop host organisation).
=> Automated emails: multiple hosts for some email actions

.github/CONTRIBUTING.md, .github/workflows/build-docs.yml, README.md, docs/procedures.md
Changes references of the master branch to main.
Fixes #1794
=> fix: Update main branch name after transition from master

amy/dashboard/tests/test_landing_page.py, amy/dashboard/views.py, amy/workshops/models.py
By default going to `/dashboard/admin/` the logged in user will be selected:
When the user is deselected `/dashboard/admin/?assigned_to=` all the unassigned events are viewable:
Fixes #1784
=> feature: Dashboard events filtered to logged in user by default.

amy/dashboard/forms.py, amy/dashboard/tests/test_search.py, amy/dashboard/views.py
When one result group contained single result, the other results would
be ignored. This fixes the invalid logic.
=> [#1819] Fix search for single result

amy/consents/models.py, amy/workshops/management/commands/fake_database.py
Fixes https://github.com/carpentries/amy/issues/1842
It adds three terms:
- Are you 18 years of age or older?
- May contact: Allow to contact from The Carpentries according to the Privacy Policy.
- Do you consent to have your name or identity associated with lesson publications?
Then adds consents for all the terms above to all persons in the database. 
```
$ make dev_database
...
Generating 255 fake terms and consents...
...
$ python manage.py shell  
>>> from consents.models import *
>>> Term.objects.all()
<TermQuerySet [<Term: Term object (1)>, <Term: Term object (2)>, <Term: Term object (3)>]>
>>> Consent.objects.all().count()
255
```
=> feature(Consents): Generate fake terms and consents for dev database.

docs/amy_database_structure.md
We do not have a `workshops_persons` table, but we do have a `workshops_person` table.
=> fix typo in documentation

amy/api/urls.py, amy/api/views.py, amy/fiscal/base_views.py, amy/fiscal/forms.py, amy/fiscal/tests/test_organization.py, amy/fiscal/views.py, amy/templates/dashboard/admin_dashboard.html, amy/templates/dashboard/search.html, amy/templates/fiscal/all_organizations.html, amy/templates/fiscal/organization.html, amy/templates/includes/event_details_table.html, amy/templates/workshops/all_events.html, amy/workshops/models.py
Previously `Organization.domain` was just that - only a domain. Now it can contain almost entire URL, without scheme.
Generic URL format: `scheme://netloc/path;parameters?query#fragment`
Out of it we're stripping scheme, `//` before the netloc, parameters and fragment.
Breaking change: URLs in API don't contain trailing slashes (otherwise they would not match new domain format correctly).
This fixes #1835.
This PR is built on top of PR #1858 and contains it's commits.
=> [#1835] Switch Organization.domain to accept domain + path

amy/dashboard/views.py, amy/fiscal/forms.py, amy/fiscal/tests/test_membership.py, amy/fiscal/views.py, amy/templates/dashboard/trainee_dashboard.html, amy/templates/workshops/person.html, amy/workshops/views.py
This fixes #1854.
This fixes #1855.
This fixes #1856.
Depends on #1869.
1. Display person membership roles in person details view as well as in the trainee dashboard (but only if person has any membership roles) - #1856
2. Allow editing values for roll-over fields when creating membership through roll-over mechanism - #1854 
3. Allow for copying over member organisations and membership person tasks when rolling over; mechanism is controlled over checkboxes - #1855
=> [#1854][#1855][#1856] Adjustments to rolling-over mechanism, display person membership roles

README.md
- Docker must be running prior to trying to use `make dev_database`
- Fixed indentation issues introduced in a prior pr
- removed reference to createsuperuser since the make file covers that.
=> ref(README): Changed setup instructions ordering

amy/extrequests/forms.py, amy/static/selforganisedsubmission_form.js
This adds REGEX validation in JavaScript for checking the URL.
Fixes #1759.
When URL is correct:
When repository name format is incorrect:
When Github.com link was used:
When URL is not for username.github.io or github.com/username:
@Talishask I corrected wording slightly (switched "slug" with "repo").
=> [#1759] Self-organised Submission form URL warnings + JS validation

config/settings.py
This fixes #1898 by adding default tag classes to changed message tags.
Thanks to this change, messages shown in Django Admin display with
correct styles, and current styling of messages in other parts of AMY
is maintained.
A warning message in Django Admin:
=> [#1898] Fix django messages tags

amy/templates/includes/event_details_table.html, amy/workshops/forms.py
This fixes #1711 by re-introducing instructors pre/post survey links into event details page and event create/edit form.
=> [#1711] Reactivate instructor survey links

amy/consents/apps.py, amy/consents/models.py, amy/consents/receivers.py, amy/consents/tests/base.py, amy/consents/tests/test_models.py, amy/templates/navigation.html, amy/workshops/apps.py, amy/workshops/models.py, amy/workshops/receivers.py, amy/workshops/signals/__init__.py, amy/workshops/tests/base.py, amy/workshops/tests/test_person.py, amy/workshops/views.py
Fixes https://github.com/carpentries/amy/issues/1888
Dependent upon https://github.com/carpentries/amy/pull/1905
I needed to move signals in Workshops app so that they could be registered by the receivers in Consents. The way it was structured before the Signal init function ran after the Consents app had registered the signal (wiping out the receiver). Putting it in a module __init__ prevents that from happening.
=> feat(Profile Archival): All consents are unset when a person is archived.

amy/workshops/views.py
Fixes https://github.com/carpentries/amy/issues/1890
Inactive User:
Active User (no change):
=> feature(Profile Archival): Added an info message when the user's profile is not active

amy/workshops/models.py, amy/workshops/tests/test_person.py
I missed some personal information. Removing those as well.
Fixes https://github.com/carpentries/amy/issues/1918
Before Archival:
After Archival:
=> fix(Profile Archival): Remove more  personal information when the user is  archived.

amy/workshops/models.py, amy/workshops/tests/test_person.py
Fixes https://github.com/carpentries/amy/issues/1892
Person with a change history:
Person's change history after archival:
=> feature(Profile Archival): Remove profile change history.

amy/workshops/models.py, amy/workshops/tests/test_person.py
Fixes https://github.com/carpentries/amy/issues/1889
Set custom permissions on the user and made them a super user:
Permissions after the profile is archived:
=> feature(Profile Archival): Remove groups and permissions from the user when the profile is archived.

amy/extrequests/forms.py, amy/extrequests/tests/test_training_request.py
The form didn't display the field correctly, because a wrong field was
used (BooleanField instead of ChoiceField).
Please delete this line and the text below before submitting your contribution.
This fixes #1946.
=> [#1946] Fix BulkMatchTrainingRequestForm

amy/workshops/migrations/0228_auto_20210204_0658.py, amy/workshops/migrations/0237_auto_20210321_1056.py
The migrations order would:
1. introduce "public_status" field with "public" default value
2. change default value to "private".
This was wrong because all the memberships would become public once
the first migration is run.
Changes introduced in this commit/PR make "private" default for the first
migration; the second migration is removed as it's now a no-op.
This fixes #1945.
=> [#1945] Change Membership public status def. value

amy/extcomments/forms.py, amy/extcomments/tests.py, amy/extcomments/utils.py
This fixes #1944 by disabling required email field - now it's not
required.
This means that some users, who don't have email on file, will be able
to post comments.
=> [#1944] Make comments work w/o user's email

amy/templates/fiscal/membership.html
This fixes #1940 by improving table display of training seats on
membership details page.
=> [#1940] Fix display of membership training seats

amy/workshops/models.py, amy/workshops/tests/test_person.py
Fixes https://github.com/carpentries/amy/issues/1920
Before Archival:
After Archival:
=> feature(Profile Archival): Added social auth removal to Person archive.

amy/consents/forms.py, amy/consents/tests/test_forms.py
Fixes https://github.com/carpentries/amy/issues/1927
=> ref(Consents): Filtered out already answered required consents in actions required.

amy/dashboard/views.py, amy/templates/dashboard/trainee_dashboard.html
Partial fix to #1963
With a consent unset:
The same consent answered:
=> fix(Consent): Remove old-style consents from trainee dashboard.

amy/api/serializers.py, amy/api/tests/test_api_structure.py, amy/api/tests/test_export.py, amy/api/urls.py, amy/api/views.py, amy/consents/models.py, amy/workshops/tests/base.py
Part of a fix for https://github.com/carpentries/amy/issues/1963
Handles the person data export.
=> feat(Consents): Remove old-style consents from api serializers

amy/workshops/management/commands/fake_database.py
Members were being created in random order, which often broke
the uniqueness constraint and prevented creating DEV database.
This fix will create unique members from randomly-sorted organization
list.
=> Fix non-unique membership members in dev database

amy/workshops/filters.py, amy/workshops/tests/test_filters.py
AllCountriesFilter and AllCountriesMultipleFilter use COUNTRIES_OVERRIDE
to substitute custom countries used to narrow the total list of
countries.
For example: `['W3']`
will be replaced with: `[('W3', 'Online')]`
since this value is set in the `settings.py`.
=> [#1996] Fix *CountriesFilter override countries

amy/extrequests/tests/test_training_request.py, amy/extrequests/views.py
Calculation in some specific cases would result in a warning message
even though the remaining number of seats was >=1.
=> [#1946] Fix: warning msg for exceeding remaining seats

amy/fiscal/tests/test_organization.py, amy/fiscal/views.py, amy/templates/fiscal/membership.html, amy/templates/fiscal/organization.html
Table style is taken from organisation page. Additional style fixes
were introduced to the original table (columns switched, headers
capitalised.)
The same table is enhanced with a new column defining 
organization<->workshop relation (hosted, sponsored, or affiliated).
This fixes #1943.
This fixes #1942.
=> [#1942][#1943] List events on membership page, display event type of organization page

amy/fiscal/forms.py, amy/fiscal/tests/test_membership.py, amy/fiscal/views.py
This fixes #1938.
Membership extension form now contains a comment field.
This comment will be posted once the form is submitted. The comment
content's will include information about extension length.
=> [#1938] Add comment to membership extension

amy/fiscal/forms.py, amy/fiscal/views.py
This fixes #1934.
This fixes #1935.
No tests needed adjusting.
=> [#1934][#1935] Membership Rollover form: remove default agreement link, move "Copy ...?" fields up

amy/fiscal/forms.py, amy/fiscal/tests/test_membership.py, amy/fiscal/views.py
This fixes #1936 by allowing to edit rolled fields.
Two kind of fields: rolled from previous and rolled over to.
"Rolled from previous" are enabled when membership was created as rolling-over.
"Rolled over" fields are enabled when membership was rolled over to another one.
=> [#1936] Membership: edit rolled values

amy/fiscal/forms.py, amy/static/membership_create.js
This fixes #1931 by prepopulating *workshops without admin fee* and *public instructor training seats* fields based on variant values proposed in #1931.
Visual indication was added to aid users.
Preview:
=> [#1931] Prepopulate workshop and public training seats based on selected membership variant

amy/templates/trainings/all_trainees.html, amy/workshops/templatetags/training_progress.py
This fixes #1999.
Display "A" (Asked to repeat) in light shade of blue.
For screenshot, please see: https://github.com/carpentries/amy/issues/1999#issuecomment-894694367
=> [#1999] Change Training Progress "a" state badge color

amy/extrequests/forms.py, amy/extrequests/tests/test_training_request.py, amy/extrequests/views.py, amy/workshops/models.py, amy/workshops/tests/test_tasks.py, amy/workshops/views.py
This fixes #2000.
There were two issues reported:
1. inability to create tasks when membership was out of seats -> solution was to change errors into warnings and move the logic into 2 views (task add, task update); tests were updated correspondingly
2. training request match form: inability to create in-house seats -> solution was to fix the error.
=> [#2000] "Seats exceeded" warning

amy/fiscal/forms.py, amy/fiscal/tests/test_membership.py, amy/fiscal/views.py, amy/static/membership_extend.js
=> [#2005] Membership Extend: use new end date instead of number of days

amy/fiscal/fields.py, amy/fiscal/forms.py, amy/fiscal/tests/test_membership.py, amy/fiscal/views.py, amy/static/css/amy.css, config/settings.py
Fixes #2015.
This PR introduces a way to edit extensions in Membership Edit page.
Screenshot:
=> [#2015] Edit membership extensions

amy/fiscal/tests/test_membership_members.py, amy/fiscal/views.py, amy/workshops/management/commands/sync_usersocialauth.py, amy/workshops/receivers.py
This fixes #1929 by adding a comment with listed member changes when
user updates members related to a membership.
Sample result comment:
=> [#1929] Log membership members change

amy/dashboard/tests/test_search.py, amy/extrequests/tests/test_training_request.py, amy/workshops/tests/base.py, amy/workshops/tests/test_event.py, amy/workshops/tests/test_person.py
The issue appeared when running tests in parallel in a fresh database.
Most likely it was due to some junk left in sites cache after
migrations. The solution clears the cache whenever Sites framework is
used.
=> [#1875] Fix Sites framework issue when running tests

amy/static/online_country.js, amy/templates/dashboard/admin_dashboard.html, amy/templates/includes/event_details_table.html, amy/templates/workshops/event.html, amy/templates/workshops/event_review_metadata_changes.html, amy/templates/workshops/events_merge.html, amy/workshops/models.py, amy/workshops/tests/test_event.py, amy/workshops/views.py
This fixes #1657 by changing logic for handling event latitude and longitude.
Apart from small fixes to how these values are displayed, there's some fixes to various Javascript scripts used with them.
=> [#1657] Null event latitude and longitude

amy/extrequests/forms.py, amy/extrequests/tests/test_workshop_inquiries.py, amy/extrequests/tests/test_workshop_requests.py, amy/static/instructor_availability_checkbox.js
This fixes #1710. The `instructor_availability` checkbox will appear
conditionally based on the value in `preferred_dates` or any input
in `preferred_dates_other`.
=> [#1710] Require instructor availability conditionally

amy/templates/fiscal/organization.html
This fixes #2055.
The template used DB value instead of property calculating sum of two DB values.
=> [#2055] Fix wrong template variable displayed in Organization page

amy/fiscal/tests/test_membership.py, amy/fiscal/views.py
This fixes #2056.
Previous behavior: when rolling over, max value for public/inhouse
training seats was set to the "remaining value" in respective seat
field. Even if that remaining value was negative.
This is now changed so that the max value is no lesser than 0.
=> [#2056] Fix for negative remaining values when rolling over

amy/fiscal/tests/test_membership.py, amy/workshops/models.py
This fixes #2051 by removing constraint dates on calculation - now the membership start and end dates are not considered. The link to membership is enough.
=> [#2051] Membership counting queryset adjustment

amy/static/amy_utils.js
Once opened, the widget should get focus on it's search field.
See https://github.com/carpentries/amy/issues/2097#issuecomment-981094900 for more information and a video.
This fixes #2097.
=> [#2097] Improve select2 widget keyboard navigation

amy/autoemails/tests/test_utils.py, amy/autoemails/utils.py, amy/autoemails/views.py
This view will only redirect to safe `?next` values, if they're provided.
Fixes #2106.
=> [#2106] Increase security in `generic_schedule_email` redirect

amy/autoemails/tests/test_job_ttl.py, config/settings.py
This fixes #1811 by increasing the default time for jobs to live after
they successfully finish from 500s to 1yr.
=> [#1811] Successful job result TTL is 1 year long

amy/templates/navigation.html, amy/templates/navigation_instructor_dashboard.html
This addresses #2087 by adding a link to the admin help guide and the users help guide to the respective navigation menus.  In addition to adding the links to the menus, it also removes the conditional in [the admin navigation](https://github.com/carpentries/amy/blob/develop/amy/templates/navigation.html) because this view is already only available to admin users.
=> add link to help guides to menu

amy/templates/mailing/workshopinquiry.txt
now that online workshops are permanent we do not need to mention covid-19.
=> Remove covid-19 and add workshops webpage

Makefile, Pipfile, Pipfile.lock, amy/autoemails/actions.py, amy/autoemails/base_views.py, amy/autoemails/bulk_email.py, amy/autoemails/tests/test_action.py, amy/consents/util.py, amy/dashboard/views.py, amy/recruitment/forms.py, amy/recruitment/tests/test_forms.py, amy/recruitment/tests/test_instructor_recruitment_views.py, amy/recruitment/urls.py, amy/recruitment/views.py, amy/static/css/amy.css, amy/templates/includes/instructor_selection_summary.html, amy/templates/includes/instructorrecruitment.html, amy/templates/recruitment/instructorrecruitment_list.html, amy/workshops/management/commands/fake_database.py, amy/workshops/tests/test_event.py, amy/workshops/tests/test_tasks.py, pyproject.toml
=> [#2065] Confirm and decline instructor signups

amy/workshops/tests/test_person.py
It would be great to comply with now common practice of acknowledging Marie Curie's Polish origins indicating both her surnames as she did herself:
- Here's her double-surname signature:
https://en.wikipedia.org/wiki/Marie_Curie#/media/File:Marie_Curie_Sk%C5%82odowska_Signature_Polish.svg 
- Here's her Nobel prize diploma with both surnames:
https://en.wikipedia.org/wiki/File:Marie_Sk%C5%82odowska-Curie%27s_Nobel_Prize_in_Chemistry_1911.jpg
Quoting the European Commission website comment regarding the renaming of the "Marie Curie Actions" into "Marie Skłodowska-Curie Actions" (https://ec.europa.eu/research-and-innovation/en/horizon-magazine/marie-sklodowska-curie-actions-supporting-europes-best-and-brightest-researchers-25-years):  "the programme was renamed the Marie Skłodowska-Curie …
=> Curie -> Skłodowska-Curie

amy/dashboard/tests/test_instructor_recruitment_views.py, amy/dashboard/urls.py, amy/dashboard/views.py, amy/templates/dashboard/upcoming_teaching_opportunities.html
This fixes #2069.
Upon resignation, user's signup is completely removed from the system. They are able to re-apply to the same recruitment again.
=> [#2069] Resign from recruitment

amy/dashboard/views.py
Adds functionality to search trainees by personal and family name together.  This does add some slightly redundant code, but only twice.  We can consider refactoring if needed.
Addresses #2149
=> Training search

amy/communityroles/forms.py, amy/communityroles/tests/test_community_role_forms.py, amy/communityroles/tests/test_community_role_views.py, amy/static/communityrole_form.js, amy/workshops/lookups.py
This fixes #2114 by limiting Community Roles awards to only show and accept person's awards.
=> [#2114] Community role award limited to person

amy/workshops/management/commands/assign_instructor_community_role.py, amy/workshops/tests/test_commands.py
Fix #2167 by providing the command to assign instructor community roles when user has an Instructor Badge.
=> [#2167] Command to assign instructor community roles + tests

amy/communityroles/models.py, amy/communityroles/tests/test_models.py, amy/templates/workshops/workshop_staff.html, amy/workshops/filters.py, amy/workshops/forms.py, amy/workshops/models.py, amy/workshops/tests/base.py, amy/workshops/tests/test_lookups.py, amy/workshops/tests/test_workshop_staff_searching.py, amy/workshops/views.py
This fixes #2168 by changing how workshop staff searching works. It's now based on instructor community role instead of a badge selection.
~~TODO: fix broken test.~~ fixed
=> [#2168] Update workshop staff searching with instructor community role

amy/templates/includes/instructor_role_badge.html, amy/templates/workshops/all_persons.html, amy/templates/workshops/event.html, amy/templates/workshops/workshop_staff.html, amy/workshops/models.py, amy/workshops/templatetags/tags.py, amy/workshops/views.py
This fixes #2170.
Preview of final version:
=> [#2170] Instructor badge display

amy/communityroles/forms.py, amy/communityroles/tests/test_community_role_forms.py, amy/static/communityrole_form.js, amy/workshops/management/commands/migrate_to_single_instructor_badge.py, amy/workshops/tests/test_commands.py
This fixes #2225 and some additional requirements:
* URL field is required in Community Role form if the config specifies so
* Awards for old instructor badges are removed when single instructor badge is awarded to a person
=> #2225 updates after last meeting

amy/workshops/management/commands/assign_trainer_community_role.py, amy/workshops/management/commands/migrate_inactive_trainers_to_trainer_badges.py, amy/workshops/management/commands/migrate_to_single_instructor_badge.py, amy/workshops/tests/test_commands.py
1. Small improvements made in migration to single instructor badge
2. New command: assign trainer community role to people with trainer badge
3. New command: migrate trainer-inactive awards to trainer awards
=> Migrate trainers

amy/recruitment/templatetags/instructorrecruitment.py, amy/recruitment/tests/test_template_tags.py
=> [#2249] Fix issues with empty event dates on upcoming teaching opportunities

amy/dashboard/tests/test_instructor_recruitment_views.py, amy/dashboard/views.py, amy/recruitment/tests/test_instructor_recruitment_views.py, amy/recruitment/views.py, amy/templates/includes/instructorrecruitment.html
Unquote is required if `next` contains e.g. `?status=o`, otherwise user was redirected to non-existing URL.
=> [#2257] Fix: unquote ?next value for redirection

amy/dashboard/filters.py, amy/workshops/filters.py, amy/workshops/tests/test_filters.py
By default, countries list should be extended with a custom list of countries (for backwards-compatibility), but it's configurable and can be turned off (the case for Upcoming Teaching Opportunities filter).
This fixes #2254.
=> [#2254] Extend AllCountriesFilter, AllCountriesMultipleFilter: conditionally extend countries

amy/templates/includes/instructorrecruitment.html
Adds "Submission date" and "Last change" columns. Fixes #2259 
Also removes a duplicate tooltip in the same table that is never displayed, from what I can tell.
=> Display timestamps of instructor signups on instructor recruitment page

amy/workshops/management/commands/create_superuser.py, amy/workshops/tests/test_commands.py, start.sh
=> Run `create_superuser` to create super user on application's start

amy/communityroles/fields.py, amy/communityroles/tests/test_fields.py
Fixes #2336 .
I wrote some tests, but do we actually use custom keys at all?
=> hotfix: check for null values when loading custom keys

config/settings.py
This fixes #2350.
Two new envvars can be used: `AMY_CACHE_DEFAULT` and `AMY_CACHE_SELECT2`. They should use URL format, for example `AMY_CACHE_DEFAULT=redis://127.0.0.1:6379/0?client_class=django_redis.client.DefaultClient` for Redis or `AMY_CACHE_SELECT2=dbcache://select2_cache_table` for DB-based.
=> Cache settings are now configurable via envvars

amy/communityroles/fields.py, amy/communityroles/tests/test_community_role_views.py
Fixes #2336 (hopefully for good this time). Details in that issue.
This is a production issue, so again a hotfix release would be needed if 4.1 isn't ready to go yet.
=> fix 500 error after posting invalid community role

amy/fiscal/filters.py, amy/fiscal/tests/test_filters.py, amy/fiscal/views.py, amy/reports/views.py, amy/templates/fiscal/all_memberships.html, amy/templates/reports/membership_trainings_stats.html, amy/workshops/filters.py, amy/workshops/models.py
Fixes #2327 and introduces tests for membership filters.
Includes combining some columns in the membership training stats view as requested in that issue.
=> Fix internal errors from filters

amy/static/css/amy.css, amy/templates/base.html, amy/templates/navigation.html, amy/workshops/context_processors.py, config/settings.py
This fixes #2322.
There will be 2 banners available: local and testing.
Local looks like this:
Testing looks like this:
Every site will have this banner. It will stay on top, but will hide beneath the navigation bar:
=> Colors for different builds

amy/consents/admin.py, amy/consents/migrations/0007_term_short_description.py, amy/consents/models.py, amy/dashboard/views.py, amy/templates/dashboard/instructor_dashboard.html, amy/workshops/views.py, docs/amy_database_structure.md, docs/users_guide/admin_index.md, docs/users_guide/community_index.md
Fixes #2302 .
Also propose updating the `content` field of the `public-profile` consent to "Do you consent to publish your profile
on The Carpentries website?" in the AMY Django admin interface.
=> Reduce hardcoding of consent labels in UI

amy/extrequests/filters.py, amy/extrequests/tests/test_training_request.py
Fixes #2315.
Stopgap for #2314 - the filtered view still performs a bit slowly on the full AMY database ([link](https://amy.carpentries.org/requests/training_requests/?search=&group_name=&state=no_d&matched=u&affiliation=&location=&order_by=)), but it shouldn't be catastrophic any more.
This implementation only sets the defaults if the user has chosen not to filter at all - i.e. it is still possible to see all training requests by explicitly selecting the blank options for these fields in the filter UI (or setting the URL query string to `?state=&matched=`)
Note that setting defaults for requests that do include user-selected filter choices is [not recommended](https://django-filter.readthedocs.io/en/main/guide/tips.html?highlight=default#using-initial-values-as-defaults).
=> Set default filtering for training requests

config/urls.py
Fixes #2429 .
@pbanaszkiewicz ideally this should be released as a hotfix rather than waiting for v4.2.
=> Allow longer auth tokens for password reset

amy/dashboard/tests/test_instructor_dashboard.py, amy/templates/includes/training_progresses_inline.html, amy/trainings/forms.py, amy/trainings/tests/test_trainees.py, amy/trainings/tests/test_training_progress.py, amy/workshops/models.py, amy/workshops/tests/test_person.py
In the interest of time, I'm raising this not against `feature/instructor-checkout-changes` but instead against the branch used in https://github.com/carpentries/amy/pull/2431 for review. Will not merge until https://github.com/carpentries/amy/pull/2431 is merged.
Fixes #2440.
This PR will:
- use 'Get Involved' rather than 'Lesson Contribution' when checking instructor badge eligibility and in all relevant tests (screenshot 1)
- allow TrainingProgress to be created for trainees without a training task (screenshot 2)
- fix the `test_eligible_but_not_awarded` test in `amy/dashboard/tests/test_instructor_dashboard.py` which was broken by #2431 
- break a different test `test_lesson_contribution_passed` in `amy/dashboard/tests/test_instructor_dashboard.py` which will be fixed as part of #2411
=> Update instructor eligibility requirements with Get Involved step

amy/trainings/filters.py, amy/trainings/tests/test_filters.py, amy/workshops/templatetags/training_progress.py
In the interest of time, I'm raising this not against `feature/instructor-checkout-changes` but instead against the branch used in #2431 for review. Will not merge until #2431 is merged.
Fixes #2412.
This PR will:
- update the filter for viewing unevaluated Get Involved submissions (formerly Lesson Contributions)
- add tests for all the trainee filters, because these were missing
- correctly display the date from a Get Involved submission, if present (falling back on the datetime the submission/TrainingProgress was created otherwise)
=> Update filter for unevaluated Get Involved step

amy/trainings/forms.py, amy/trainings/tests/test_trainees.py
In the interest of time, I'm raising this not against feature/instructor-checkout-changes but instead against the branch used in https://github.com/carpentries/amy/pull/2431 for review. Will not merge until https://github.com/carpentries/amy/pull/2431 is merged.
Fixes #2445.
This PR will:
- add fields needed for the Get Involved step to the bulk training progress form
- make the bulk form use the same JS as the individual training progress form to dynamically display fields based on options
- expand tests of the bulk form to test adding different requirements
=> Update bulk training progress form to work with Get Involved step

amy/dashboard/forms.py, amy/dashboard/tests/test_instructor_dashboard.py, amy/dashboard/views.py, amy/scripts/seed_involvements.py, amy/templates/dashboard/training_progress.html, amy/trainings/forms.py, amy/trainings/tests/test_training_progress.py, amy/workshops/models.py
Fix #2411 , fix #2451 .
This PR will:
- update "Lesson Contribution" to "Get Involved" throughout the instructor dashboard/training progress view and in associated tests
- update the lesson contribution form to match the new Get Involved format, including validation
- update instructions and links in the training progress view
- refactor the validation for TrainingProgress
- update error messages so that they should make sense in both the admin-facing TrainingProgressForm and the trainee-facing GetInvolvedForm
- fix the failing test on this branch - CI should now pass.
=> Update trainee progress view

amy/trainings/tests/test_template_tags.py, amy/workshops/tests/test_person.py
Fixes #2452 .
Also cleans up a leftover reference to Lesson Contribution in a separate test.
=> Add tests for training progress template tags

amy/templates/workshops/changes_log.html, amy/workshops/tests/test_views.py
Fixes #2456.
Though now I've done this, I realise that displaying just the first Version created as part of each Revision loses some helpful information (e.g. if a Task is created, this updates an Event and a Person; only the Event name is shown in the changes_log view). As we barely use this view, I'm not going to propose further changes at this time.
=> Correct links in changes_log view

amy/dashboard/tests/test_instructor_dashboard.py, amy/dashboard/tests/test_utils.py, amy/dashboard/utils.py, amy/dashboard/views.py, amy/templates/dashboard/training_progress.html, amy/templates/includes/progress_trainee_view.html, amy/trainings/tests/test_template_tags.py, amy/workshops/templatetags/dates.py, amy/workshops/templatetags/training_progress.py
This PR will:
- show colour-coded state & date of each step's progress. This shows one recent progress for each step, prioritising progress with a passed state. (fixes #2476, fixes #2477)
- update alerts at top of page (fixes #2475)
This PR will not:
- update the Get Involved part of the page to show/edit a submission - that will come in the next PR (and is previewed in #2472). I've deliberately omitted the submission form from the screenshots for this reason.
- ~fix the colour contrast issues that have arisen - @elichad will work on this separately before the 4.2 release~ figured out a way to improve contrast after all
Requesting code review from @pbanaszkiewicz as usual.
For @klbarnes20 and @karenword I have some outstanding design questions. You only need to look through the …
=> Improvements to trainee progress view

amy/dashboard/forms.py, amy/dashboard/tests/test_forms.py
Form was raising a server error if submitted blank, because the validation on `trainee_notes` was expecting `involvement_type` to be set.
Note that `involvement_type` is always required in `TrainingProgress` creation, but it has `required=False` set on the form. This is because at least one _other_ field will always be required, but this is only determined at validation time, so showing an asterisk on only one field and not the rest doesn't quite represent how the form works.
=> Add cancel button and fix validation bug on Get Involved form

amy/workshops/base_views.py, config/settings.py
This fixes #2426 by hiding Anymail errors.
The original bug report is caused by test-amy2 attempting to send email without authorization. There's a couple of ways to fix this:
1. disable sending emails in test-amy2 (through AMY_LIVE_EMAIL env variable)
2. catch the exceptions where they are caused (this is the way I chose)
3. set up test-amy2 in a way that it can send real emails
4. switch to sandbox/test-only mode in test-amy2 + mailgun (probably solution that would take the most time).
I wanted to fix this issue quickly, and I didn't want to disable sending emails altogether since we may want to do this in future. So I decided on solution no. 2.
=> [#2426] Hide Anymail errors

amy/api/tests/test_export.py, amy/dashboard/forms.py, amy/dashboard/tests/test_get_involved_views.py, amy/dashboard/tests/test_instructor_dashboard.py, amy/scripts/seed_involvements.py, amy/templates/dashboard/training_progress.html, amy/templates/get_involved_form.html, amy/trainings/tests/test_filters.py, amy/trainings/tests/test_trainees.py, amy/trainings/tests/test_training_progress.py, amy/workshops/models.py
Fixes #2470. Depends on #2492.
This just checks for "github.com/ORG" in the URL text, for all of our organisations as listed in the Carpentries Handbook: https://docs.carpentries.org/topic_folders/communications/tools/github_organisations.html.
In future we might look at storing a machine-readable list of organisations centrally and pulling the list from that, but for now @maneesha and I agreed to hardcode this list.
Screenshot:
=> Check that GitHub contributions are associated with a Carpentries GH organisation

amy/api/tests/test_export.py, amy/dashboard/forms.py, amy/dashboard/tests/test_forms.py, amy/trainings/tests/test_training_progress.py, amy/workshops/migrations/0261_migrate_lesson_contribution_to_get_involved.py, amy/workshops/models.py
Fixes #2507 by moving the relevant validation out of the TrainingProgress model and into the GetInvolvedForm.
Required due to submissions made before the rollout potentially not having GitHub URLs where they would now be required - admins may still need to update these to change the state or add notes.
Required for v4.2.
=> Allow admins to submit/update training progress with non GitHub URL

amy/dashboard/tests/test_instructor_dashboard.py, amy/templates/dashboard/training_progress.html
Fixes #2508 .
More explanation in https://github.com/carpentries/amy/issues/2508#issuecomment-1671458935.
Required for v4.2 so we aren't displaying misleading information about checkout deadlines.
=> Update conditions for progress messages at top of page

config/settings.py
This fixes #2372.
Missing HTTP**S** was the main reason why test-amy2 GitHub auth failed.
=> Force HTTPS in `redirect_uri` generated by social auth

amy/templates/requests/all_trainingrequests.html, amy/templates/workshops/workshop_staff.html
Fixes a contrast bug introduced by #2490 . The override is no longer needed as the text colour choice is handled better by Bootstrap under the new palette.
Current `develop` branch:
This branch:
=> Remove use of text-white to override text colour

amy/emails/actions.py, amy/emails/controller.py, amy/emails/forms.py, amy/emails/signals.py, amy/emails/templatetags/emails.py, amy/emails/tests/test_signals.py, amy/emails/tests/test_template_tags.py, amy/emails/tests/test_utils.py, amy/emails/tests/test_views.py, amy/emails/types.py, amy/emails/utils.py, amy/emails/views.py, amy/templates/emails/email_template_create.html, amy/templates/emails/email_template_detail.html, amy/templates/emails/email_template_edit.html, amy/templates/emails/scheduled_email_detail.html, amy/templates/emails/scheduled_email_edit.html
This fixes #2482 by providing links to documentation for every variable used in email template context (e.g. person, event, award, etc.).
It builds on top of #2481.
~~WIP. Needs testing and perhaps some code improvements / refactoring.~~
=> [Emails] Template context variables documentation links

amy/dashboard/forms.py, amy/dashboard/tests/test_forms.py
Fixes a bug in v4.2 reported by @karenword in Slack:
> a trainee is reporting that this link is throwing an error claiming it is not associated with a Carpentries repo: `https://github.com/LibraryCarpentry/lc-r/issues/<id>` .
This arises because we have the organization in lowercase (`librarycarpentry`) in our code. Github organization URLs are case insensitive, so we should accept both.
=> Make GitHub organization check case insensitive

amy/dashboard/templatetags/notifications.py, amy/dashboard/tests/test_template_tags.py, amy/emails/tests/test_utils.py, amy/emails/utils.py, amy/templates/base.html, config/settings.py
This fixes #2498.
Two notifications generated by email actions (`messages_missing_template` and `messages_action_scheduled`) now add extra tag `"only-for-admins"`.
New condition in `base.html` checks for this tag when displaying messages. If the tag is present on the message, then that message is shown only for administrator users. If the tag is not present, then the message is shown as usual.
Writing unit tests for this was a little bit tricky, as I wasn't able to inject adding messages to a view. So instead I moved the logic to the template tag and tested it instead of testing the view output.
=> [Emails] Disable some notifications for non-admin users

amy/emails/forms.py, amy/emails/tests/test_controller.py, amy/templates/emails/email_template_list.html
This fixes #2499. The field was added to EmailTemplate forms and displayed in the email template list+detail views.
Email Controller tests were extended to ensure only active templates are considered.
=> [Emails] Enable field `active` on EmailTemplates

amy/emails/controller.py, amy/emails/models.py, amy/emails/templatetags/emails.py, amy/emails/tests/test_controller.py, amy/emails/tests/test_template_tags.py, amy/emails/tests/test_views.py, amy/emails/views.py, amy/templates/emails/scheduled_email_detail.html, amy/templates/emails/scheduled_email_reschedule.html
Fixes #2459.
Based on PR #2491.
This PR introduces whitelist of statuses the scheduled email has to be in in order to edit, reschedule or cancel it.
One of the interesting techniques used here is database-level locking connected with filtering for allowed statuses. This will ensure that an email is in proper status before and during the POST request.
=> [Emails] Prevent changes to emails in specific states

amy/extrequests/base_views.py, amy/extrequests/tests/test_selforganised_submissions.py, amy/extrequests/tests/test_workshop_inquiries.py, amy/extrequests/tests/test_workshop_requests.py, amy/templates/includes/selforganisedsubmission_details.html, amy/templates/includes/workshopinquiry_details.html, amy/templates/includes/workshoprequest_details.html, amy/workshops/management/commands/fake_database.py, docs/design/design_patterns.md
Also updates fake data creation to include membership codes.
=> Autofill membership when accepting workshop requests

amy/emails/actions/admin_signs_instructor_up_for_workshop.py, amy/emails/actions/base_action.py, amy/emails/actions/instructor_badge_awarded.py, amy/emails/actions/instructor_confirmed_for_workshop.py, amy/emails/actions/instructor_declined_from_workshop.py, amy/emails/actions/instructor_signs_up_for_workshop.py, amy/emails/actions/instructor_training_approaching.py, amy/emails/actions/persons_merged.py, amy/emails/tests/actions/test_admin_signs_instructor_up_for_workshop.py, amy/emails/tests/actions/test_base_action.py, amy/emails/tests/actions/test_instructor_badge_awarded.py, amy/emails/tests/actions/test_instructor_confirmed_for_workshop.py, amy/emails/tests/actions/test_instructor_declined_from_workshop.py, amy/emails/tests/actions/test_instructor_signs_up_for_workshop.py, amy/emails/tests/actions/test_instructor_training_approaching_receiver.py, amy/emails/tests/actions/test_instructor_training_approaching_remove_receiver.py, amy/emails/tests/actions/test_instructor_training_approaching_update_receiver.py, amy/emails/tests/actions/test_persons_merged.py
This fixes #2530 by moving all existing signals/receivers into class-based actions.
Three class based actions currently exist:
1. A base one which just adds new scheduled emails
2. An update action: it fetches exactly one scheduled email and updates its fields
3. A cancel action: it fetches multiple scheduled emails and cancels all of them.
=> [Emails] Refactor receivers into class-based actions

amy/extrequests/filters.py, amy/extrequests/tests/test_filters.py, amy/extrequests/tests/test_training_request.py, amy/workshops/management/commands/fake_database.py
Fixes #2396. The filter itself is simple change thanks to the `member_code_override` field added in #2549.
I also added tests for the whole filterset, and implemented a small fix to the state="Pending or accepted" filter option as a result (it wasn't excluding withdrawn requests).
=> Add filter to training requests view for invalid codes

amy/extrequests/filters.py, amy/extrequests/tests/test_filters.py, amy/extrequests/tests/test_training_request.py, amy/workshops/management/commands/fake_database.py
Depends on #2558 because this edits the same `test_filters.py` file which was introduced there.
Requested in https://github.com/carpentries/amy/issues/2380#issuecomment-1768639578.
=> Add a filter to the workshop request view for requests where an active member did not use their code

amy/extforms/tests/test_training_request_form.py, amy/templates/includes/trainingrequest_details.html, amy/templates/mailing/training_request.html, amy/templates/mailing/training_request.txt, amy/templates/mailing/workshoprequest.txt
- adds `member_code` field to the WRF autoresponse
- adds `member_code_override` field to the TR autoresponse if it is set to `True` (i.e. if it wasn't used, don't include it as it may not have been displayed at all)
- adds a warning to the TR autoresponse if `member_code_override=True` (i.e. if the member code is invalid)
=> Update autoresponses with member codes

amy/workshops/lookups.py, amy/workshops/tests/test_lookups.py
The `KnowledgeDomainLookupView` filters on the `subtag` field, which doesn't actually exist on the `KnowledgeDomain` model. 
(I think this might have been copied across from the equivalent view for the `Language` model.)
This lookup is only used in one view, and it doesn't get much use, so this fix can go into the next regular release.
=> Remove nonexistent field from knowledge domain lookup

amy/extrequests/filters.py, amy/extrequests/tests/test_filters.py
Currently the `member_code_override` `BooleanFilter`, when unchecked, will only display training requests where the override hasn't been used.
It would make more sense that when the filter is unchecked, _all_ requests should be shown, regardless of override usage.
=> Never hide training requests with invalid code when filtering

amy/emails/actions/__init__.py, amy/emails/actions/admin_signs_instructor_up_for_workshop.py, amy/emails/actions/base_action.py, amy/emails/actions/instructor_badge_awarded.py, amy/emails/actions/instructor_confirmed_for_workshop.py, amy/emails/actions/instructor_declined_from_workshop.py, amy/emails/actions/instructor_signs_up_for_workshop.py, amy/emails/actions/instructor_training_approaching.py, amy/emails/actions/instructor_training_completed_not_badged.py, amy/emails/actions/persons_merged.py, amy/emails/controller.py, amy/emails/signals.py, amy/emails/templatetags/emails.py, amy/emails/tests/actions/test_instructor_training_approaching_remove_receiver.py, amy/emails/tests/actions/test_instructor_training_approaching_strategy.py, amy/emails/tests/actions/test_instructor_training_approaching_update_receiver.py, amy/emails/tests/actions/test_instructor_training_completed_not_badged_common_functions.py, amy/emails/tests/actions/test_instructor_training_completed_not_badged_integration.py, amy/emails/tests/actions/test_instructor_training_completed_not_badged_strategy.py, amy/emails/tests/test_template_tags.py, amy/emails/tests/test_utils.py, amy/emails/tests/test_views.py, amy/emails/types.py, amy/emails/utils.py, amy/emails/views.py, amy/scripts/seed_emails.py, amy/templates/emails/email_template_detail.html, amy/templates/emails/email_template_edit.html, amy/trainings/views.py
This fixes #2540.
Add "Instructor Training Completed but not yet badged" email.
This email will be triggered when trainee is given a pass mark on training requirement.
It will update with other training requirements being awarded, and once all requirements have been passed it will cancel.
The email is scheduled to run 2 months after the training has completed (trainee's training requirement event's end date).
From developer's standpoint there's a few small differences between this action and other emails:
1. strategy run function, `run_instructor_training_completed_not_badged_strategy`, is also responsible for getting trainee's training completion date (it may not be available when marking as "passed" other requirements than the training requirement)
2. receiver classes inheriting from …
=> [Emails] Completed instructor training not yet badged

amy/extrequests/forms.py, amy/extrequests/tests/test_training_request.py, amy/extrequests/tests/test_utils.py, amy/extrequests/utils.py, amy/extrequests/views.py, amy/static/task_form.js, amy/workshops/forms.py, amy/workshops/lookups.py, amy/workshops/tests/test_lookups.py, docs/design/index.md, mkdocs.yml
Depends on #2553 so marking as draft until that is merged.
This PR adds two features:
1. on the 'Add task' page, helps the user find the active membership when assigning a learner task (which uses a new lookup)
2. on the 'All trainees' page, adds a checkbox to auto-assign membership seats based on member codes used. This will raise errors for requests that did not provide a code or that provided an invalid code. 
Screenshots:
Note that I get lots of extra warnings raised on my dev instance because the membership dates are randomised, but they're the same warnings as you may see currently when you match trainees through this page. It's only the errors that are new.
=> Automatically assign learner TTT task membership based on code in training application

amy/extforms/forms.py, amy/extforms/tests/test_training_request_form.py
=> Fix IntegrityError and make CoC agreement required

amy/emails/actions/__init__.py, amy/emails/actions/new_membership_onboarding.py, amy/emails/signals.py, amy/emails/tests/actions/test_new_membership_onboarding_common_functions.py, amy/emails/tests/actions/test_new_membership_onboarding_integration.py, amy/emails/tests/actions/test_new_membership_onboarding_strategy.py, amy/emails/types.py, amy/fiscal/forms.py, amy/fiscal/tests/test_membership_members.py, amy/fiscal/views.py, amy/scripts/seed_emails.py, amy/static/amy_utils.js, amy/templates/fiscal/membership_formset.html, config/settings.py
=> [Emails] New membership onboarding email

amy/extforms/tests/test_training_request_form.py, config/settings.py
This enables the feature flag "ENFORCE_MEMBER_CODES", which is required for testing by anonymous users.
=> [Chore] Unconditionally enable "ENFORCE_MEMBER_CODES" feature flag

README.md
There is a legacy line in the README about removing the old database file. This is a holdover from when we were using SQLite.
=> rm line about rm'ing old db

amy/extforms/forms.py, amy/extforms/tests/test_training_request_form.py
Change Instructor Training form to only accept pre-approved applications.
Fixes #2617.
**Visually before:**
**Visually after:**
=> [#2617] Default training requests to preapproved only

config/settings.py
Additional change following migration to v4.2.
=> [#2624] Add CSRF_TRUSTED_ORIGINS because it was missing

amy/emails/templatetags/emails.py, amy/templates/fiscal/membership.html, amy/templates/includes/event_details_table.html, amy/templates/includes/instructorrecruitment.html, amy/templates/includes/related_scheduled_emails.html, amy/templates/includes/related_scheduled_emails_no_empty_msg.html, amy/templates/recruitment/instructorrecruitment_list.html, amy/templates/workshops/person.html, config/settings.py
This fixes #2622 by providing a template to list related scheduled emails. This template was used in Person, Event and Membership models.
=> [Emails] List related scheduled emails

amy/api/v2/serializers.py, amy/api/v2/urls.py, amy/api/v2/views.py, amy/emails/actions/__init__.py, amy/emails/actions/admin_signs_instructor_up_for_workshop.py, amy/emails/actions/host_instructors_introduction.py, amy/emails/actions/instructor_badge_awarded.py, amy/emails/actions/instructor_confirmed_for_workshop.py, amy/emails/actions/instructor_declined_from_workshop.py, amy/emails/actions/instructor_signs_up_for_workshop.py, amy/emails/actions/instructor_training_approaching.py, amy/emails/actions/instructor_training_completed_not_badged.py, amy/emails/actions/new_membership_onboarding.py, amy/emails/actions/new_self_organised_workshop.py, amy/emails/actions/persons_merged.py, amy/emails/actions/post_workshop_7days.py, amy/emails/actions/recruit_helpers.py, amy/emails/schemas.py, amy/emails/signals.py, amy/emails/tests/actions/test_admin_signs_instructor_up_for_workshop.py, amy/emails/tests/actions/test_instructor_badge_awarded.py, amy/emails/tests/actions/test_instructor_confirmed_for_workshop.py, amy/emails/tests/actions/test_instructor_declined_from_workshop.py, amy/emails/tests/actions/test_instructor_signs_up_for_workshop.py, amy/emails/tests/actions/test_new_self_organised_workshop.py, amy/emails/tests/actions/test_persons_merged.py, amy/emails/types.py, amy/emails/utils.py, amy/extrequests/tests/test_selforganised_submissions.py, amy/extrequests/views.py
=> [Emails] New self organised workshop

amy/scripts/seed_emails.py
This fixes missing template seeds.
=> [Emails] Add missing email template seeds for New Self-Organised Workshop and Ask For Website

amy/emails/actions/ask_for_website.py, amy/emails/actions/base_action.py, amy/emails/actions/host_instructors_introduction.py, amy/emails/actions/instructor_training_approaching.py, amy/emails/actions/instructor_training_completed_not_badged.py, amy/emails/actions/new_membership_onboarding.py, amy/emails/actions/post_workshop_7days.py, amy/emails/actions/recruit_helpers.py, amy/emails/management/commands/create_emails_for_existing_events.py, amy/emails/tests/test_views.py
=> [Emails] Management command to enable new emails for existing events

amy/dashboard/tests/test_instructor_recruitment_views.py, amy/dashboard/views.py, amy/emails/tests/actions/test_admin_signs_instructor_up_for_workshop.py, amy/emails/tests/actions/test_instructor_confirmed_for_workshop_receiver.py, amy/emails/tests/actions/test_instructor_declined_from_workshop.py, amy/emails/tests/actions/test_instructor_signs_up_for_workshop.py, amy/recruitment/templatetags/instructorrecruitment.py, amy/recruitment/tests/test_template_tags.py, amy/recruitment/views.py, amy/templates/dashboard/all_feature_flags.html, amy/templates/dashboard/instructor_dashboard.html, amy/templates/navigation_instructor_dashboard.html, amy/templates/workshops/event.html, amy/workshops/base_views.py, amy/workshops/templatetags/feature_flag_conditions.py, amy/workshops/tests/test_base_views.py, amy/workshops/tests/test_template_tags.py, config/settings.py
This fixes #2687.
This fixes #2524.
1. Email module feature flag is enabled.
2. Feature Flags view is enabled in production only for admin users.
3. Small improvements for managing feature flags in UI.
4. Old feature, Instructor Recruitment, was switched to feature flags system (and always enabled).
=> [Emails] Cleanup feature flags

amy/api/v2/tests/test_scheduled_emails_api.py, amy/emails/tests/test_utils.py, amy/emails/tests/test_views.py, amy/emails/utils.py, amy/emails/views.py
This fixes #2694.
The error was caused by accessing event.tags object from the email template; for the worker this object was going to be a list of strings, whereas in the code this was a manager, which needed a different (special) handling. Fix involved serializing the event as the API does it.
=> [Emails] Rendering emails - switch to API serializers to fix error

amy/recruitment/tests/test_instructor_recruitment_views.py, amy/recruitment/views.py
When recruitment is opened or closed, the strategy for host-instructor introduction is run.
This fixes #2695.
=> [Emails] Update trigger for the host-instructor introduction

amy/templates/emails/email_template_list.html, amy/templates/includes/event_details_table.html, amy/templates/workshops/person.html, amy/workshops/views.py
This fixes #2696. New links were introduced to event and person details page.
=> [Emails] Link to other related scheduled emails

amy/emails/actions/ask_for_website.py, amy/emails/actions/host_instructors_introduction.py, amy/emails/actions/instructor_confirmed_for_workshop.py, amy/emails/actions/recruit_helpers.py, amy/emails/tests/actions/test_ask_for_website_cancel_receiver.py, amy/emails/tests/actions/test_ask_for_website_receiver.py, amy/emails/tests/actions/test_ask_for_website_strategy.py, amy/emails/tests/actions/test_ask_for_website_update_receiver.py, amy/emails/tests/actions/test_host_instructors_introduction_cancel_receiver.py, amy/emails/tests/actions/test_host_instructors_introduction_receiver.py, amy/emails/tests/actions/test_host_instructors_introduction_strategy.py, amy/emails/tests/actions/test_host_instructors_introduction_update_receiver.py, amy/emails/tests/actions/test_instructor_confirmed_for_workshop_cancel_receiver.py, amy/emails/tests/actions/test_instructor_confirmed_for_workshop_strategy.py, amy/emails/tests/actions/test_instructor_confirmed_for_workshop_update_receiver.py, amy/emails/tests/actions/test_recruit_helpers_cancel_receiver.py, amy/emails/tests/actions/test_recruit_helpers_receiver.py, amy/emails/tests/actions/test_recruit_helpers_strategy.py, amy/emails/tests/actions/test_recruit_helpers_update_receiver.py, amy/workshops/models.py
AskForWebsite, HostInstructorsIntroduction, InstructorConfirmedForWorkshop and RecruitHelpers now should run only for events tagged SWC/DC/LC, and not run for anything tagged TTT/Circuits/CLDT.
This fixes #2697.
=> [Emails] Update Tag condition for some email actions

amy/templates/dashboard/admin_dashboard.html, amy/templates/includes/event_details_table.html, amy/templates/workshops/all_events.html, amy/templates/workshops/events_merge.html, amy/workshops/forms.py
No migration created since the rename is only in forms and some templates.
This fixes #1992.
=> [#1992] Rename Host->Host Site, Sponsor->Organiser

amy/workshops/models.py, docs/amy_database_structure.md, docs/design/design_patterns.md, docs/design/projects/2023_member_code_enforcement.md, docs/manual_deployment_steps.md, mkdocs.yml
Addresses #2576 except for the admin guide updates.
Merge when ready to release v4.3.
=> Member codes docs

amy/emails/actions/instructor_confirmed_for_workshop.py, amy/emails/tests/actions/test_instructor_confirmed_for_workshop_strategy.py
This email is now only sent to centrally-organised workshops.
This fixes #2717.
=> [Emails] Limit instructor confirmed for workshop email

amy/api/v2/serializers.py, amy/api/v2/urls.py, amy/api/v2/views.py, amy/emails/actions/base_action.py, amy/emails/actions/instructor_badge_awarded.py, amy/emails/actions/instructor_confirmed_for_workshop.py, amy/emails/tests/actions/test_instructor_badge_awarded_cancel_receiver.py, amy/emails/tests/actions/test_instructor_badge_awarded_receiver.py, amy/emails/tests/actions/test_instructor_badge_awarded_strategy.py, amy/emails/tests/actions/test_instructor_badge_awarded_update_receiver.py, amy/emails/tests/actions/test_instructor_confirmed_for_workshop_cancel_receiver.py, amy/emails/tests/actions/test_instructor_confirmed_for_workshop_receiver.py, amy/emails/tests/actions/test_instructor_confirmed_for_workshop_strategy.py, amy/emails/tests/actions/test_instructor_confirmed_for_workshop_update_receiver.py, amy/emails/types.py, amy/emails/utils.py, amy/recruitment/views.py, amy/templates/includes/event_details_table.html, amy/templates/workshops/person.html, amy/workshops/views.py
This fixes #2719 by switching related objects in some emails, which helped in some cases when some entities (Person) were related to multiple of those email types at once:
1. Instructor Confirmed for Workshop: switch from Person to Task as a related object
2. Instructor Badge Awarded: switch from Person to Award as related object
=> [Emails] Change related object to Task in Instructor Confirmed for Workshop and to Award in Instructor Badge Awarded

amy/emails/actions/ask_for_website.py, amy/emails/actions/host_instructors_introduction.py, amy/emails/actions/instructor_confirmed_for_workshop.py, amy/emails/actions/instructor_training_approaching.py, amy/emails/actions/new_membership_onboarding.py, amy/emails/actions/post_workshop_7days.py, amy/emails/actions/recruit_helpers.py
=> [Emails] Change email scheduled condition in some strategies

amy/dashboard/forms.py, amy/dashboard/tests/test_forms.py, amy/dashboard/tests/test_instructor_recruitment_views.py, amy/recruitment/forms.py, amy/recruitment/tests/test_forms.py, amy/recruitment/tests/test_instructor_recruitment_views.py, amy/recruitment/views.py
This fixes #2495 by disallowing multiple signups (both from admin and from the instructor) in open recruitments. Indirectly this also resolves an issue of multiple confirmation emails sent out in the new email system.
=> [Recruitment] Disallow multiple signups for the same person

amy/emails/actions/__init__.py, amy/emails/actions/instructor_declined_from_workshop.py, amy/emails/signals.py, amy/emails/tests/actions/test_instructor_confirmed_for_workshop_receiver.py, amy/emails/tests/actions/test_instructor_declined_from_workshop.py, amy/emails/tests/actions/test_instructor_declined_from_workshop_cancel_receiver.py, amy/emails/tests/actions/test_instructor_declined_from_workshop_receiver.py, amy/emails/tests/actions/test_instructor_declined_from_workshop_strategy.py, amy/emails/tests/actions/test_instructor_declined_from_workshop_update_receiver.py, amy/recruitment/tests/test_instructor_recruitment_views.py, amy/recruitment/views.py
This fixes #2728 by implementing a complex strategy for instructor declined for workshop, and by changing how the strategies are run when instructor recruitment signup is accepted/declined.
=> [Emails] Complex strategy for instructor declined for workshop

.github/workflows/accessibility.yml
upload-artifact versions < v4 are soon to be deprecated: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
=> Update upload-artifact version to v4

amy/emails/actions/instructor_confirmed_for_workshop.py, amy/emails/actions/instructor_task_created_for_workshop.py, amy/emails/signals.py, amy/emails/tests/actions/test_instructor_confirmed_for_workshop_cancel_receiver.py, amy/emails/tests/actions/test_instructor_confirmed_for_workshop_receiver.py, amy/emails/tests/actions/test_instructor_confirmed_for_workshop_strategy.py, amy/emails/tests/actions/test_instructor_confirmed_for_workshop_update_receiver.py, amy/emails/tests/actions/test_instructor_declined_from_workshop_cancel_receiver.py, amy/emails/tests/actions/test_instructor_declined_from_workshop_strategy.py, amy/emails/tests/actions/test_instructor_declined_from_workshop_update_receiver.py, amy/emails/tests/actions/test_instructor_task_created_for_workshop_cancel_receiver.py, amy/emails/tests/actions/test_instructor_task_created_for_workshop_receiver.py, amy/emails/tests/actions/test_instructor_task_created_for_workshop_strategy.py, amy/emails/tests/actions/test_instructor_task_created_for_workshop_update_receiver.py, amy/emails/types.py, amy/recruitment/tests/test_instructor_recruitment_views.py, amy/recruitment/views.py, amy/scripts/seed_emails.py, amy/templates/workshops/person_edit_form.html, amy/templates/workshops/task.html, amy/workshops/forms.py, amy/workshops/views.py
This fixes #2449.
There were some minor bugs discovered and fixed along the way.
Email action "Instructor Confirmed for Workshop" was split and changed. Now a similar email only handles Recruitment process (accepting/declining an instructor signup), and a new email "Instructor Task Created for Workshop" handles instructor tasks in centrally-organised workshops.
~~WIP because of this comment: https://github.com/carpentries/amy/issues/2449#issuecomment-2591127828~~
=> Emails: Improve managing instructor task in recruitments, new email action Instructor Task Created for Workshop

amy/templates/workshops/event.html, amy/templates/workshops/event_edit_form.html
=> Remove missed columns with URL field for tasks

amy/api/v2/serializers.py, amy/workshops/tests/runner.py
This fixes #2771 - a problem in REST API serializer definition that causes issue in the email worker.
=> feat(#2771): Update API serializer for inline Attachments
